TdZdd: tdzdd::MyListOnPool< T > Class Template Reference
tdzdd::MyListOnPool< T > Class Template Reference
#include <MyList.hpp>
Classes
struct Cell
class const_iterator
class iterator
Public Member Functions
MyListOnPool ()
MyListOnPool (MyListOnPool const &o)
MyListOnPool & operator= (MyListOnPool const &o)
virtual ~MyListOnPool ()
size_t size () const
Returns the number of elements.
bool empty () const
Checks emptiness.
void clear ()
Initializes the array to be empty.
T * front ()
Accesses the first element.
T const * front () const
Accesses the first element.
template<typename Pool >
T * alloc_front (Pool &pool, size_t numElements=1)
Allocates a contiguous memory block for one or more new elements at the beginning.
void pop_front ()
Removes a memory block at the beginning.
iterator begin ()
Returns an iterator to the beginning.
const_iterator begin () const
Returns an iterator to the beginning.
iterator end ()
Returns an iterator to the end.
const_iterator end () const
Returns an iterator to the end.
Static Private Member Functions
static size_t dataCells (size_t n)
static size_t workCells (size_t n)
static T * dataStart (Cell *p)
static T const * dataStart (Cell const *p)
Private Attributes
Cell * front_
size_t size_
Friends
std::ostream & operator<< (std::ostream &os, MyListOnPool const &o)
Get the hash code of this object.
Detailed Description
template<typename T>
class tdzdd::MyListOnPool< T >
Definition at line 335 of file MyList.hpp.
Constructor & Destructor Documentation
template<typename T> tdzdd::MyListOnPool< T >::MyListOnPool () inline
Definition at line 360 of file MyList.hpp.
template<typename T> tdzdd::MyListOnPool< T >::MyListOnPool (MyListOnPool< T > const & o) inline
Definition at line 364 of file MyList.hpp.
template<typename T> virtual tdzdd::MyListOnPool< T >::~MyListOnPool () inline virtual
Definition at line 389 of file MyList.hpp.
References tdzdd::MyList< T, BLOCK_ELEMENTS >::clear().
Member Function Documentation
template<typename T> template<typename Pool > T* tdzdd::MyListOnPool< T >::alloc_front (Pool & pool, size_t numElements = 1) inline
Allocates a contiguous memory block for one or more new elements at the beginning.
The memory block is not initialized.
Parameters
pool memory pool for allocating new entries.
numElements the number of elements.
Returns
pointer to the memory block.
Definition at line 444 of file MyList.hpp.
References tdzdd::MyList< T, BLOCK_ELEMENTS >::dataStart(), tdzdd::MyList< T, BLOCK_ELEMENTS >::front_, tdzdd::MyListOnPool< T >::Cell::next, and tdzdd::MyList< T, BLOCK_ELEMENTS >::size_.
template<typename T> iterator tdzdd::MyListOnPool< T >::begin () inline
Returns an iterator to the beginning.
Returns
iterator to the beginning.
Definition at line 518 of file MyList.hpp.
Referenced by tdzdd::ZddSubsetter< S >::subset(), and tdzdd::ZddSubsetterMP< S >::subset().
template<typename T> const_iterator tdzdd::MyListOnPool< T >::begin () const inline
Returns an iterator to the beginning.
Returns
iterator to the beginning.
Definition at line 526 of file MyList.hpp.
template<typename T> void tdzdd::MyListOnPool< T >::clear () inline
Initializes the array to be empty.
The memory is left unused on the pool.
Definition at line 414 of file MyList.hpp.
template<typename T> static size_t tdzdd::MyListOnPool< T >::dataCells (size_t n) inline static private
Definition at line 343 of file MyList.hpp.
template<typename T> static T* tdzdd::MyListOnPool< T >::dataStart (Cell * p) inline static private
Definition at line 351 of file MyList.hpp.
template<typename T> static T const* tdzdd::MyListOnPool< T >::dataStart (Cell const * p) inline static private
Definition at line 355 of file MyList.hpp.
template<typename T> bool tdzdd::MyListOnPool< T >::empty () const inline
Checks emptiness.
Returns
true if empty.
Definition at line 405 of file MyList.hpp.
Referenced by tdzdd::MyListOnPool< T >::operator=().
template<typename T> iterator tdzdd::MyListOnPool< T >::end () inline
Returns an iterator to the end.
Returns
iterator to the end.
Definition at line 534 of file MyList.hpp.
Referenced by tdzdd::ZddSubsetter< S >::subset(), and tdzdd::ZddSubsetterMP< S >::subset().
template<typename T> const_iterator tdzdd::MyListOnPool< T >::end () const inline
Returns an iterator to the end.
Returns
iterator to the end.
Definition at line 542 of file MyList.hpp.
template<typename T> T* tdzdd::MyListOnPool< T >::front () inline
Accesses the first element.
Returns
pointer to the first element.
Definition at line 423 of file MyList.hpp.
References tdzdd::MyList< T, BLOCK_ELEMENTS >::dataStart().
Referenced by tdzdd::ZddSubsetter< S >::subset().
template<typename T> T const* tdzdd::MyListOnPool< T >::front () const inline
Accesses the first element.
Returns
pointer to the first element.
Definition at line 431 of file MyList.hpp.
References tdzdd::MyList< T, BLOCK_ELEMENTS >::dataStart().
template<typename T> MyListOnPool& tdzdd::MyListOnPool< T >::operator= (MyListOnPool< T > const & o) inline
Definition at line 368 of file MyList.hpp.
References tdzdd::MyListOnPool< T >::empty().
template<typename T> void tdzdd::MyListOnPool< T >::pop_front () inline
Removes a memory block at the beginning.
Definition at line 457 of file MyList.hpp.
References tdzdd::MyListOnPool< T >::Cell::next, and tdzdd::MyList< T, BLOCK_ELEMENTS >::size_.
template<typename T> size_t tdzdd::MyListOnPool< T >::size () const inline
Returns the number of elements.
Returns
the number of elements.
Definition at line 397 of file MyList.hpp.
References tdzdd::MyList< T, BLOCK_ELEMENTS >::size_.
Referenced by tdzdd::ZddSubsetter< S >::subset(), and tdzdd::ZddSubsetterMP< S >::subset().
template<typename T> static size_t tdzdd::MyListOnPool< T >::workCells (size_t n) inline static private
Definition at line 347 of file MyList.hpp.
Friends And Related Function Documentation
template<typename T> std::ostream& operator<< (std::ostream & os, MyListOnPool< T > const & o) friend
Get the hash code of this object.
Returns
the hash code. Check equivalence between another object.
Parameters
o another object.
Returns
true if equivalent. Sends an object to an output stream.
Parameters
os the output stream.
o the object.
Returns
os.
Definition at line 577 of file MyList.hpp.
Member Data Documentation
template<typename T> Cell* tdzdd::MyListOnPool< T >::front_ private
Definition at line 340 of file MyList.hpp.
template<typename T> size_t tdzdd::MyListOnPool< T >::size_ private
Definition at line 341 of file MyList.hpp.
The documentation for this class was generated from the following file:
include/tdzdd/util/MyList.hpp