TdZdd: tdzdd::MyList< T, BLOCK_ELEMENTS >::iterator Class Reference
tdzdd::MyList< T, BLOCK_ELEMENTS >::iterator Class Reference
#include <MyList.hpp>
Public Member Functions
iterator (Cell *front)
T * operator* () const
T * operator-> () const
iterator & operator++ ()
bool operator== (iterator const &o) const
bool operator!= (iterator const &o) const
Private Attributes
Cell * front
Detailed Description
template<typename T, size_t BLOCK_ELEMENTS = 1000>
class tdzdd::MyList< T, BLOCK_ELEMENTS >::iterator
Definition at line 199 of file MyList.hpp.
Constructor & Destructor Documentation
template<typename T, size_t BLOCK_ELEMENTS = 1000> tdzdd::MyList< T, BLOCK_ELEMENTS >::iterator::iterator (Cell * front) inline
Definition at line 203 of file MyList.hpp.
Member Function Documentation
template<typename T, size_t BLOCK_ELEMENTS = 1000> bool tdzdd::MyList< T, BLOCK_ELEMENTS >::iterator::operator!= (iterator const & o) const inline
Definition at line 224 of file MyList.hpp.
References tdzdd::MyList< T, BLOCK_ELEMENTS >::iterator::front.
template<typename T, size_t BLOCK_ELEMENTS = 1000> T* tdzdd::MyList< T, BLOCK_ELEMENTS >::iterator::operator* () const inline
Definition at line 207 of file MyList.hpp.
References tdzdd::MyList< T, BLOCK_ELEMENTS >::dataStart().
template<typename T, size_t BLOCK_ELEMENTS = 1000> iterator& tdzdd::MyList< T, BLOCK_ELEMENTS >::iterator::operator++ () inline
Definition at line 215 of file MyList.hpp.
References tdzdd::MyList< T, BLOCK_ELEMENTS >::clearFlag(), and tdzdd::MyList< T, BLOCK_ELEMENTS >::Cell::next.
template<typename T, size_t BLOCK_ELEMENTS = 1000> T* tdzdd::MyList< T, BLOCK_ELEMENTS >::iterator::operator-> () const inline
Definition at line 211 of file MyList.hpp.
References tdzdd::MyList< T, BLOCK_ELEMENTS >::dataStart().
template<typename T, size_t BLOCK_ELEMENTS = 1000> bool tdzdd::MyList< T, BLOCK_ELEMENTS >::iterator::operator== (iterator const & o) const inline
Definition at line 220 of file MyList.hpp.
References tdzdd::MyList< T, BLOCK_ELEMENTS >::iterator::front.
Member Data Documentation
template<typename T, size_t BLOCK_ELEMENTS = 1000> Cell* tdzdd::MyList< T, BLOCK_ELEMENTS >::iterator::front private
Definition at line 200 of file MyList.hpp.
Referenced by tdzdd::MyList< T, BLOCK_ELEMENTS >::iterator::operator!=(), tdzdd::MyList< T, BLOCK_ELEMENTS >::const_iterator::operator!=(), tdzdd::MyList< T, BLOCK_ELEMENTS >::iterator::operator==(), and tdzdd::MyList< T, BLOCK_ELEMENTS >::const_iterator::operator==().
The documentation for this class was generated from the following file:
include/tdzdd/util/MyList.hpp