TdZdd: tdzdd::DdSpecBase< S, AR > Class Template Reference
tdzdd::DdSpecBase< S, AR > Class Template Reference
Base class of DD specs.
#include <DdSpec.hpp>
Public Member Functions
S & entity ()
S const & entity () const
void printLevel (std::ostream &os, int level) const
std::vector< std::pair< int,
int > > findOneInstance () const
Returns a random instance using simple depth-first search without caching.
void dumpDot (std::ostream &os=std::cout, std::string title=typenameof< S >()) const
Dumps the node table in Graphviz (dot) format.
Static Public Attributes
static int const ARITY = AR
Static Protected Member Functions
template<typename T >
static size_t rawHashCode (T const &o)
template<typename T >
static size_t rawEqualTo (T const &o1, T const &o2)
Friends
std::ostream & operator<< (std::ostream &os, DdSpecBase const &o)
Dumps the node table in Graphviz (dot) format.
Detailed Description
template<typename S, int AR>
class tdzdd::DdSpecBase< S, AR >
Base class of DD specs.
Every implementation must have the following functions:
int datasize() const
int get_root(void* p)
int get_child(void* p, int level, int value)
void get_copy(void* to, void const* from)
int merge_states(void* p1, void* p2)
void destruct(void* p)
void destructLevel(int level)
size_t hash_code(void const* p, int level) const
bool equal_to(void const* p, void const* q, int level) const
void print_state(std::ostream& os, void const* p, int level) const
Optionally, the following functions can be overloaded:
void printLevel(std::ostream& os, int level) const
A return code of get_root(void*) or get_child(void*, int, bool) is: 0 when the node is the 0-terminal, -1 when it is the 1-terminal, or the node level when it is a non-terminal. A return code of merge_states(void*, void*) is: 0 when the states are merged into the first one, 1 when they cannot be merged and the first one should be forwarded to the 0-terminal, 2 when they cannot be merged and the second one should be forwarded to the 0-terminal.
Template Parameters
S the class implementing this class.
AR arity of the nodes.
Definition at line 68 of file DdSpec.hpp.
Member Function Documentation
template<typename S, int AR> void tdzdd::DdSpecBase< S, AR >::dumpDot (std::ostream & os = std::cout, std::string title = typenameof<S>()) const inline
Dumps the node table in Graphviz (dot) format.
Parameters
os the output stream.
title title label.
Definition at line 102 of file DdSpec.hpp.
template<typename S, int AR> S& tdzdd::DdSpecBase< S, AR >::entity () inline
Definition at line 72 of file DdSpec.hpp.
Referenced by tdzdd::DdStructure< ARITY >::DdStructure(), tdzdd::DdSpecBase< DdStructure< ARITY >, AR >::dumpDot(), tdzdd::DdSpec< DdStructure< ARITY >, NodeId, ARITY >::equal_to(), tdzdd::HybridDdSpec< S, TS, TA, AR >::equal_to(), tdzdd::DdSpec< DdStructure< ARITY >, NodeId, ARITY >::equalToAtLevel(), tdzdd::HybridDdSpec< S, TS, TA, AR >::equalToAtLevel(), tdzdd::DdSpecBase< DdStructure< ARITY >, AR >::findOneInstance(), tdzdd::StatelessDdSpec< S, AR >::get_child(), tdzdd::DdSpec< DdStructure< ARITY >, NodeId, ARITY >::get_child(), tdzdd::PodArrayDdSpec< S, T, AR >::get_child(), tdzdd::HybridDdSpec< S, TS, TA, AR >::get_child(), tdzdd::DdSpec< DdStructure< ARITY >, NodeId, ARITY >::get_copy(), tdzdd::HybridDdSpec< S, TS, TA, AR >::get_copy(), tdzdd::StatelessDdSpec< S, AR >::get_root(), tdzdd::DdSpec< DdStructure< ARITY >, NodeId, ARITY >::get_root(), tdzdd::PodArrayDdSpec< S, T, AR >::get_root(), tdzdd::HybridDdSpec< S, TS, TA, AR >::get_root(), tdzdd::DdSpec< DdStructure< ARITY >, NodeId, ARITY >::hash_code(), tdzdd::HybridDdSpec< S, TS, TA, AR >::hash_code(), tdzdd::DdSpec< DdStructure< ARITY >, NodeId, ARITY >::hashCodeAtLevel(), tdzdd::HybridDdSpec< S, TS, TA, AR >::hashCodeAtLevel(), tdzdd::DdSpec< DdStructure< ARITY >, NodeId, ARITY >::merge_states(), tdzdd::PodArrayDdSpec< S, T, AR >::merge_states(), tdzdd::HybridDdSpec< S, TS, TA, AR >::merge_states(), tdzdd::DdSpec< DdStructure< ARITY >, NodeId, ARITY >::print_state(), tdzdd::PodArrayDdSpec< S, T, AR >::print_state(), tdzdd::HybridDdSpec< S, TS, TA, AR >::print_state(), tdzdd::DdSpec< DdStructure< ARITY >, NodeId, ARITY >::printStateAtLevel(), tdzdd::PodArrayDdSpec< S, T, AR >::printStateAtLevel(), tdzdd::HybridDdSpec< S, TS, TA, AR >::printStateAtLevel(), and tdzdd::DdStructure< ARITY >::zddSubset().
template<typename S, int AR> S const& tdzdd::DdSpecBase< S, AR >::entity () const inline
Definition at line 76 of file DdSpec.hpp.
template<typename S, int AR> std::vector<std::pair<int,int> > tdzdd::DdSpecBase< S, AR >::findOneInstance () const inline
Returns a random instance using simple depth-first search without caching.
It does not guarantee that the selection is uniform. merge_states(void*, void*) is not supported.
Returns
a collection of (item, value) pairs.
Exceptions
std::runtime_error no instance exists.
Definition at line 92 of file DdSpec.hpp.
Referenced by tdzdd::DdSpecBase< DdStructure< ARITY >, AR >::findOneInstance().
template<typename S, int AR> void tdzdd::DdSpecBase< S, AR >::printLevel (std::ostream & os, int level) const inline
Definition at line 80 of file DdSpec.hpp.
template<typename S, int AR> template<typename T > static size_t tdzdd::DdSpecBase< S, AR >::rawEqualTo (T const & o1, T const & o2) inline static protected
Definition at line 157 of file DdSpec.hpp.
Referenced by tdzdd::DdSpec< DdStructure< ARITY >, NodeId, ARITY >::equalTo(), and tdzdd::HybridDdSpec< S, TS, TA, AR >::equalTo().
template<typename S, int AR> template<typename T > static size_t tdzdd::DdSpecBase< S, AR >::rawHashCode (T const & o) inline static protected
Definition at line 143 of file DdSpec.hpp.
Referenced by tdzdd::DdSpec< DdStructure< ARITY >, NodeId, ARITY >::hashCode(), and tdzdd::HybridDdSpec< S, TS, TA, AR >::hashCode().
Friends And Related Function Documentation
template<typename S, int AR> std::ostream& operator<< (std::ostream & os, DdSpecBase< S, AR > const & o) friend
Dumps the node table in Graphviz (dot) format.
Parameters
os the output stream.
o the ZDD.
Returns
os itself.
Definition at line 114 of file DdSpec.hpp.
Member Data Documentation
template<typename S, int AR> int const tdzdd::DdSpecBase< S, AR >::ARITY = AR static
Definition at line 70 of file DdSpec.hpp.
The documentation for this class was generated from the following file:
include/tdzdd/DdSpec.hpp