TdZdd: tdzdd::PodArrayDdSpec< S, T, AR > Class Template Reference
tdzdd::PodArrayDdSpec< S, T, AR > Class Template Reference
Abstract class of DD specifications using POD array states.
#include <DdSpec.hpp>
Public Types
typedef T State
Public Member Functions
PodArrayDdSpec ()
int datasize () const
int get_root (void *p)
int get_child (void *p, int level, int value)
void get_copy (void *to, void const *from)
int mergeStates (T *a1, T *a2)
int merge_states (void *p1, void *p2)
void destruct (void *p)
void destructLevel (int level)
size_t hash_code (void const *p, int level) const
bool equal_to (void const *p, void const *q, int level) const
void printState (std::ostream &os, State const *a) const
void printStateAtLevel (std::ostream &os, State const *a, int level) const
void print_state (std::ostream &os, void const *p, int level) const
Public Member Functions inherited from tdzdd::DdSpecBase< S, AR >
S & entity ()
S const & entity () const
void printLevel (std::ostream &os, int level) const
std::vector< std::pair< int,
int > > findOneInstance () const
Returns a random instance using simple depth-first search without caching.
void dumpDot (std::ostream &os=std::cout, std::string title=typenameof< S >()) const
Dumps the node table in Graphviz (dot) format.
Protected Member Functions
void setArraySize (int n)
int getArraySize () const
Additional Inherited Members
Static Public Attributes inherited from tdzdd::DdSpecBase< S, AR >
static int const ARITY = AR
Static Protected Member Functions inherited from tdzdd::DdSpecBase< S, AR >
template<typename T >
static size_t rawHashCode (T const &o)
template<typename T >
static size_t rawEqualTo (T const &o1, T const &o2)
Detailed Description
template<typename S, typename T, int AR>
class tdzdd::PodArrayDdSpec< S, T, AR >
Abstract class of DD specifications using POD array states.
The size of array must be set by setArraySize(int n) in the constructor and cannot be changed. If you want some arbitrary-sized data storage for states, use pointers to those storages in DdSpec instead.
Every implementation must have the following functions:
int getRoot(T* array)
int getChild(T* array, int level, int value)
Optionally, the following functions can be overloaded:
void mergeStates(T* array1, T* array2)
void printLevel(std::ostream& os, int level) const
void printState(std::ostream& os, State const* array) const
Template Parameters
S the class implementing this class.
T data type of array elements.
AR arity of the nodes.
Definition at line 360 of file DdSpec.hpp.
Member Typedef Documentation
template<typename S , typename T , int AR> typedef T tdzdd::PodArrayDdSpec< S, T, AR >::State
Definition at line 362 of file DdSpec.hpp.
Constructor & Destructor Documentation
template<typename S , typename T , int AR> tdzdd::PodArrayDdSpec< S, T, AR >::PodArrayDdSpec () inline
Definition at line 393 of file DdSpec.hpp.
Member Function Documentation
template<typename S , typename T , int AR> int tdzdd::PodArrayDdSpec< S, T, AR >::datasize () const inline
Definition at line 397 of file DdSpec.hpp.
template<typename S , typename T , int AR> void tdzdd::PodArrayDdSpec< S, T, AR >::destruct (void * p) inline
Definition at line 430 of file DdSpec.hpp.
template<typename S , typename T , int AR> void tdzdd::PodArrayDdSpec< S, T, AR >::destructLevel (int level) inline
Definition at line 433 of file DdSpec.hpp.
template<typename S , typename T , int AR> bool tdzdd::PodArrayDdSpec< S, T, AR >::equal_to (void const * p, void const * q, int level) const inline
Definition at line 447 of file DdSpec.hpp.
template<typename S , typename T , int AR> int tdzdd::PodArrayDdSpec< S, T, AR >::get_child (void * p, int level, int value) inline
Definition at line 408 of file DdSpec.hpp.
References tdzdd::DdSpecBase< S, AR >::entity().
template<typename S , typename T , int AR> void tdzdd::PodArrayDdSpec< S, T, AR >::get_copy (void * to, void const * from) inline
Definition at line 413 of file DdSpec.hpp.
template<typename S , typename T , int AR> int tdzdd::PodArrayDdSpec< S, T, AR >::get_root (void * p) inline
Definition at line 404 of file DdSpec.hpp.
References tdzdd::DdSpecBase< S, AR >::entity().
template<typename S , typename T , int AR> int tdzdd::PodArrayDdSpec< S, T, AR >::getArraySize () const inline protected
Definition at line 388 of file DdSpec.hpp.
template<typename S , typename T , int AR> size_t tdzdd::PodArrayDdSpec< S, T, AR >::hash_code (void const * p, int level) const inline
Definition at line 436 of file DdSpec.hpp.
template<typename S , typename T , int AR> int tdzdd::PodArrayDdSpec< S, T, AR >::merge_states (void * p1, void * p2) inline
Definition at line 426 of file DdSpec.hpp.
References tdzdd::DdSpecBase< S, AR >::entity().
template<typename S , typename T , int AR> int tdzdd::PodArrayDdSpec< S, T, AR >::mergeStates (T * a1, T * a2) inline
Definition at line 422 of file DdSpec.hpp.
template<typename S , typename T , int AR> void tdzdd::PodArrayDdSpec< S, T, AR >::print_state (std::ostream & os, void const * p, int level) const inline
Definition at line 470 of file DdSpec.hpp.
References tdzdd::DdSpecBase< S, AR >::entity().
template<typename S , typename T , int AR> void tdzdd::PodArrayDdSpec< S, T, AR >::printState (std::ostream & os, State const * a) const inline
Definition at line 457 of file DdSpec.hpp.
template<typename S , typename T , int AR> void tdzdd::PodArrayDdSpec< S, T, AR >::printStateAtLevel (std::ostream & os, State const * a, int level) const inline
Definition at line 466 of file DdSpec.hpp.
References tdzdd::DdSpecBase< S, AR >::entity().
template<typename S , typename T , int AR> void tdzdd::PodArrayDdSpec< S, T, AR >::setArraySize (int n) inline protected
Definition at line 379 of file DdSpec.hpp.
The documentation for this class was generated from the following file:
include/tdzdd/DdSpec.hpp