TdZdd: tdzdd::BddLookahead< S > Class Template Reference
tdzdd::BddLookahead< S > Class Template Reference
#include <Lookahead.hpp>
Public Member Functions
BddLookahead (S const &s)
int datasize () const
int get_root (void *p)
int get_child (void *p, int level, int b)
void get_copy (void *to, void const *from)
int merge_states (void *p1, void *p2)
void destruct (void *p)
void destructLevel (int level)
size_t hash_code (void const *p, int level) const
bool equal_to (void const *p, void const *q, int level) const
void print_state (std::ostream &os, void const *p, int level) const
void print_level (std::ostream &os, int level) const
Public Member Functions inherited from tdzdd::DdSpecBase< BddLookahead< S >, S::ARITY >
BddLookahead< S > & entity ()
BddLookahead< S >const & entity () const
void printLevel (std::ostream &os, int level) const
std::vector< std::pair< int, int > > findOneInstance () const
Returns a random instance using simple depth-first search without caching.
void dumpDot (std::ostream &os=std::cout, std::string title=typenameof< BddLookahead< S > >()) const
Dumps the node table in Graphviz (dot) format.
Private Types
typedef S Spec
Private Member Functions
int lookahead (void *p, int level)
Private Attributes
Spec spec
std::vector< char > work0
std::vector< char > work1
Additional Inherited Members
Static Public Attributes inherited from tdzdd::DdSpecBase< BddLookahead< S >, S::ARITY >
static int const ARITY
Static Protected Member Functions inherited from tdzdd::DdSpecBase< BddLookahead< S >, S::ARITY >
static size_t rawHashCode (T const &o)
static size_t rawEqualTo (T const &o1, T const &o2)
Detailed Description
template<typename S>
class tdzdd::BddLookahead< S >
Definition at line 36 of file Lookahead.hpp.
Member Typedef Documentation
template<typename S > typedef S tdzdd::BddLookahead< S >::Spec private
Definition at line 37 of file Lookahead.hpp.
Constructor & Destructor Documentation
template<typename S > tdzdd::BddLookahead< S >::BddLookahead (S const & s) inline
Definition at line 72 of file Lookahead.hpp.
Member Function Documentation
template<typename S > int tdzdd::BddLookahead< S >::datasize () const inline
Definition at line 76 of file Lookahead.hpp.
template<typename S > void tdzdd::BddLookahead< S >::destruct (void * p) inline
Definition at line 96 of file Lookahead.hpp.
template<typename S > void tdzdd::BddLookahead< S >::destructLevel (int level) inline
Definition at line 100 of file Lookahead.hpp.
template<typename S > bool tdzdd::BddLookahead< S >::equal_to (void const * p, void const * q, int level) const inline
Definition at line 108 of file Lookahead.hpp.
template<typename S > int tdzdd::BddLookahead< S >::get_child (void * p, int level, int b) inline
Definition at line 84 of file Lookahead.hpp.
References tdzdd::BddLookahead< S >::lookahead().
template<typename S > void tdzdd::BddLookahead< S >::get_copy (void * to, void const * from) inline
Definition at line 88 of file Lookahead.hpp.
template<typename S > int tdzdd::BddLookahead< S >::get_root (void * p) inline
Definition at line 80 of file Lookahead.hpp.
References tdzdd::BddLookahead< S >::lookahead().
template<typename S > size_t tdzdd::BddLookahead< S >::hash_code (void const * p, int level) const inline
Definition at line 104 of file Lookahead.hpp.
template<typename S > int tdzdd::BddLookahead< S >::lookahead (void * p, int level) inline private
Definition at line 43 of file Lookahead.hpp.
Referenced by tdzdd::BddLookahead< S >::get_child(), tdzdd::ZddLookahead< S >::get_child(), tdzdd::BddLookahead< S >::get_root(), and tdzdd::ZddLookahead< S >::get_root().
template<typename S > int tdzdd::BddLookahead< S >::merge_states (void * p1, void * p2) inline
Definition at line 92 of file Lookahead.hpp.
template<typename S > void tdzdd::BddLookahead< S >::print_level (std::ostream & os, int level) const inline
Definition at line 116 of file Lookahead.hpp.
template<typename S > void tdzdd::BddLookahead< S >::print_state (std::ostream & os, void const * p, int level) const inline
Definition at line 112 of file Lookahead.hpp.
Member Data Documentation
template<typename S > Spec tdzdd::BddLookahead< S >::spec private
Definition at line 39 of file Lookahead.hpp.
template<typename S > std::vector<char> tdzdd::BddLookahead< S >::work0 private
Definition at line 40 of file Lookahead.hpp.
template<typename S > std::vector<char> tdzdd::BddLookahead< S >::work1 private
Definition at line 41 of file Lookahead.hpp.
The documentation for this class was generated from the following file:
include/tdzdd/op/Lookahead.hpp