TdZdd: tdzdd::NodeTableEntity< ARITY > Class Template Reference
tdzdd::NodeTableEntity< ARITY > Class Template Reference
#include <NodeTable.hpp>
Public Member Functions
NodeTableEntity (int n=1)
Constructor.
void init (int n)
Clears and initializes the table.
void initTerminals ()
Initializes the terminal nodes.
size_t size () const
Gets the variable ID at a given level.
int numVars () const
Gets the number of ZDD variables.
void stretchBottom (int n)
Changes the number of ZDD variables by shifting up/down the levels of existing variables.
Node< ARITY > const & node (NodeId f) const
Gets a node.
Node< ARITY > & node (NodeId f)
Gets a reference to a node.
NodeId child (NodeId f, int b) const
Gets a child node ID.
NodeId & child (NodeId f, int b)
Gets a reference to a child node ID.
NodeId child (int i, size_t j, int b) const
Gets a child node ID.
NodeId & child (int i, size_t j, int b)
Gets a reference to a child node ID.
NodeId getZeroDescendant (NodeId f, int stopLevel) const
Gets a descendant node ID by tracing 0-edges.
void deleteIndex ()
Deletes current index information.
void makeIndex (bool useMP=false) const
Makes index information.
MyVector< int > const & higherLevels (int level) const
Returns a collection of the higher levels that directly refers the given level and that does not refer any lower levels.
MyVector< int > const & lowerLevels (int level) const
Returns a collection of the lower levels that are referred by the given level and that are not referred directly by any higher levels.
void dumpDot (std::ostream &os, std::string title="") const
Dumps the node table in Graphviz (dot) format.
Public Member Functions inherited from tdzdd::DataTable< Node< ARITY > >
DataTable (int n=0)
Constructor.
DataTable (DataTable const &o)
DataTable & operator= (DataTable const &o)
void init (int n=0)
Clears and initializes the table.
void setNumRows (int n)
Resizes the table rows.
void initRow (int i, size_t size)
Clears and initializes a row.
size_t addColumn (int i)
Clears and initializes a row.
int numRows () const
Gets the number of rows.
size_t totalSize () const
Gets the total number of elements in the table.
MyVector< Node< ARITY > > & operator[] (int i)
Accesses to a row.
MyVector< Node< ARITY > > const & operator[] (int i) const
Accesses to a row.
Private Attributes
MyVector< MyVector< int > > higherLevelTable
MyVector< MyVector< int > > lowerLevelTable
Detailed Description
template<int ARITY>
class tdzdd::NodeTableEntity< ARITY >
Definition at line 40 of file NodeTable.hpp.
Constructor & Destructor Documentation
template<int ARITY> tdzdd::NodeTableEntity< ARITY >::NodeTableEntity (int n = 1) inline
Constructor.
Parameters
n the number of rows.
Definition at line 49 of file NodeTable.hpp.
Member Function Documentation
template<int ARITY> NodeId tdzdd::NodeTableEntity< ARITY >::child (NodeId f, int b) const inline
Gets a child node ID.
Parameters
f parent node ID.
b child branch.
Returns
the b-child of f.
Definition at line 186 of file NodeTable.hpp.
Referenced by tdzdd::DdReducer< ARITY, BDD, ZDD >::algorithmR(), tdzdd::NodeTableEntity< AR >::child(), tdzdd::ZddSubsetter< S >::downTable(), tdzdd::ZddSubsetterMP< S >::downTable(), tdzdd::NodeTableEntity< AR >::dumpDot(), tdzdd::DdReducer< ARITY, BDD, ZDD >::garbageCollect(), tdzdd::NodeTableEntity< AR >::getZeroDescendant(), tdzdd::DdReducer< ARITY, BDD, ZDD >::makeReadyForSequentialReduction(), and tdzdd::NodeTableEntity< AR >::stretchBottom().
template<int ARITY> NodeId& tdzdd::NodeTableEntity< ARITY >::child (NodeId f, int b) inline
Gets a reference to a child node ID.
Parameters
f parent node ID.
b child branch.
Returns
the b-child of f.
Definition at line 196 of file NodeTable.hpp.
template<int ARITY> NodeId tdzdd::NodeTableEntity< ARITY >::child (int i, size_t j, int b) const inline
Gets a child node ID.
Parameters
i parent row.
j parent column.
b child branch.
Returns
the b-child of the parent.
Definition at line 207 of file NodeTable.hpp.
template<int ARITY> NodeId& tdzdd::NodeTableEntity< ARITY >::child (int i, size_t j, int b) inline
Gets a reference to a child node ID.
Parameters
i parent row.
j parent column.
b child branch.
Returns
the b-child of the parent.
Definition at line 219 of file NodeTable.hpp.
template<int ARITY> void tdzdd::NodeTableEntity< ARITY >::deleteIndex () inline
Deletes current index information.
Definition at line 242 of file NodeTable.hpp.
template<int ARITY> void tdzdd::NodeTableEntity< ARITY >::dumpDot (std::ostream & os, std::string title = "") const inline
Dumps the node table in Graphviz (dot) format.
Parameters
os output stream.
title title label.
Definition at line 331 of file NodeTable.hpp.
template<int ARITY> NodeId tdzdd::NodeTableEntity< ARITY >::getZeroDescendant (NodeId f, int stopLevel) const inline
Gets a descendant node ID by tracing 0-edges.
Parameters
f parent node ID.
stopLevel level to stop going down.
Returns
reached node ID.
Definition at line 230 of file NodeTable.hpp.
template<int ARITY> MyVector<int> const& tdzdd::NodeTableEntity< ARITY >::higherLevels (int level) const inline
Returns a collection of the higher levels that directly refers the given level and that does not refer any lower levels.
Parameters
level the level.
Definition at line 310 of file NodeTable.hpp.
template<int ARITY> void tdzdd::NodeTableEntity< ARITY >::init (int n) inline
Clears and initializes the table.
Parameters
n the number of rows.
Definition at line 59 of file NodeTable.hpp.
Referenced by tdzdd::NodeTableEntity< AR >::init(), tdzdd::ZddSubsetter< S >::initialize(), and tdzdd::ZddSubsetterMP< S >::initialize().
template<int ARITY> void tdzdd::NodeTableEntity< ARITY >::initTerminals () inline
Initializes the terminal nodes.
Definition at line 68 of file NodeTable.hpp.
Referenced by tdzdd::DdReducer< ARITY, BDD, ZDD >::DdReducer(), tdzdd::NodeTableEntity< AR >::init(), and tdzdd::NodeTableEntity< AR >::NodeTableEntity().
template<int ARITY> MyVector<int> const& tdzdd::NodeTableEntity< ARITY >::lowerLevels (int level) const inline
Returns a collection of the lower levels that are referred by the given level and that are not referred directly by any higher levels.
Parameters
level the level.
Definition at line 321 of file NodeTable.hpp.
Referenced by tdzdd::DdReducer< ARITY, BDD, ZDD >::algorithmR(), tdzdd::DdReducer< ARITY, BDD, ZDD >::reduce_(), and tdzdd::DdReducer< ARITY, BDD, ZDD >::reduceMP_().
template<int ARITY> void tdzdd::NodeTableEntity< ARITY >::makeIndex (bool useMP = false) const inline
Makes index information.
Parameters
useMP use an algorithm for multiple processors.
Definition at line 251 of file NodeTable.hpp.
Referenced by tdzdd::DdReducer< ARITY, BDD, ZDD >::DdReducer(), tdzdd::NodeTableEntity< AR >::higherLevels(), tdzdd::NodeTableEntity< AR >::lowerLevels(), and tdzdd::DdReducer< ARITY, BDD, ZDD >::makeReadyForSequentialReduction().
template<int ARITY> Node<ARITY> const& tdzdd::NodeTableEntity< ARITY >::node (NodeId f) const inline
Gets a node.
Parameters
f node ID.
Returns
node f.
Definition at line 167 of file NodeTable.hpp.
Referenced by tdzdd::NodeTableEntity< AR >::makeIndex().
template<int ARITY> Node<ARITY>& tdzdd::NodeTableEntity< ARITY >::node (NodeId f) inline
Gets a reference to a node.
Parameters
f node ID.
Returns
node f.
Definition at line 176 of file NodeTable.hpp.
template<int ARITY> int tdzdd::NodeTableEntity< ARITY >::numVars () const inline
Gets the number of ZDD variables.
Returns
the number of ZDD variables.
Definition at line 108 of file NodeTable.hpp.
Referenced by tdzdd::NodeTableEntity< AR >::stretchBottom().
template<int ARITY> size_t tdzdd::NodeTableEntity< ARITY >::size () const inline
Gets the variable ID at a given level.
Parameters
level level.
Returns
variable ID. Gets the level of a variable.
Parameters
var variable ID.
Returns
level. Gets the number of nonterminal nodes.
the number of nonterminal nodes.
Definition at line 100 of file NodeTable.hpp.
Referenced by tdzdd::DdReducer< ARITY, BDD, ZDD >::algorithmR(), tdzdd::DdBuilder< S >::construct(), tdzdd::DdBuilderMP< S >::construct(), tdzdd::DdReducer< ARITY, BDD, ZDD >::garbageCollect(), tdzdd::DdReducer< ARITY, BDD, ZDD >::makeReadyForSequentialReduction(), tdzdd::DdReducer< ARITY, BDD, ZDD >::reduce_(), tdzdd::DdReducer< ARITY, BDD, ZDD >::reduceMP_(), tdzdd::ZddSubsetter< S >::subset(), tdzdd::ZddSubsetterMP< S >::subset(), and tdzdd::DdSweeper< AR >::update().
template<int ARITY> void tdzdd::NodeTableEntity< ARITY >::stretchBottom (int n) inline
Changes the number of ZDD variables by shifting up/down the levels of existing variables.
Parameters
n required number of variables.
Definition at line 117 of file NodeTable.hpp.
Member Data Documentation
template<int ARITY> MyVector<MyVector<int> > tdzdd::NodeTableEntity< ARITY >::higherLevelTable mutable private
Definition at line 41 of file NodeTable.hpp.
template<int ARITY> MyVector<MyVector<int> > tdzdd::NodeTableEntity< ARITY >::lowerLevelTable mutable private
Definition at line 42 of file NodeTable.hpp.
The documentation for this class was generated from the following file:
include/tdzdd/dd/NodeTable.hpp