TdZdd: tdzdd::Graph Class Reference
tdzdd::Graph Class Reference
#include <Graph.hpp>
Classes
struct EdgeInfo
struct NoEdgeDecorator
Public Types
typedef int VertexNumber
typedef int EdgeNumber
typedef int ColorNumber
typedef std::pair< VertexNumber, VertexNumber > VertexNumberPair
Public Member Functions
void addEdge (std::string vertexName1, std::string vertexName2)
void setColor (std::string v, std::string color)
void setColor (std::string v, int color)
void readEdges (std::string const &filename)
void readAdjacencyList (std::string const &filename)
void readVertexGroups (std::string const &filename)
void update ()
VertexNumber vertexSize () const
EdgeNumber edgeSize () const
EdgeInfo const & edgeInfo (EdgeNumber a) const
VertexNumber getVertex (std::string const &name) const
std::string vertexName (VertexNumber v) const
std::string vertexLabel (VertexNumber v) const
EdgeNumber getEdge (std::pair< std::string, std::string > const &name) const
EdgeNumber getEdge (std::string const &name1, std::string const &name2) const
std::pair< std::string, std::string > edgeName (EdgeNumber e) const
std::string edgeLabel (EdgeNumber e) const
VertexNumber virtualMate (VertexNumber v) const
EdgeNumber getEdge (VertexNumber v1, VertexNumber v2) const
VertexNumber maxFrontierSize () const
void clearColors ()
void setDefaultPathColor ()
ColorNumber colorNumber (VertexNumber v) const
ColorNumber numColor () const
bool hasColorPairs () const
template<typename E >
std::ostream & dump (std::ostream &os, E const &edgeDecorator) const
std::ostream & dump (std::ostream &os) const
Static Public Attributes
static VertexNumber const MAX_VERTICES = USHRT_MAX
static EdgeNumber const MAX_EDGES = INT_MAX
static ColorNumber const MAX_COLORS = USHRT_MAX
Private Member Functions
void readEdges (std::istream &is)
void readAdjacencyList (std::istream &is)
void readVertexGroups (std::istream &is)
std::string getColor (int n)
Static Private Member Functions
static std::string to_string (int i)
Private Attributes
std::vector< std::pair< std::string, std::string > > edgeNames
std::map< std::string, std::string > name2label
std::map< std::string, std::string > name2color
std::map< std::string, VertexNumber > name2vertex
std::vector< std::string > vertex2name
std::map< std::pair< std::string, std::string >, EdgeNumber > name2edge
std::vector< std::pair< std::string, std::string > > edge2name
std::vector< EdgeInfo > edgeInfo_
std::map< VertexNumberPair, EdgeNumber > edgeIndex
std::vector< VertexNumber > virtualMate_
std::vector< ColorNumber > colorNumber_
VertexNumber vMax
ColorNumber numColor_
bool hasColorPairs_
Friends
std::ostream & operator<< (std::ostream &os, Graph const &g)
Detailed Description
Definition at line 43 of file Graph.hpp.
Member Typedef Documentation
typedef int tdzdd::Graph::ColorNumber
Definition at line 47 of file Graph.hpp.
typedef int tdzdd::Graph::EdgeNumber
Definition at line 46 of file Graph.hpp.
typedef int tdzdd::Graph::VertexNumber
Definition at line 45 of file Graph.hpp.
typedef std::pair<VertexNumber,VertexNumber> tdzdd::Graph::VertexNumberPair
Definition at line 48 of file Graph.hpp.
Member Function Documentation
void tdzdd::Graph::addEdge (std::string vertexName1, std::string vertexName2) inline
Definition at line 101 of file Graph.hpp.
void tdzdd::Graph::clearColors () inline
Definition at line 583 of file Graph.hpp.
ColorNumber tdzdd::Graph::colorNumber (VertexNumber v) const inline
Definition at line 599 of file Graph.hpp.
Referenced by tdzdd::FrontierBasedSearch::FrontierBasedSearch(), tdzdd::SimpathBasedImpl< HamiltonPathZdd, Path, true >::SimpathBasedImpl(), and update().
template<typename E > std::ostream& tdzdd::Graph::dump (std::ostream & os, E const & edgeDecorator) const inline
Definition at line 612 of file Graph.hpp.
References edgeInfo(), edgeSize(), tdzdd::Graph::EdgeInfo::v1, and tdzdd::Graph::EdgeInfo::v2.
Referenced by dump().
std::ostream& tdzdd::Graph::dump (std::ostream & os) const inline
Definition at line 663 of file Graph.hpp.
References dump().
EdgeInfo const& tdzdd::Graph::edgeInfo (EdgeNumber a) const inline
Definition at line 495 of file Graph.hpp.
Referenced by dump(), tdzdd::PathZddByStdMap::getChild(), tdzdd::DegreeConstraint::getChild(), tdzdd::SimpathBasedImpl< HamiltonPathZdd, Path, true >::getChild(), tdzdd::FrontierBasedSearch::getChild(), tdzdd::SimpathBasedImpl< HamiltonPathZdd, Path, true >::getRoot(), tdzdd::FrontierBasedSearch::getRoot(), maxFrontierSize(), and update().
std::string tdzdd::Graph::edgeLabel (EdgeNumber e) const inline
Definition at line 543 of file Graph.hpp.
References edgeName().
std::pair<std::string,std::string> tdzdd::Graph::edgeName (EdgeNumber e) const inline
Definition at line 538 of file Graph.hpp.
References edgeSize().
Referenced by edgeLabel().
EdgeNumber tdzdd::Graph::edgeSize () const inline
Definition at line 490 of file Graph.hpp.
Referenced by dump(), edgeName(), maxFrontierSize(), and update().
std::string tdzdd::Graph::getColor (int n) inline private
Definition at line 262 of file Graph.hpp.
Referenced by readVertexGroups(), and setColor().
EdgeNumber tdzdd::Graph::getEdge (std::pair< std::string, std::string > const & name) const inline
Definition at line 525 of file Graph.hpp.
Referenced by getEdge().
EdgeNumber tdzdd::Graph::getEdge (std::string const & name1, std::string const & name2) const inline
Definition at line 533 of file Graph.hpp.
References getEdge().
EdgeNumber tdzdd::Graph::getEdge (VertexNumber v1, VertexNumber v2) const inline
Definition at line 560 of file Graph.hpp.
References to_string().
VertexNumber tdzdd::Graph::getVertex (std::string const & name) const inline
Definition at line 500 of file Graph.hpp.
Referenced by tdzdd::DegreeConstraint::setConstraint().
bool tdzdd::Graph::hasColorPairs () const inline
Definition at line 607 of file Graph.hpp.
References hasColorPairs_.
VertexNumber tdzdd::Graph::maxFrontierSize () const inline
Definition at line 573 of file Graph.hpp.
References edgeInfo(), edgeSize(), tdzdd::Graph::EdgeInfo::v0, and tdzdd::Graph::EdgeInfo::v2.
ColorNumber tdzdd::Graph::numColor () const inline
Definition at line 603 of file Graph.hpp.
References numColor_.
Referenced by tdzdd::FrontierBasedSearch::FrontierBasedSearch().
void tdzdd::Graph::readAdjacencyList (std::string const & filename) inline
Definition at line 132 of file Graph.hpp.
References tdzdd::MessageHandler_< os >::begin(), tdzdd::MessageHandler_< os >::end(), and update().
void tdzdd::Graph::readAdjacencyList (std::istream & is) inline private
Definition at line 218 of file Graph.hpp.
References to_string(), tdzdd::Graph::EdgeInfo::v1, and tdzdd::Graph::EdgeInfo::v2.
void tdzdd::Graph::readEdges (std::string const & filename) inline
Definition at line 113 of file Graph.hpp.
References tdzdd::MessageHandler_< os >::begin(), tdzdd::MessageHandler_< os >::end(), and update().
void tdzdd::Graph::readEdges (std::istream & is) inline private
Definition at line 171 of file Graph.hpp.
References tdzdd::Graph::EdgeInfo::v1, and tdzdd::Graph::EdgeInfo::v2.
void tdzdd::Graph::readVertexGroups (std::string const & filename) inline
Definition at line 151 of file Graph.hpp.
References tdzdd::MessageHandler_< os >::begin(), tdzdd::MessageHandler_< os >::end(), and update().
void tdzdd::Graph::readVertexGroups (std::istream & is) inline private
Definition at line 239 of file Graph.hpp.
References getColor(), and to_string().
void tdzdd::Graph::setColor (std::string v, std::string color) inline
Definition at line 105 of file Graph.hpp.
void tdzdd::Graph::setColor (std::string v, int color) inline
Definition at line 109 of file Graph.hpp.
References getColor().
void tdzdd::Graph::setDefaultPathColor () inline
Definition at line 592 of file Graph.hpp.
References to_string(), and update().
static std::string tdzdd::Graph::to_string (int i) inline static private
Definition at line 672 of file Graph.hpp.
Referenced by getEdge(), readAdjacencyList(), readVertexGroups(), setDefaultPathColor(), and update().
void tdzdd::Graph::update () inline
Definition at line 282 of file Graph.hpp.
References tdzdd::Graph::EdgeInfo::allColorsSeen, colorNumber(), tdzdd::Graph::EdgeInfo::EdgeInfo(), edgeInfo(), edgeSize(), tdzdd::Graph::EdgeInfo::finalEdge, numColor_, to_string(), tdzdd::Graph::EdgeInfo::v0, tdzdd::Graph::EdgeInfo::v1, tdzdd::Graph::EdgeInfo::v1final, tdzdd::Graph::EdgeInfo::v1final2, tdzdd::Graph::EdgeInfo::v2, tdzdd::Graph::EdgeInfo::v2final, tdzdd::Graph::EdgeInfo::v2final2, and vMax.
Referenced by readAdjacencyList(), readEdges(), readVertexGroups(), and setDefaultPathColor().
std::string tdzdd::Graph::vertexLabel (VertexNumber v) const inline
Definition at line 513 of file Graph.hpp.
References vertexName().
std::string tdzdd::Graph::vertexName (VertexNumber v) const inline
Definition at line 508 of file Graph.hpp.
References vertexSize().
Referenced by vertexLabel().
VertexNumber tdzdd::Graph::vertexSize () const inline
Definition at line 486 of file Graph.hpp.
References vMax.
Referenced by tdzdd::DegreeConstraint::DegreeConstraint(), tdzdd::PathZddByStdMap::getRoot(), tdzdd::DegreeConstraint::setConstraint(), and vertexName().
VertexNumber tdzdd::Graph::virtualMate (VertexNumber v) const inline
Definition at line 556 of file Graph.hpp.
Referenced by tdzdd::PathZddByStdMap::getRoot().
Friends And Related Function Documentation
std::ostream& operator<< (std::ostream & os, Graph const & g) friend
Definition at line 667 of file Graph.hpp.
Member Data Documentation
std::vector<ColorNumber> tdzdd::Graph::colorNumber_ private
Definition at line 95 of file Graph.hpp.
std::vector<std::pair<std::string,std::string> > tdzdd::Graph::edge2name private
Definition at line 91 of file Graph.hpp.
std::map<VertexNumberPair,EdgeNumber> tdzdd::Graph::edgeIndex private
Definition at line 93 of file Graph.hpp.
std::vector<EdgeInfo> tdzdd::Graph::edgeInfo_ private
Definition at line 92 of file Graph.hpp.
std::vector<std::pair<std::string,std::string> > tdzdd::Graph::edgeNames private
Definition at line 85 of file Graph.hpp.
bool tdzdd::Graph::hasColorPairs_ private
Definition at line 98 of file Graph.hpp.
Referenced by hasColorPairs().
ColorNumber const tdzdd::Graph::MAX_COLORS = USHRT_MAX static
Definition at line 82 of file Graph.hpp.
EdgeNumber const tdzdd::Graph::MAX_EDGES = INT_MAX static
Definition at line 81 of file Graph.hpp.
VertexNumber const tdzdd::Graph::MAX_VERTICES = USHRT_MAX static
Definition at line 80 of file Graph.hpp.
std::map<std::string,std::string> tdzdd::Graph::name2color private
Definition at line 87 of file Graph.hpp.
std::map<std::pair<std::string,std::string>,EdgeNumber> tdzdd::Graph::name2edge private
Definition at line 90 of file Graph.hpp.
std::map<std::string,std::string> tdzdd::Graph::name2label private
Definition at line 86 of file Graph.hpp.
std::map<std::string,VertexNumber> tdzdd::Graph::name2vertex private
Definition at line 88 of file Graph.hpp.
ColorNumber tdzdd::Graph::numColor_ private
Definition at line 97 of file Graph.hpp.
Referenced by numColor(), and update().
std::vector<std::string> tdzdd::Graph::vertex2name private
Definition at line 89 of file Graph.hpp.
std::vector<VertexNumber> tdzdd::Graph::virtualMate_ private
Definition at line 94 of file Graph.hpp.
VertexNumber tdzdd::Graph::vMax private
Definition at line 96 of file Graph.hpp.
Referenced by update(), and vertexSize().
The documentation for this class was generated from the following file:
include/tdzdd/util/Graph.hpp