TdZdd: tdzdd::FixedBigNumber< size > Class Template Reference
tdzdd::FixedBigNumber< size > Class Template Reference
#include <BigNumber.hpp>
Public Member Functions
FixedBigNumber ()
FixedBigNumber (uint32_t i)
FixedBigNumber & operator= (uint32_t n)
bool operator== (FixedBigNumber const &o) const
bool operator!= (FixedBigNumber const &o) const
bool operator== (uint32_t n) const
bool operator!= (uint32_t n) const
void operator+= (FixedBigNumber const &o)
FixedBigNumber operator+ (FixedBigNumber const &o) const
uint32_t divide (uint32_t n)
template<typename T >
T translate () const
operator std::string () const
Private Member Functions
void printHelper (std::ostream &os)
Private Attributes
uint32_t val [size]
Friends
std::ostream & operator<< (std::ostream &os, FixedBigNumber const &o)
Detailed Description
template<int size>
class tdzdd::FixedBigNumber< size >
Definition at line 266 of file BigNumber.hpp.
Constructor & Destructor Documentation
template<int size> tdzdd::FixedBigNumber< size >::FixedBigNumber () inline
Definition at line 270 of file BigNumber.hpp.
References tdzdd::BigNumber::size().
template<int size> tdzdd::FixedBigNumber< size >::FixedBigNumber (uint32_t i) inline
Definition at line 276 of file BigNumber.hpp.
References tdzdd::BigNumber::size().
Member Function Documentation
template<int size> uint32_t tdzdd::FixedBigNumber< size >::divide (uint32_t n) inline
Definition at line 331 of file BigNumber.hpp.
References tdzdd::BigNumber::size().
template<int size> tdzdd::FixedBigNumber< size >::operator std::string () const inline
Definition at line 366 of file BigNumber.hpp.
template<int size> bool tdzdd::FixedBigNumber< size >::operator!= (FixedBigNumber< size > const & o) const inline
Definition at line 298 of file BigNumber.hpp.
References tdzdd::BigNumber::operator==().
template<int size> bool tdzdd::FixedBigNumber< size >::operator!= (uint32_t n) const inline
Definition at line 310 of file BigNumber.hpp.
References tdzdd::BigNumber::operator==().
template<int size> FixedBigNumber tdzdd::FixedBigNumber< size >::operator+ (FixedBigNumber< size > const & o) const inline
Definition at line 325 of file BigNumber.hpp.
template<int size> void tdzdd::FixedBigNumber< size >::operator+= (FixedBigNumber< size > const & o) inline
Definition at line 314 of file BigNumber.hpp.
References tdzdd::BigNumber::size(), and tdzdd::FixedBigNumber< size >::val.
template<int size> FixedBigNumber& tdzdd::FixedBigNumber< size >::operator= (uint32_t n) inline
Definition at line 283 of file BigNumber.hpp.
References tdzdd::BigNumber::size().
template<int size> bool tdzdd::FixedBigNumber< size >::operator== (FixedBigNumber< size > const & o) const inline
Definition at line 291 of file BigNumber.hpp.
References tdzdd::BigNumber::size(), and tdzdd::FixedBigNumber< size >::val.
template<int size> bool tdzdd::FixedBigNumber< size >::operator== (uint32_t n) const inline
Definition at line 302 of file BigNumber.hpp.
References tdzdd::BigNumber::size().
template<int size> void tdzdd::FixedBigNumber< size >::printHelper (std::ostream & os) inline private
Definition at line 353 of file BigNumber.hpp.
References tdzdd::BigNumber::divide(), and tdzdd::BigNumber::printHelper().
template<int size> template<typename T > T tdzdd::FixedBigNumber< size >::translate () const inline
Definition at line 343 of file BigNumber.hpp.
References tdzdd::BigNumber::size().
Friends And Related Function Documentation
template<int size> std::ostream& operator<< (std::ostream & os, FixedBigNumber< size > const & o) friend
Definition at line 360 of file BigNumber.hpp.
Member Data Documentation
template<int size> uint32_t tdzdd::FixedBigNumber< size >::val[size] private
Definition at line 267 of file BigNumber.hpp.
Referenced by tdzdd::FixedBigNumber< size >::operator+=(), and tdzdd::FixedBigNumber< size >::operator==().
The documentation for this class was generated from the following file:
include/tdzdd/util/BigNumber.hpp