TdZdd: tdzdd::NodeTableHandler< ARITY > Class Template Reference
tdzdd::NodeTableHandler< ARITY > Class Template Reference
#include <NodeTable.hpp>
Classes
struct Object
Public Member Functions
NodeTableHandler (int n=1)
NodeTableHandler (NodeTableHandler const &o)
NodeTableHandler & operator= (NodeTableHandler const &o)
~NodeTableHandler ()
NodeTableEntity< ARITY > const & operator* () const
NodeTableEntity< ARITY > const * operator-> () const
NodeTableEntity< ARITY > & privateEntity ()
Make the table unshared.
NodeTableEntity< ARITY > & init (int n=1)
Clear and initialize the table.
void derefLevel (int i)
Clear a row if it is not shared.
Private Attributes
Object * pointer
Detailed Description
template<int ARITY>
class tdzdd::NodeTableHandler< ARITY >
Definition at line 402 of file NodeTable.hpp.
Constructor & Destructor Documentation
template<int ARITY> tdzdd::NodeTableHandler< ARITY >::NodeTableHandler (int n = 1) inline
Definition at line 429 of file NodeTable.hpp.
template<int ARITY> tdzdd::NodeTableHandler< ARITY >::NodeTableHandler (NodeTableHandler< ARITY > const & o) inline
Definition at line 433 of file NodeTable.hpp.
References tdzdd::NodeTableHandler< ARITY >::Object::ref().
template<int ARITY> tdzdd::NodeTableHandler< ARITY >::~NodeTableHandler () inline
Definition at line 445 of file NodeTable.hpp.
References tdzdd::NodeTableHandler< ARITY >::Object::deref().
Member Function Documentation
template<int ARITY> void tdzdd::NodeTableHandler< ARITY >::derefLevel (int i) inline
Clear a row if it is not shared.
Parameters
i row index.
Definition at line 489 of file NodeTable.hpp.
References tdzdd::NodeTableHandler< ARITY >::Object::entity, and tdzdd::NodeTableHandler< ARITY >::Object::refCount.
Referenced by tdzdd::DdStructure< ARITY >::zddSubset_(), and tdzdd::DdStructure< ARITY >::zddSubsetMP_().
template<int ARITY> NodeTableEntity<ARITY>& tdzdd::NodeTableHandler< ARITY >::init (int n = 1) inline
Clear and initialize the table.
Parameters
n the number of rows.
Returns
writable reference to the private table.
Definition at line 474 of file NodeTable.hpp.
References tdzdd::NodeTableHandler< ARITY >::Object::deref(), tdzdd::NodeTableHandler< ARITY >::Object::entity, and tdzdd::NodeTableHandler< ARITY >::Object::refCount.
template<int ARITY> NodeTableEntity<ARITY> const& tdzdd::NodeTableHandler< ARITY >::operator* () const inline
Definition at line 449 of file NodeTable.hpp.
References tdzdd::NodeTableHandler< ARITY >::Object::entity.
template<int ARITY> NodeTableEntity<ARITY> const* tdzdd::NodeTableHandler< ARITY >::operator-> () const inline
Definition at line 453 of file NodeTable.hpp.
References tdzdd::NodeTableHandler< ARITY >::Object::entity.
template<int ARITY> NodeTableHandler& tdzdd::NodeTableHandler< ARITY >::operator= (NodeTableHandler< ARITY > const & o) inline
Definition at line 438 of file NodeTable.hpp.
References tdzdd::NodeTableHandler< ARITY >::Object::deref(), tdzdd::NodeTableHandler< ARITY >::pointer, and tdzdd::NodeTableHandler< ARITY >::Object::ref().
template<int ARITY> NodeTableEntity<ARITY>& tdzdd::NodeTableHandler< ARITY >::privateEntity () inline
Make the table unshared.
Returns
writable reference to the private table.
Definition at line 461 of file NodeTable.hpp.
References tdzdd::NodeTableHandler< ARITY >::Object::deref(), tdzdd::NodeTableHandler< ARITY >::Object::entity, and tdzdd::NodeTableHandler< ARITY >::Object::refCount.
Referenced by tdzdd::DdStructure< ARITY >::DdStructure().
Member Data Documentation
template<int ARITY> Object* tdzdd::NodeTableHandler< ARITY >::pointer private
Definition at line 426 of file NodeTable.hpp.
Referenced by tdzdd::NodeTableHandler< ARITY >::operator=().
The documentation for this class was generated from the following file:
include/tdzdd/dd/NodeTable.hpp