TdZdd: tdzdd::DataTable< T > Class Template Reference
tdzdd::DataTable< T > Class Template Reference
#include <DataTable.hpp>
Public Member Functions
DataTable (int n=0)
Constructor.
DataTable (DataTable const &o)
DataTable & operator= (DataTable const &o)
void init (int n=0)
Clears and initializes the table.
void setNumRows (int n)
Resizes the table rows.
void initRow (int i, size_t size)
Clears and initializes a row.
size_t addColumn (int i)
Clears and initializes a row.
int numRows () const
Gets the number of rows.
size_t totalSize () const
Gets the total number of elements in the table.
MyVector< T > & operator[] (int i)
Accesses to a row.
MyVector< T > const & operator[] (int i) const
Accesses to a row.
Private Attributes
MyVector< MyVector< T > > table
Friends
std::ostream & operator<< (std::ostream &os, DataTable const &o)
Detailed Description
template<typename T>
class tdzdd::DataTable< T >
Definition at line 35 of file DataTable.hpp.
Constructor & Destructor Documentation
template<typename T> tdzdd::DataTable< T >::DataTable (int n = 0) inline
Constructor.
Parameters
n the number of rows.
Definition at line 46 of file DataTable.hpp.
template<typename T> tdzdd::DataTable< T >::DataTable (DataTable< T > const & o) inline
Definition at line 50 of file DataTable.hpp.
Member Function Documentation
template<typename T> size_t tdzdd::DataTable< T >::addColumn (int i) inline
Clears and initializes a row.
Parameters
i row index.
size new size of the row.
initVal initial value of elements.
Returns
the new array for the row. Adds one column to a row.
Parameters
i row index.
Returns
the new column index.
Definition at line 139 of file DataTable.hpp.
template<typename T> void tdzdd::DataTable< T >::init (int n = 0) inline
Clears and initializes the table.
Parameters
n the number of rows.
Definition at line 91 of file DataTable.hpp.
template<typename T> void tdzdd::DataTable< T >::initRow (int i, size_t size) inline
Clears and initializes a row.
Parameters
i row index.
size new size of the row.
Definition at line 109 of file DataTable.hpp.
Referenced by tdzdd::DdBuilderMP< S >::construct(), tdzdd::ZddSubsetter< S >::subset(), and tdzdd::ZddSubsetterMP< S >::subset().
template<typename T> int tdzdd::DataTable< T >::numRows () const inline
Gets the number of rows.
Returns
the number of rows.
Definition at line 148 of file DataTable.hpp.
Referenced by tdzdd::DdBuilderMP< S >::construct(), tdzdd::DdBuilder< S >::init(), tdzdd::DdBuilderMP< S >::init(), tdzdd::ZddSubsetter< S >::subset(), and tdzdd::ZddSubsetterMP< S >::subset().
template<typename T> DataTable& tdzdd::DataTable< T >::operator= (DataTable< T > const & o) inline
Definition at line 54 of file DataTable.hpp.
template<typename T> MyVector<T>& tdzdd::DataTable< T >::operator[] (int i) inline
Accesses to a row.
Parameters
i row index.
Returns
vector of elements on the row.
Definition at line 169 of file DataTable.hpp.
template<typename T> MyVector<T> const& tdzdd::DataTable< T >::operator[] (int i) const inline
Accesses to a row.
Parameters
i row index.
Returns
vector of elements on the row.
Definition at line 178 of file DataTable.hpp.
template<typename T> void tdzdd::DataTable< T >::setNumRows (int n) inline
Resizes the table rows.
Parameters
n the number of rows.
Definition at line 100 of file DataTable.hpp.
Referenced by tdzdd::DdBuilder< S >::init(), and tdzdd::DdBuilderMP< S >::init().
template<typename T> size_t tdzdd::DataTable< T >::totalSize () const inline
Gets the total number of elements in the table.
Returns
the total number of elements in the table.
Definition at line 156 of file DataTable.hpp.
Friends And Related Function Documentation
template<typename T> std::ostream& operator<< (std::ostream & os, DataTable< T > const & o) friend
Definition at line 182 of file DataTable.hpp.
Member Data Documentation
template<typename T> MyVector<MyVector<T> > tdzdd::DataTable< T >::table private
Definition at line 36 of file DataTable.hpp.
Referenced by tdzdd::DataTable< tdzdd::MyListOnPool< SpecNode > >::operator=().
The documentation for this class was generated from the following file:
include/tdzdd/dd/DataTable.hpp