TdZdd: tdzdd::MemoryPool Class Reference
tdzdd::MemoryPool Class Reference
Memory pool.
#include <MemoryPool.hpp>
Classes
class Allocator
struct Unit
Public Member Functions
MemoryPool ()
MemoryPool (MemoryPool const &o)
void moveFrom (MemoryPool &o)
virtual ~MemoryPool ()
bool empty () const
void clear ()
void reuse ()
void splice (MemoryPool &o)
void * alloc (size_t n)
template<typename T >
T * allocate (size_t n=1)
template<typename T >
Allocator< T > allocator ()
Private Attributes
Unit * blockList
size_t nextUnit
Static Private Attributes
static size_t const UNIT_SIZE = sizeof(Unit)
static size_t const BLOCK_UNITS = 400000 / UNIT_SIZE
static size_t const MAX_ELEMENT_UNIS = BLOCK_UNITS / 10
Friends
std::ostream & operator<< (std::ostream &os, MemoryPool const &o)
Send an object to an output stream.
Detailed Description
Memory pool.
Allocated memory blocks are kept until the pool is destructed.
Definition at line 39 of file MemoryPool.hpp.
Constructor & Destructor Documentation
tdzdd::MemoryPool::MemoryPool () inline
Definition at line 52 of file MemoryPool.hpp.
tdzdd::MemoryPool::MemoryPool (MemoryPool const & o) inline
Definition at line 56 of file MemoryPool.hpp.
virtual tdzdd::MemoryPool::~MemoryPool () inline virtual
Definition at line 86 of file MemoryPool.hpp.
References clear().
Member Function Documentation
void* tdzdd::MemoryPool::alloc (size_t n) inline
Definition at line 129 of file MemoryPool.hpp.
References BLOCK_UNITS, blockList, tdzdd::MemoryPool::Unit::next, and nextUnit.
Referenced by allocate().
template<typename T > T* tdzdd::MemoryPool::allocate (size_t n = 1) inline
Definition at line 160 of file MemoryPool.hpp.
References alloc().
Referenced by tdzdd::MemoryPool::Allocator< T >::allocate().
template<typename T > Allocator<T> tdzdd::MemoryPool::allocator () inline
Definition at line 208 of file MemoryPool.hpp.
void tdzdd::MemoryPool::clear () inline
Definition at line 94 of file MemoryPool.hpp.
References BLOCK_UNITS, blockList, and tdzdd::MemoryPool::Unit::next.
Referenced by ~MemoryPool().
bool tdzdd::MemoryPool::empty () const inline
Definition at line 90 of file MemoryPool.hpp.
void tdzdd::MemoryPool::moveFrom (MemoryPool & o) inline
Definition at line 80 of file MemoryPool.hpp.
References blockList, and nextUnit.
Referenced by tdzdd::MyVector< T, Size >::moveElement().
void tdzdd::MemoryPool::reuse () inline
Definition at line 103 of file MemoryPool.hpp.
References blockList, and tdzdd::MemoryPool::Unit::next.
void tdzdd::MemoryPool::splice (MemoryPool & o) inline
Definition at line 113 of file MemoryPool.hpp.
References BLOCK_UNITS, blockList, tdzdd::MemoryPool::Unit::next, and nextUnit.
Friends And Related Function Documentation
std::ostream& operator<< (std::ostream & os, MemoryPool const & o) friend
Send an object to an output stream.
Parameters
os the output stream.
o the object.
Returns
os.
Definition at line 218 of file MemoryPool.hpp.
Member Data Documentation
size_t const tdzdd::MemoryPool::BLOCK_UNITS = 400000 / UNIT_SIZE static private
Definition at line 45 of file MemoryPool.hpp.
Referenced by alloc(), clear(), and splice().
Unit* tdzdd::MemoryPool::blockList private
Definition at line 48 of file MemoryPool.hpp.
Referenced by alloc(), clear(), moveFrom(), reuse(), and splice().
size_t const tdzdd::MemoryPool::MAX_ELEMENT_UNIS = BLOCK_UNITS / 10 static private
Definition at line 46 of file MemoryPool.hpp.
size_t tdzdd::MemoryPool::nextUnit private
Definition at line 49 of file MemoryPool.hpp.
Referenced by alloc(), moveFrom(), and splice().
size_t const tdzdd::MemoryPool::UNIT_SIZE = sizeof(Unit) static private
Definition at line 44 of file MemoryPool.hpp.
The documentation for this class was generated from the following file:
include/tdzdd/util/MemoryPool.hpp