TdZdd: tdzdd::DdReducer< ARITY, BDD, ZDD > Class Template Reference
tdzdd::DdReducer< ARITY, BDD, ZDD > Class Template Reference
#include <DdReducer.hpp>
Classes
struct ReducNodeInfo
Public Member Functions
DdReducer (NodeTableHandler< ARITY > &diagram, bool useMP=false)
void setRoot (NodeId &root)
Sets a root node.
void reduce (int i, bool useMP=false)
Reduces one level.
void garbageCollect ()
Private Member Functions
void makeReadyForSequentialReduction ()
Applies the node deletion rules.
void algorithmR (int i)
Reduces one level using Algorithm-R.
void reduce_ (int i)
Reduces one level.
void reduceMP_ (int i)
Reduces one level using OpenMP.
Private Attributes
NodeTableEntity< ARITY > & input
NodeTableHandler< ARITY > oldDiagram
NodeTableHandler< ARITY > newDiagram
NodeTableEntity< ARITY > & output
MyVector< MyVector< NodeId > > newIdTable
MyVector< MyVector< NodeId * > > rootPtr
bool readyForSequentialReduction
Detailed Description
template<int ARITY, bool BDD, bool ZDD>
class tdzdd::DdReducer< ARITY, BDD, ZDD >
Definition at line 45 of file DdReducer.hpp.
Constructor & Destructor Documentation
template<int ARITY, bool BDD, bool ZDD> tdzdd::DdReducer< ARITY, BDD, ZDD >::DdReducer (NodeTableHandler< ARITY > & diagram, bool useMP = false) inline
Definition at line 87 of file DdReducer.hpp.
References tdzdd::NodeTableEntity< ARITY >::initTerminals(), tdzdd::NodeTableEntity< ARITY >::makeIndex(), tdzdd::DdReducer< ARITY, BDD, ZDD >::newDiagram, tdzdd::MyVector< T, Size >::resize(), tdzdd::ElapsedTimeCounter::start(), and tdzdd::ElapsedTimeCounter::stop().
Member Function Documentation
template<int ARITY, bool BDD, bool ZDD> void tdzdd::DdReducer< ARITY, BDD, ZDD >::algorithmR (int i) inline private
Reduces one level using Algorithm-R.
Parameters
i level.
Definition at line 225 of file DdReducer.hpp.
References tdzdd::MyVector< T, Size >::begin(), tdzdd::Node< ARITY >::branch, tdzdd::NodeTableEntity< ARITY >::child(), tdzdd::MyVector< T, Size >::clear(), tdzdd::NodeId::col(), tdzdd::MyVector< T, Size >::end(), tdzdd::NodeId::hasEmpty(), tdzdd::DataTable< Node< ARITY > >::initRow(), tdzdd::NodeTableEntity< ARITY >::lowerLevels(), tdzdd::DdReducer< ARITY, BDD, ZDD >::makeReadyForSequentialReduction(), tdzdd::MyVector< T, Size >::resize(), tdzdd::NodeId::row(), tdzdd::NodeTableEntity< ARITY >::size(), and tdzdd::MyVector< T, Size >::size().
Referenced by tdzdd::DdReducer< ARITY, BDD, ZDD >::reduce().
template<int ARITY, bool BDD, bool ZDD> void tdzdd::DdReducer< ARITY, BDD, ZDD >::garbageCollect () inline
Definition at line 564 of file DdReducer.hpp.
References tdzdd::MyVector< T, Size >::begin(), tdzdd::NodeTableEntity< ARITY >::child(), tdzdd::MyVector< T, Size >::end(), tdzdd::NodeId::getAttr(), tdzdd::DataTable< Node< ARITY > >::numRows(), tdzdd::MyVector< T, Size >::push_back(), tdzdd::MyVector< T, Size >::reserve(), tdzdd::MyVector< T, Size >::resize(), tdzdd::NodeTableEntity< ARITY >::size(), and tdzdd::MyVector< T, Size >::size().
template<int ARITY, bool BDD, bool ZDD> void tdzdd::DdReducer< ARITY, BDD, ZDD >::makeReadyForSequentialReduction () inline private
Applies the node deletion rules.
It is required before serial reduction (Algorithm-R) in order to make lower-level index safe.
Definition at line 153 of file DdReducer.hpp.
References tdzdd::Node< ARITY >::branch, tdzdd::NodeTableEntity< ARITY >::child(), tdzdd::NodeTableEntity< ARITY >::makeIndex(), tdzdd::DataTable< Node< ARITY > >::numRows(), tdzdd::NodeId::row(), and tdzdd::NodeTableEntity< ARITY >::size().
Referenced by tdzdd::DdReducer< ARITY, BDD, ZDD >::algorithmR().
template<int ARITY, bool BDD, bool ZDD> void tdzdd::DdReducer< ARITY, BDD, ZDD >::reduce (int i, bool useMP = false) inline
Reduces one level.
Parameters
i level.
useMP use an algorithm for multiple processors.
Definition at line 208 of file DdReducer.hpp.
References tdzdd::DdReducer< ARITY, BDD, ZDD >::algorithmR(), tdzdd::DdReducer< ARITY, BDD, ZDD >::reduce_(), and tdzdd::DdReducer< ARITY, BDD, ZDD >::reduceMP_().
Referenced by tdzdd::DdStructure< ARITY >::reduce().
template<int ARITY, bool BDD, bool ZDD> void tdzdd::DdReducer< ARITY, BDD, ZDD >::reduce_ (int i) inline private
Reduces one level.
Parameters
i level.
Definition at line 338 of file DdReducer.hpp.
References tdzdd::MyHashTable< T, Hash, Equal >::add(), tdzdd::MyVector< T, Size >::begin(), tdzdd::Node< ARITY >::branch, tdzdd::MyVector< T, Size >::clear(), tdzdd::NodeId::col(), tdzdd::MyVector< T, Size >::end(), tdzdd::NodeId::hasEmpty(), tdzdd::DataTable< Node< ARITY > >::initRow(), tdzdd::NodeTableEntity< ARITY >::lowerLevels(), tdzdd::MyVector< T, Size >::resize(), tdzdd::NodeId::row(), tdzdd::NodeTableEntity< ARITY >::size(), and tdzdd::MyVector< T, Size >::size().
Referenced by tdzdd::DdReducer< ARITY, BDD, ZDD >::reduce(), and tdzdd::DdReducer< ARITY, BDD, ZDD >::reduceMP_().
template<int ARITY, bool BDD, bool ZDD> void tdzdd::DdReducer< ARITY, BDD, ZDD >::reduceMP_ (int i) inline private
Reduces one level using OpenMP.
Parameters
i level.
Definition at line 405 of file DdReducer.hpp.
References tdzdd::MyHashTable< T, Hash, Equal >::add(), tdzdd::MyList< T, BLOCK_ELEMENTS >::begin(), tdzdd::MyVector< T, Size >::begin(), tdzdd::Node< ARITY >::branch, tdzdd::DdReducer< ARITY, BDD, ZDD >::ReducNodeInfo::children, tdzdd::MyVector< T, Size >::clear(), tdzdd::NodeId::col(), tdzdd::DdReducer< ARITY, BDD, ZDD >::ReducNodeInfo::column, tdzdd::MyList< T, BLOCK_ELEMENTS >::end(), tdzdd::MyVector< T, Size >::end(), tdzdd::NodeId::getAttr(), tdzdd::Node< ARITY >::hash(), tdzdd::MyHashTable< T, Hash, Equal >::initialize(), tdzdd::DataTable< Node< ARITY > >::initRow(), tdzdd::NodeTableEntity< ARITY >::lowerLevels(), tdzdd::DdReducer< ARITY, BDD, ZDD >::reduce_(), tdzdd::MyVector< T, Size >::resize(), tdzdd::NodeId::row(), tdzdd::NodeTableEntity< ARITY >::size(), tdzdd::MyVector< T, Size >::size(), tdzdd::ElapsedTimeCounter::start(), and tdzdd::ElapsedTimeCounter::stop().
Referenced by tdzdd::DdReducer< ARITY, BDD, ZDD >::reduce().
template<int ARITY, bool BDD, bool ZDD> void tdzdd::DdReducer< ARITY, BDD, ZDD >::setRoot (NodeId & root) inline
Sets a root node.
Parameters
root reference to a root node ID storage.
Definition at line 199 of file DdReducer.hpp.
References tdzdd::MyVector< T, Size >::push_back(), and tdzdd::NodeId::row().
Referenced by tdzdd::DdStructure< ARITY >::reduce().
Member Data Documentation
template<int ARITY, bool BDD, bool ZDD> NodeTableEntity<ARITY>& tdzdd::DdReducer< ARITY, BDD, ZDD >::input private
Definition at line 46 of file DdReducer.hpp.
template<int ARITY, bool BDD, bool ZDD> NodeTableHandler<ARITY> tdzdd::DdReducer< ARITY, BDD, ZDD >::newDiagram private
Definition at line 48 of file DdReducer.hpp.
Referenced by tdzdd::DdReducer< ARITY, BDD, ZDD >::DdReducer().
template<int ARITY, bool BDD, bool ZDD> MyVector<MyVector<NodeId> > tdzdd::DdReducer< ARITY, BDD, ZDD >::newIdTable private
Definition at line 50 of file DdReducer.hpp.
template<int ARITY, bool BDD, bool ZDD> NodeTableHandler<ARITY> tdzdd::DdReducer< ARITY, BDD, ZDD >::oldDiagram private
Definition at line 47 of file DdReducer.hpp.
template<int ARITY, bool BDD, bool ZDD> NodeTableEntity<ARITY>& tdzdd::DdReducer< ARITY, BDD, ZDD >::output private
Definition at line 49 of file DdReducer.hpp.
template<int ARITY, bool BDD, bool ZDD> bool tdzdd::DdReducer< ARITY, BDD, ZDD >::readyForSequentialReduction private
Definition at line 84 of file DdReducer.hpp.
template<int ARITY, bool BDD, bool ZDD> MyVector<MyVector<NodeId*> > tdzdd::DdReducer< ARITY, BDD, ZDD >::rootPtr private
Definition at line 51 of file DdReducer.hpp.
The documentation for this class was generated from the following file:
include/tdzdd/dd/DdReducer.hpp