TdZdd: tdzdd::DdBuilder< S > Class Template Reference
tdzdd::DdBuilder< S > Class Template Reference
Basic breadth-first DD builder.
#include <DdBuilder.hpp>
Public Member Functions
DdBuilder (Spec const &spec, NodeTableHandler< AR > &output, int n=0)
~DdBuilder ()
void schedule (NodeId *fp, int level, void *s)
Schedules a top-down event.
int initialize (NodeId &root)
Initializes the builder.
void construct (int i)
Builds one level.
Private Types
typedef S Spec
typedef MyHashTable< SpecNode *, Hasher< Spec >, Hasher< Spec > > UniqTable
Private Member Functions
void init (int n)
Private Attributes
Spec spec
int const specNodeSize
NodeTableEntity< AR > & output
DdSweeper< AR > sweeper
MyVector< MyList< SpecNode > > snodeTable
MyVector< char > oneStorage
void *const one
MyVector< NodeBranchId > oneSrcPtr
Static Private Attributes
static int const AR = Spec::ARITY
Static Private Attributes inherited from tdzdd::DdBuilderBase
static int const headerSize = 1
Additional Inherited Members
Static Private Member Functions inherited from tdzdd::DdBuilderBase
static NodeId *& srcPtr (SpecNode *p)
static int64_t & code (SpecNode *p)
static NodeId & nodeId (SpecNode *p)
static void * state (SpecNode *p)
static void const * state (SpecNode const *p)
static int getSpecNodeSize (int n)
Detailed Description
template<typename S>
class tdzdd::DdBuilder< S >
Basic breadth-first DD builder.
Definition at line 175 of file DdBuilder.hpp.
Member Typedef Documentation
template<typename S> typedef S tdzdd::DdBuilder< S >::Spec private
Definition at line 176 of file DdBuilder.hpp.
template<typename S> typedef MyHashTable<SpecNode*,Hasher<Spec>,Hasher<Spec> > tdzdd::DdBuilder< S >::UniqTable private
Definition at line 177 of file DdBuilder.hpp.
Constructor & Destructor Documentation
template<typename S> tdzdd::DdBuilder< S >::DdBuilder (Spec const & spec, NodeTableHandler< AR > & output, int n = 0) inline
Definition at line 198 of file DdBuilder.hpp.
template<typename S> tdzdd::DdBuilder< S >::~DdBuilder () inline
Definition at line 208 of file DdBuilder.hpp.
References tdzdd::MyVector< T, Size >::clear(), and tdzdd::MyVector< T, Size >::empty().
Member Function Documentation
template<typename S> void tdzdd::DdBuilder< S >::construct (int i) inline
Builds one level.
Parameters
i level.
Definition at line 258 of file DdBuilder.hpp.
References tdzdd::MyVector< T, Size >::back(), tdzdd::MyList< T, BLOCK_ELEMENTS >::begin(), tdzdd::Node< ARITY >::branch, tdzdd::NodeBranchId::col, tdzdd::MyVector< T, Size >::empty(), tdzdd::DdBuilderBase::nodeId(), tdzdd::MyVector< T, Size >::pop_back(), tdzdd::MyVector< T, Size >::push_back(), tdzdd::NodeBranchId::row, tdzdd::NodeTableEntity< ARITY >::size(), tdzdd::MyVector< T, Size >::size(), tdzdd::DdBuilderBase::SpecNode::srcPtr, tdzdd::DdBuilderBase::state(), tdzdd::DdSweeper< ARITY >::update(), and tdzdd::NodeBranchId::val.
Referenced by tdzdd::DdStructure< ARITY >::construct_().
template<typename S> void tdzdd::DdBuilder< S >::init (int n) inline private
Definition at line 191 of file DdBuilder.hpp.
References tdzdd::MyVector< T, Size >::clear(), tdzdd::DataTable< T >::numRows(), tdzdd::MyVector< T, Size >::resize(), and tdzdd::DataTable< T >::setNumRows().
template<typename S> int tdzdd::DdBuilder< S >::initialize (NodeId & root) inline
Initializes the builder.
Parameters
root result storage.
Definition at line 231 of file DdBuilder.hpp.
References tdzdd::MyVector< T, Size >::clear(), tdzdd::MyVector< T, Size >::data(), tdzdd::MyVector< T, Size >::empty(), and tdzdd::DdSweeper< ARITY >::setRoot().
Referenced by tdzdd::DdStructure< ARITY >::construct_().
template<typename S> void tdzdd::DdBuilder< S >::schedule (NodeId * fp, int level, void * s) inline
Schedules a top-down event.
Parameters
fp result storage.
level node level of the event.
s node state of the event.
Definition at line 221 of file DdBuilder.hpp.
References tdzdd::DdBuilderBase::SpecNode::srcPtr, and tdzdd::DdBuilderBase::state().
Member Data Documentation
template<typename S> int const tdzdd::DdBuilder< S >::AR = Spec::ARITY static private
Definition at line 178 of file DdBuilder.hpp.
template<typename S> void* const tdzdd::DdBuilder< S >::one private
Definition at line 188 of file DdBuilder.hpp.
template<typename S> MyVector<NodeBranchId> tdzdd::DdBuilder< S >::oneSrcPtr private
Definition at line 189 of file DdBuilder.hpp.
template<typename S> MyVector<char> tdzdd::DdBuilder< S >::oneStorage private
Definition at line 187 of file DdBuilder.hpp.
template<typename S> NodeTableEntity<AR>& tdzdd::DdBuilder< S >::output private
Definition at line 182 of file DdBuilder.hpp.
template<typename S> MyVector<MyList<SpecNode> > tdzdd::DdBuilder< S >::snodeTable private
Definition at line 185 of file DdBuilder.hpp.
template<typename S> Spec tdzdd::DdBuilder< S >::spec private
Definition at line 180 of file DdBuilder.hpp.
template<typename S> int const tdzdd::DdBuilder< S >::specNodeSize private
Definition at line 181 of file DdBuilder.hpp.
template<typename S> DdSweeper<AR> tdzdd::DdBuilder< S >::sweeper private
Definition at line 183 of file DdBuilder.hpp.
The documentation for this class was generated from the following file:
include/tdzdd/dd/DdBuilder.hpp