TdZdd: tdzdd::BigNumber Class Reference
tdzdd::BigNumber Class Reference
#include <BigNumber.hpp>
Public Member Functions
BigNumber ()
BigNumber (uint64_t *array)
void setArray (uint64_t *array)
int size () const
size_t store (BigNumber const &o)
size_t store (uint64_t n)
bool operator== (BigNumber const &o) const
bool operator!= (BigNumber const &o) const
bool operator== (uint64_t n) const
bool operator!= (uint64_t const &o) const
size_t add (BigNumber const &o)
uint32_t divide (uint32_t n)
size_t shiftLeft (int k)
template<typename T >
T translate () const
operator std::string () const
Protected Attributes
uint64_t * array
Static Protected Attributes
static uint64_t const MSB = uint64_t(1) << 63
Private Member Functions
void printHelper (std::ostream &os)
Friends
std::ostream & operator<< (std::ostream &os, BigNumber const &o)
Detailed Description
Definition at line 37 of file BigNumber.hpp.
Constructor & Destructor Documentation
tdzdd::BigNumber::BigNumber () inline
Definition at line 44 of file BigNumber.hpp.
tdzdd::BigNumber::BigNumber (uint64_t * array) inline explicit
Definition at line 48 of file BigNumber.hpp.
Member Function Documentation
size_t tdzdd::BigNumber::add (BigNumber const & o) inline
Definition at line 126 of file BigNumber.hpp.
References array, and MSB.
Referenced by tdzdd::PathCounter< S >::count(), tdzdd::PathCounter< S >::countFast(), tdzdd::CardinalityBase< E, std::string, ARITY, BDD >::evalNode(), and tdzdd::CardinalityBase< E, std::string, ARITY, BDD >::getValue().
uint32_t tdzdd::BigNumber::divide (uint32_t n) inline
Definition at line 167 of file BigNumber.hpp.
References array.
Referenced by printHelper(), and tdzdd::FixedBigNumber< size >::printHelper().
tdzdd::BigNumber::operator std::string () const inline
Definition at line 258 of file BigNumber.hpp.
bool tdzdd::BigNumber::operator!= (BigNumber const & o) const inline
Definition at line 113 of file BigNumber.hpp.
References operator==().
bool tdzdd::BigNumber::operator!= (uint64_t const & o) const inline
Definition at line 122 of file BigNumber.hpp.
References operator==().
bool tdzdd::BigNumber::operator== (BigNumber const & o) const inline
Definition at line 101 of file BigNumber.hpp.
References array.
Referenced by operator!=(), and tdzdd::FixedBigNumber< size >::operator!=().
bool tdzdd::BigNumber::operator== (uint64_t n) const inline
Definition at line 117 of file BigNumber.hpp.
References MSB.
void tdzdd::BigNumber::printHelper (std::ostream & os) inline private
Definition at line 242 of file BigNumber.hpp.
References divide().
Referenced by tdzdd::FixedBigNumber< size >::printHelper().
void tdzdd::BigNumber::setArray (uint64_t * array) inline
Definition at line 52 of file BigNumber.hpp.
References array.
Referenced by tdzdd::CardinalityBase< E, std::string, ARITY, BDD >::evalNode(), tdzdd::CardinalityBase< E, std::string, ARITY, BDD >::evalTerminal(), and tdzdd::CardinalityBase< E, std::string, ARITY, BDD >::initialize().
size_t tdzdd::BigNumber::shiftLeft (int k) inline
Definition at line 193 of file BigNumber.hpp.
References array, MSB, and size().
Referenced by tdzdd::CardinalityBase< E, std::string, ARITY, BDD >::evalNode(), and tdzdd::CardinalityBase< E, std::string, ARITY, BDD >::getValue().
int tdzdd::BigNumber::size () const inline
Definition at line 56 of file BigNumber.hpp.
References array.
Referenced by tdzdd::FixedBigNumber< size >::divide(), tdzdd::FixedBigNumber< size >::FixedBigNumber(), tdzdd::FixedBigNumber< size >::operator+=(), tdzdd::FixedBigNumber< size >::operator=(), tdzdd::FixedBigNumber< size >::operator==(), shiftLeft(), and tdzdd::FixedBigNumber< size >::translate().
size_t tdzdd::BigNumber::store (BigNumber const & o) inline
Definition at line 64 of file BigNumber.hpp.
References array.
Referenced by tdzdd::PathCounter< S >::count(), tdzdd::PathCounter< S >::countFast(), tdzdd::CardinalityBase< E, std::string, ARITY, BDD >::evalNode(), tdzdd::CardinalityBase< E, std::string, ARITY, BDD >::evalTerminal(), and tdzdd::CardinalityBase< E, std::string, ARITY, BDD >::getValue().
size_t tdzdd::BigNumber::store (uint64_t n) inline
Definition at line 83 of file BigNumber.hpp.
template<typename T > T tdzdd::BigNumber::translate () const inline
Definition at line 228 of file BigNumber.hpp.
References array.
Friends And Related Function Documentation
std::ostream& operator<< (std::ostream & os, BigNumber const & o) friend
Definition at line 249 of file BigNumber.hpp.
Member Data Documentation
uint64_t* tdzdd::BigNumber::array protected
Definition at line 41 of file BigNumber.hpp.
Referenced by add(), divide(), operator==(), setArray(), shiftLeft(), size(), store(), and translate().
uint64_t const tdzdd::BigNumber::MSB = uint64_t(1) << 63 static protected
Definition at line 39 of file BigNumber.hpp.
Referenced by add(), operator==(), and shiftLeft().
The documentation for this class was generated from the following file:
include/tdzdd/util/BigNumber.hpp