TdZdd: tdzdd::DdStructure< ARITY >::const_iterator Class Reference
tdzdd::DdStructure< ARITY >::const_iterator Class Reference
Iterator on a set of integer vectors represented by a DD.
#include <DdStructure.hpp>
Classes
struct Selection
Public Member Functions
const_iterator (DdStructure const &dd, bool begin)
const_iterator & operator++ ()
std::set< int > const & operator* () const
std::set< int > const * operator-> () const
bool operator== (const_iterator const &o) const
bool operator!= (const_iterator const &o) const
Private Member Functions
void next (NodeId f)
Private Attributes
DdStructure const & dd
int cursor
std::vector< Selection > path
std::set< int > itemset
Detailed Description
template<int ARITY>
class tdzdd::DdStructure< ARITY >::const_iterator
Iterator on a set of integer vectors represented by a DD.
Definition at line 554 of file DdStructure.hpp.
Constructor & Destructor Documentation
template<int ARITY> tdzdd::DdStructure< ARITY >::const_iterator::const_iterator (DdStructure const & dd, bool begin) inline
Definition at line 578 of file DdStructure.hpp.
References tdzdd::DdStructure< ARITY >::const_iterator::next(), and tdzdd::DdStructure< ARITY >::root_.
Referenced by tdzdd::DdStructure< ARITY >::begin(), and tdzdd::DdStructure< ARITY >::end().
Member Function Documentation
template<int ARITY> void tdzdd::DdStructure< ARITY >::const_iterator::next (NodeId f) inline private
Definition at line 605 of file DdStructure.hpp.
References tdzdd::Node< ARITY >::branch, tdzdd::NodeId::col(), tdzdd::DdStructure< ARITY >::const_iterator::cursor, tdzdd::DdStructure< ARITY >::diagram, tdzdd::DdStructure< ARITY >::const_iterator::Selection::node, tdzdd::NodeId::row(), tdzdd::DdStructure< ARITY >::const_iterator::Selection::Selection(), and tdzdd::DdStructure< ARITY >::const_iterator::Selection::val.
Referenced by tdzdd::DdStructure< ARITY >::const_iterator::const_iterator(), and tdzdd::DdStructure< ARITY >::const_iterator::operator++().
template<int ARITY> bool tdzdd::DdStructure< ARITY >::const_iterator::operator!= (const_iterator const & o) const inline
Definition at line 600 of file DdStructure.hpp.
References tdzdd::DdStructure< ARITY >::const_iterator::Selection::operator==().
template<int ARITY> std::set<int> const& tdzdd::DdStructure< ARITY >::const_iterator::operator* () const inline
Definition at line 588 of file DdStructure.hpp.
References tdzdd::DdStructure< ARITY >::const_iterator::itemset.
template<int ARITY> const_iterator& tdzdd::DdStructure< ARITY >::const_iterator::operator++ () inline
Definition at line 583 of file DdStructure.hpp.
References tdzdd::DdStructure< ARITY >::const_iterator::next().
template<int ARITY> std::set<int> const* tdzdd::DdStructure< ARITY >::const_iterator::operator-> () const inline
Definition at line 592 of file DdStructure.hpp.
References tdzdd::DdStructure< ARITY >::const_iterator::itemset.
template<int ARITY> bool tdzdd::DdStructure< ARITY >::const_iterator::operator== (const_iterator const & o) const inline
Definition at line 596 of file DdStructure.hpp.
References tdzdd::DdStructure< ARITY >::const_iterator::cursor, and tdzdd::DdStructure< ARITY >::const_iterator::path.
Member Data Documentation
template<int ARITY> int tdzdd::DdStructure< ARITY >::const_iterator::cursor private
Definition at line 573 of file DdStructure.hpp.
Referenced by tdzdd::DdStructure< ARITY >::const_iterator::next(), and tdzdd::DdStructure< ARITY >::const_iterator::operator==().
template<int ARITY> DdStructure const& tdzdd::DdStructure< ARITY >::const_iterator::dd private
Definition at line 572 of file DdStructure.hpp.
template<int ARITY> std::set<int> tdzdd::DdStructure< ARITY >::const_iterator::itemset private
Definition at line 575 of file DdStructure.hpp.
Referenced by tdzdd::DdStructure< ARITY >::const_iterator::operator*(), and tdzdd::DdStructure< ARITY >::const_iterator::operator->().
template<int ARITY> std::vector<Selection> tdzdd::DdStructure< ARITY >::const_iterator::path private
Definition at line 574 of file DdStructure.hpp.
Referenced by tdzdd::DdStructure< ARITY >::const_iterator::operator==().
The documentation for this class was generated from the following file:
include/tdzdd/DdStructure.hpp