TdZdd: tdzdd::GraphillionZdd Class Reference
tdzdd::GraphillionZdd Class Reference
#include <GraphillionZdd.hpp>
Classes
struct Node
Public Member Functions
GraphillionZdd ()
void read (std::string const &filename="")
void addNode (uint64_t id, Node const &node)
int getRoot (uint64_t &f) const
int getChild (uint64_t &f, int level, int take) const
Public Member Functions inherited from tdzdd::DdSpec< GraphillionZdd, uint64_t, 2 >
int datasize () const
void construct (void *p)
int get_root (void *p)
int get_child (void *p, int level, int value)
void getCopy (void *p, State const &s)
void get_copy (void *to, void const *from)
int mergeStates (State &s1, State &s2)
int merge_states (void *p1, void *p2)
void destruct (void *p)
void destructLevel (int level)
size_t hashCode (State const &s) const
size_t hashCodeAtLevel (State const &s, int level) const
size_t hash_code (void const *p, int level) const
bool equalTo (State const &s1, State const &s2) const
bool equalToAtLevel (State const &s1, State const &s2, int level) const
bool equal_to (void const *p, void const *q, int level) const
void printState (std::ostream &os, State const &s) const
void printStateAtLevel (std::ostream &os, State const &s, int level) const
void print_state (std::ostream &os, void const *p, int level) const
Public Member Functions inherited from tdzdd::DdSpecBase< GraphillionZdd, AR >
GraphillionZdd & entity ()
GraphillionZddconst & entity () const
void printLevel (std::ostream &os, int level) const
std::vector< std::pair< int, int > > findOneInstance () const
Returns a random instance using simple depth-first search without caching.
void dumpDot (std::ostream &os=std::cout, std::string title=typenameof< GraphillionZdd >()) const
Dumps the node table in Graphviz (dot) format.
Private Member Functions
void read (std::istream &is)
Static Private Member Functions
static uint64_t readID (std::istream &is)
static int skipSpace (std::istream &is)
static void skipLine (std::istream &is)
Private Attributes
std::vector< Node > table
uint64_t root
int minIndex
int maxIndex
Additional Inherited Members
Public Types inherited from tdzdd::DdSpec< GraphillionZdd, uint64_t, 2 >
typedef uint64_t State
Static Public Attributes inherited from tdzdd::DdSpecBase< GraphillionZdd, AR >
static int const ARITY
Static Protected Member Functions inherited from tdzdd::DdSpecBase< GraphillionZdd, AR >
static size_t rawHashCode (T const &o)
static size_t rawEqualTo (T const &o1, T const &o2)
Detailed Description
Definition at line 39 of file GraphillionZdd.hpp.
Constructor & Destructor Documentation
tdzdd::GraphillionZdd::GraphillionZdd () inline
Definition at line 51 of file GraphillionZdd.hpp.
Member Function Documentation
void tdzdd::GraphillionZdd::addNode (uint64_t id, Node const & node) inline
Definition at line 73 of file GraphillionZdd.hpp.
References tdzdd::GraphillionZdd::Node::child, and tdzdd::GraphillionZdd::Node::index.
Referenced by read().
int tdzdd::GraphillionZdd::getChild (uint64_t & f, int level, int take) const inline
Definition at line 141 of file GraphillionZdd.hpp.
int tdzdd::GraphillionZdd::getRoot (uint64_t & f) const inline
Definition at line 134 of file GraphillionZdd.hpp.
References root.
void tdzdd::GraphillionZdd::read (std::string const & filename = "") inline
Definition at line 55 of file GraphillionZdd.hpp.
References tdzdd::MessageHandler_< os >::begin(), and tdzdd::MessageHandler_< os >::end().
void tdzdd::GraphillionZdd::read (std::istream & is) inline private
Definition at line 87 of file GraphillionZdd.hpp.
References addNode(), tdzdd::GraphillionZdd::Node::child, tdzdd::GraphillionZdd::Node::index, readID(), skipLine(), and skipSpace().
static uint64_t tdzdd::GraphillionZdd::readID (std::istream & is) inline static private
Definition at line 104 of file GraphillionZdd.hpp.
Referenced by read().
static void tdzdd::GraphillionZdd::skipLine (std::istream & is) inline static private
Definition at line 128 of file GraphillionZdd.hpp.
Referenced by read().
static int tdzdd::GraphillionZdd::skipSpace (std::istream & is) inline static private
Definition at line 120 of file GraphillionZdd.hpp.
Referenced by read().
Member Data Documentation
int tdzdd::GraphillionZdd::maxIndex private
Definition at line 48 of file GraphillionZdd.hpp.
int tdzdd::GraphillionZdd::minIndex private
Definition at line 47 of file GraphillionZdd.hpp.
uint64_t tdzdd::GraphillionZdd::root private
Definition at line 46 of file GraphillionZdd.hpp.
Referenced by getRoot().
std::vector<Node> tdzdd::GraphillionZdd::table private
Definition at line 45 of file GraphillionZdd.hpp.
The documentation for this class was generated from the following file:
include/tdzdd/spec/GraphillionZdd.hpp