TdZdd: tdzdd::PodHybridDdSpec< S, TS, TA, AR > Class Template Reference
tdzdd::PodHybridDdSpec< S, TS, TA, AR > Class Template Reference
Abstract class of DD specifications using both POD scalar and POD array states.
#include <DdSpec.hpp>
Public Types
typedef TS S_State
typedef TA A_State
Public Member Functions
PodHybridDdSpec ()
int datasize () const
int get_root (void *p)
int get_child (void *p, int level, int value)
void get_copy (void *to, void const *from)
void destruct (void *p)
void destructLevel (int level)
size_t hash_code (void const *p, int level) const
bool equal_to (void const *p, void const *q, int level) const
void printState (std::ostream &os, S_State const &s, A_State const *a) const
void print_state (std::ostream &os, void const *p) const
Public Member Functions inherited from tdzdd::DdSpecBase< S, AR >
S & entity ()
S const & entity () const
void printLevel (std::ostream &os, int level) const
void print_level (std::ostream &os, int level) const
void dumpDot (std::ostream &os=std::cout, std::string title=typenameof< S >()) const
Dumps the node table in Graphviz (dot) format.
void dumpDotCut (std::ostream &os=std::cout, std::string title=typenameof< S >()) const
Dumps the node table in Graphviz (dot) format.
Protected Member Functions
void setArraySize (int n)
Additional Inherited Members
Static Public Attributes inherited from tdzdd::DdSpecBase< S, AR >
static int const ARITY = AR
Detailed Description
template<typename S, typename TS, typename TA, int AR>
class tdzdd::PodHybridDdSpec< S, TS, TA, AR >
Abstract class of DD specifications using both POD scalar and POD array states.
Every implementation must have the following functions:
int getRoot(TS& scalar, TA* array)
int getChild(TS& scalar, TA* array, int level, int value)
Optionally, the following functions can be overloaded:
void printLevel(std::ostream& os, int level) const
void printState(std::ostream& os, TS const& s, TA const* a) const
Template Parameters
S the class implementing this class.
TS data type of scalar.
TA data type of array elements.
AR arity of the nodes.
Definition at line 463 of file DdSpec.hpp.
Member Typedef Documentation
template<typename S , typename TS , typename TA , int AR> typedef TA tdzdd::PodHybridDdSpec< S, TS, TA, AR >::A_State
Definition at line 466 of file DdSpec.hpp.
template<typename S , typename TS , typename TA , int AR> typedef TS tdzdd::PodHybridDdSpec< S, TS, TA, AR >::S_State
Definition at line 465 of file DdSpec.hpp.
Constructor & Destructor Documentation
template<typename S , typename TS , typename TA , int AR> tdzdd::PodHybridDdSpec< S, TS, TA, AR >::PodHybridDdSpec () inline
Definition at line 504 of file DdSpec.hpp.
Member Function Documentation
template<typename S , typename TS , typename TA , int AR> int tdzdd::PodHybridDdSpec< S, TS, TA, AR >::datasize () const inline
Definition at line 508 of file DdSpec.hpp.
template<typename S , typename TS , typename TA , int AR> void tdzdd::PodHybridDdSpec< S, TS, TA, AR >::destruct (void * p) inline
Definition at line 530 of file DdSpec.hpp.
template<typename S , typename TS , typename TA , int AR> void tdzdd::PodHybridDdSpec< S, TS, TA, AR >::destructLevel (int level) inline
Definition at line 533 of file DdSpec.hpp.
template<typename S , typename TS , typename TA , int AR> bool tdzdd::PodHybridDdSpec< S, TS, TA, AR >::equal_to (void const * p, void const * q, int level) const inline
Definition at line 547 of file DdSpec.hpp.
template<typename S , typename TS , typename TA , int AR> int tdzdd::PodHybridDdSpec< S, TS, TA, AR >::get_child (void * p, int level, int value) inline
Definition at line 516 of file DdSpec.hpp.
References tdzdd::DdSpecBase< S, AR >::entity().
template<typename S , typename TS , typename TA , int AR> void tdzdd::PodHybridDdSpec< S, TS, TA, AR >::get_copy (void * to, void const * from) inline
Definition at line 521 of file DdSpec.hpp.
template<typename S , typename TS , typename TA , int AR> int tdzdd::PodHybridDdSpec< S, TS, TA, AR >::get_root (void * p) inline
Definition at line 512 of file DdSpec.hpp.
References tdzdd::DdSpecBase< S, AR >::entity().
template<typename S , typename TS , typename TA , int AR> size_t tdzdd::PodHybridDdSpec< S, TS, TA, AR >::hash_code (void const * p, int level) const inline
Definition at line 536 of file DdSpec.hpp.
template<typename S , typename TS , typename TA , int AR> void tdzdd::PodHybridDdSpec< S, TS, TA, AR >::print_state (std::ostream & os, void const * p) const inline
Definition at line 568 of file DdSpec.hpp.
References tdzdd::DdSpecBase< S, AR >::entity().
template<typename S , typename TS , typename TA , int AR> void tdzdd::PodHybridDdSpec< S, TS, TA, AR >::printState (std::ostream & os, S_State const & s, A_State const * a) const inline
Definition at line 557 of file DdSpec.hpp.
template<typename S , typename TS , typename TA , int AR> void tdzdd::PodHybridDdSpec< S, TS, TA, AR >::setArraySize (int n) inline protected
Definition at line 496 of file DdSpec.hpp.
The documentation for this class was generated from the following file:
include/tdzdd/DdSpec.hpp