TdZdd: tdzdd::BinaryOperation< S, S1, S2 > Class Template Reference
tdzdd::BinaryOperation< S, S1, S2 > Class Template Reference
#include <BinaryOperation.hpp>
Public Member Functions
BinaryOperation (S1 const &s1, S2 const &s2)
void get_copy (void *to, void const *from)
int merge_states (void *p1, void *p2)
void destruct (void *p)
void destructLevel (int level)
size_t hash_code (void const *p, int level) const
bool equal_to (void const *p, void const *q, int level) const
Public Member Functions inherited from tdzdd::PodArrayDdSpec< S, size_t, 2 >
PodArrayDdSpec ()
int datasize () const
int get_root (void *p)
int get_child (void *p, int level, int value)
void get_copy (void *to, void const *from)
int mergeStates (size_t *a1, size_t *a2)
int merge_states (void *p1, void *p2)
void destruct (void *p)
void destructLevel (int level)
size_t hash_code (void const *p, int level) const
bool equal_to (void const *p, void const *q, int level) const
void printState (std::ostream &os, State const *a) const
void printStateAtLevel (std::ostream &os, State const *a, int level) const
void print_state (std::ostream &os, void const *p, int level) const
Public Member Functions inherited from tdzdd::DdSpecBase< S, AR >
S & entity ()
S const & entity () const
void printLevel (std::ostream &os, int level) const
std::vector< std::pair< int, int > > findOneInstance () const
Returns a random instance using simple depth-first search without caching.
void dumpDot (std::ostream &os=std::cout, std::string title=typenameof< S >()) const
Dumps the node table in Graphviz (dot) format.
Protected Types
typedef S1 Spec1
typedef S2 Spec2
typedef size_t Word
Protected Member Functions
void setLevel1 (void *p, int level) const
int level1 (void const *p) const
void setLevel2 (void *p, int level) const
int level2 (void const *p) const
void * state1 (void *p) const
void const * state1 (void const *p) const
void * state2 (void *p) const
void const * state2 (void const *p) const
Protected Member Functions inherited from tdzdd::PodArrayDdSpec< S, size_t, 2 >
void setArraySize (int n)
int getArraySize () const
Static Protected Member Functions
static int wordSize (int size)
Static Protected Member Functions inherited from tdzdd::DdSpecBase< S, AR >
template<typename T >
static size_t rawHashCode (T const &o)
template<typename T >
static size_t rawEqualTo (T const &o1, T const &o2)
Protected Attributes
Spec1 spec1
Spec2 spec2
int const stateWords1
int const stateWords2
Static Protected Attributes
static size_t const levelWords
Additional Inherited Members
Public Types inherited from tdzdd::PodArrayDdSpec< S, size_t, 2 >
typedef size_t State
Static Public Attributes inherited from tdzdd::DdSpecBase< S, AR >
static int const ARITY = AR
Detailed Description
template<typename S, typename S1, typename S2>
class tdzdd::BinaryOperation< S, S1, S2 >
Definition at line 35 of file BinaryOperation.hpp.
Member Typedef Documentation
template<typename S , typename S1 , typename S2 > typedef S1 tdzdd::BinaryOperation< S, S1, S2 >::Spec1 protected
Definition at line 37 of file BinaryOperation.hpp.
template<typename S , typename S1 , typename S2 > typedef S2 tdzdd::BinaryOperation< S, S1, S2 >::Spec2 protected
Definition at line 38 of file BinaryOperation.hpp.
template<typename S , typename S1 , typename S2 > typedef size_t tdzdd::BinaryOperation< S, S1, S2 >::Word protected
Definition at line 39 of file BinaryOperation.hpp.
Constructor & Destructor Documentation
template<typename S , typename S1 , typename S2 > tdzdd::BinaryOperation< S, S1, S2 >::BinaryOperation (S1 const & s1, S2 const & s2) inline
Definition at line 86 of file BinaryOperation.hpp.
References tdzdd::PodArrayDdSpec< S, size_t, 2 >::setArraySize().
Member Function Documentation
template<typename S , typename S1 , typename S2 > void tdzdd::BinaryOperation< S, S1, S2 >::destruct (void * p) inline
Definition at line 106 of file BinaryOperation.hpp.
References tdzdd::BinaryOperation< S, S1, S2 >::state1(), and tdzdd::BinaryOperation< S, S1, S2 >::state2().
template<typename S , typename S1 , typename S2 > void tdzdd::BinaryOperation< S, S1, S2 >::destructLevel (int level) inline
Definition at line 111 of file BinaryOperation.hpp.
template<typename S , typename S1 , typename S2 > bool tdzdd::BinaryOperation< S, S1, S2 >::equal_to (void const * p, void const * q, int level) const inline
Definition at line 126 of file BinaryOperation.hpp.
References tdzdd::BinaryOperation< S, S1, S2 >::level1(), tdzdd::BinaryOperation< S, S1, S2 >::level2(), tdzdd::BinaryOperation< S, S1, S2 >::state1(), and tdzdd::BinaryOperation< S, S1, S2 >::state2().
template<typename S , typename S1 , typename S2 > void tdzdd::BinaryOperation< S, S1, S2 >::get_copy (void * to, void const * from) inline
Definition at line 94 of file BinaryOperation.hpp.
References tdzdd::BinaryOperation< S, S1, S2 >::level1(), tdzdd::BinaryOperation< S, S1, S2 >::level2(), tdzdd::BinaryOperation< S, S1, S2 >::setLevel1(), tdzdd::BinaryOperation< S, S1, S2 >::setLevel2(), tdzdd::BinaryOperation< S, S1, S2 >::state1(), and tdzdd::BinaryOperation< S, S1, S2 >::state2().
template<typename S , typename S1 , typename S2 > size_t tdzdd::BinaryOperation< S, S1, S2 >::hash_code (void const * p, int level) const inline
Definition at line 116 of file BinaryOperation.hpp.
References tdzdd::BinaryOperation< S, S1, S2 >::level1(), tdzdd::BinaryOperation< S, S1, S2 >::level2(), tdzdd::BinaryOperation< S, S1, S2 >::state1(), and tdzdd::BinaryOperation< S, S1, S2 >::state2().
template<typename S , typename S1 , typename S2 > int tdzdd::BinaryOperation< S, S1, S2 >::level1 (void const * p) const inline protected
Definition at line 57 of file BinaryOperation.hpp.
Referenced by tdzdd::BinaryOperation< S, S1, S2 >::equal_to(), tdzdd::BinaryOperation< S, S1, S2 >::get_copy(), and tdzdd::BinaryOperation< S, S1, S2 >::hash_code().
template<typename S , typename S1 , typename S2 > int tdzdd::BinaryOperation< S, S1, S2 >::level2 (void const * p) const inline protected
Definition at line 65 of file BinaryOperation.hpp.
Referenced by tdzdd::BinaryOperation< S, S1, S2 >::equal_to(), tdzdd::BinaryOperation< S, S1, S2 >::get_copy(), and tdzdd::BinaryOperation< S, S1, S2 >::hash_code().
template<typename S , typename S1 , typename S2 > int tdzdd::BinaryOperation< S, S1, S2 >::merge_states (void * p1, void * p2) inline
Definition at line 101 of file BinaryOperation.hpp.
References tdzdd::BinaryOperation< S, S1, S2 >::state1(), and tdzdd::BinaryOperation< S, S1, S2 >::state2().
template<typename S , typename S1 , typename S2 > void tdzdd::BinaryOperation< S, S1, S2 >::setLevel1 (void * p, int level) const inline protected
Definition at line 53 of file BinaryOperation.hpp.
Referenced by tdzdd::BinaryOperation< S, S1, S2 >::get_copy().
template<typename S , typename S1 , typename S2 > void tdzdd::BinaryOperation< S, S1, S2 >::setLevel2 (void * p, int level) const inline protected
Definition at line 61 of file BinaryOperation.hpp.
Referenced by tdzdd::BinaryOperation< S, S1, S2 >::get_copy().
template<typename S , typename S1 , typename S2 > void* tdzdd::BinaryOperation< S, S1, S2 >::state1 (void * p) const inline protected
Definition at line 69 of file BinaryOperation.hpp.
Referenced by tdzdd::BinaryOperation< S, S1, S2 >::destruct(), tdzdd::ZddIntersection_< S, S1, S2 >::destruct(), tdzdd::BinaryOperation< S, S1, S2 >::equal_to(), tdzdd::ZddIntersection_< S, S1, S2 >::equal_to(), tdzdd::BinaryOperation< S, S1, S2 >::get_copy(), tdzdd::ZddIntersection_< S, S1, S2 >::get_copy(), tdzdd::ZddIntersection_< S, S1, S2 >::getChild(), tdzdd::ZddIntersection_< S, S1, S2 >::getRoot(), tdzdd::BinaryOperation< S, S1, S2 >::hash_code(), tdzdd::ZddIntersection_< S, S1, S2 >::hash_code(), tdzdd::BinaryOperation< S, S1, S2 >::merge_states(), tdzdd::ZddIntersection_< S, S1, S2 >::merge_states(), and tdzdd::ZddIntersection_< S, S1, S2 >::print_state().
template<typename S , typename S1 , typename S2 > void const* tdzdd::BinaryOperation< S, S1, S2 >::state1 (void const * p) const inline protected
Definition at line 73 of file BinaryOperation.hpp.
template<typename S , typename S1 , typename S2 > void* tdzdd::BinaryOperation< S, S1, S2 >::state2 (void * p) const inline protected
Definition at line 77 of file BinaryOperation.hpp.
Referenced by tdzdd::BinaryOperation< S, S1, S2 >::destruct(), tdzdd::ZddIntersection_< S, S1, S2 >::destruct(), tdzdd::BinaryOperation< S, S1, S2 >::equal_to(), tdzdd::ZddIntersection_< S, S1, S2 >::equal_to(), tdzdd::BinaryOperation< S, S1, S2 >::get_copy(), tdzdd::ZddIntersection_< S, S1, S2 >::get_copy(), tdzdd::ZddIntersection_< S, S1, S2 >::getChild(), tdzdd::ZddIntersection_< S, S1, S2 >::getRoot(), tdzdd::BinaryOperation< S, S1, S2 >::hash_code(), tdzdd::ZddIntersection_< S, S1, S2 >::hash_code(), tdzdd::BinaryOperation< S, S1, S2 >::merge_states(), tdzdd::ZddIntersection_< S, S1, S2 >::merge_states(), and tdzdd::ZddIntersection_< S, S1, S2 >::print_state().
template<typename S , typename S1 , typename S2 > void const* tdzdd::BinaryOperation< S, S1, S2 >::state2 (void const * p) const inline protected
Definition at line 81 of file BinaryOperation.hpp.
template<typename S , typename S1 , typename S2 > static int tdzdd::BinaryOperation< S, S1, S2 >::wordSize (int size) inline static protected
Definition at line 49 of file BinaryOperation.hpp.
Member Data Documentation
template<typename S , typename S1 , typename S2 > size_t const tdzdd::BinaryOperation< S, S1, S2 >::levelWords static protected
Initial value:
= (sizeof(int[2]) + sizeof(Word) - 1)
            / sizeof(Word)
Definition at line 41 of file BinaryOperation.hpp.
template<typename S , typename S1 , typename S2 > Spec1 tdzdd::BinaryOperation< S, S1, S2 >::spec1 protected
Definition at line 44 of file BinaryOperation.hpp.
template<typename S , typename S1 , typename S2 > Spec2 tdzdd::BinaryOperation< S, S1, S2 >::spec2 protected
Definition at line 45 of file BinaryOperation.hpp.
template<typename S , typename S1 , typename S2 > int const tdzdd::BinaryOperation< S, S1, S2 >::stateWords1 protected
Definition at line 46 of file BinaryOperation.hpp.
template<typename S , typename S1 , typename S2 > int const tdzdd::BinaryOperation< S, S1, S2 >::stateWords2 protected
Definition at line 47 of file BinaryOperation.hpp.
The documentation for this class was generated from the following file:
include/tdzdd/op/BinaryOperation.hpp