TdZdd: tdzdd::MessageHandler_< os > Class Template Reference
tdzdd::MessageHandler_< os > Class Template Reference
#include <MessageHandler.hpp>
Classes
class Buf
Public Member Functions
MessageHandler_ ()
virtual ~MessageHandler_ ()
MessageHandler_ & begin (std::string const &s)
MessageHandler_ & setSteps (int steps)
MessageHandler_ & step (char dot= '-')
MessageHandler_ & end (std::string const &msg="", std::string const &info="")
MessageHandler_ & end (size_t n)
int col () const
Static Public Member Functions
static bool showMessages (bool flag=true)
Private Attributes
Buf buf
std::string name
int indent
int beginLine
ResourceUsage initialUsage
ResourceUsage prevUsage
int totalSteps
int stepCount
int dotCount
time_t dotTime
bool stepping
Static Private Attributes
static int const INDENT_SIZE = 2
static bool enabled = false
static int indentLevel = 0
static int lineno = 1
static int column = 0
static Buf * lastUser = 0
Detailed Description
template<std::ostream & os>
class tdzdd::MessageHandler_< os >
Definition at line 53 of file MessageHandler.hpp.
Constructor & Destructor Documentation
template<std::ostream & os> tdzdd::MessageHandler_< os >::MessageHandler_ () inline
Definition at line 123 of file MessageHandler.hpp.
template<std::ostream & os> virtual tdzdd::MessageHandler_< os >::~MessageHandler_ () inline virtual
Definition at line 132 of file MessageHandler.hpp.
References tdzdd::MessageHandler_< os >::end().
Member Function Documentation
template<std::ostream & os> MessageHandler_& tdzdd::MessageHandler_< os >::begin (std::string const & s) inline
Definition at line 142 of file MessageHandler.hpp.
References tdzdd::capitalize(), tdzdd::MessageHandler_< os >::end(), tdzdd::MessageHandler_< os >::INDENT_SIZE, tdzdd::MessageHandler_< os >::initialUsage, tdzdd::MessageHandler_< os >::lineno, tdzdd::MessageHandler_< os >::setSteps(), and tdzdd::ResourceUsage::update().
Referenced by tdzdd::DdStructure< ARITY >::construct_(), tdzdd::DdStructure< ARITY >::constructMP_(), tdzdd::PathCounter< S >::count(), tdzdd::PathCounter< S >::count64(), tdzdd::PathCounter< S >::countFast(), tdzdd::DdStructure< ARITY >::evaluate(), tdzdd::GraphillionZdd::read(), tdzdd::Graph::readAdjacencyList(), tdzdd::Graph::readEdges(), tdzdd::Graph::readVertexGroups(), tdzdd::DdStructure< ARITY >::reduce(), tdzdd::DdStructure< ARITY >::zddSubset_(), and tdzdd::DdStructure< ARITY >::zddSubsetMP_().
template<std::ostream & os> int tdzdd::MessageHandler_< os >::col () const inline
Definition at line 249 of file MessageHandler.hpp.
References tdzdd::MessageHandler_< os >::column.
template<std::ostream & os> MessageHandler_& tdzdd::MessageHandler_< os >::end (std::string const & msg = "", std::string const & info = "") inline
Definition at line 206 of file MessageHandler.hpp.
References tdzdd::capitalize(), tdzdd::MessageHandler_< os >::INDENT_SIZE, tdzdd::MessageHandler_< os >::initialUsage, and tdzdd::MessageHandler_< os >::name.
Referenced by tdzdd::MessageHandler_< os >::begin(), tdzdd::DdStructure< ARITY >::construct_(), tdzdd::DdStructure< ARITY >::constructMP_(), tdzdd::PathCounter< S >::count(), tdzdd::PathCounter< S >::count64(), tdzdd::PathCounter< S >::countFast(), tdzdd::MessageHandler_< os >::end(), tdzdd::DdStructure< ARITY >::evaluate(), tdzdd::GraphillionZdd::read(), tdzdd::Graph::readAdjacencyList(), tdzdd::Graph::readEdges(), tdzdd::Graph::readVertexGroups(), tdzdd::DdStructure< ARITY >::reduce(), tdzdd::DdStructure< ARITY >::zddSubset_(), tdzdd::DdStructure< ARITY >::zddSubsetMP_(), and tdzdd::MessageHandler_< os >::~MessageHandler_().
template<std::ostream & os> MessageHandler_& tdzdd::MessageHandler_< os >::end (size_t n) inline
Definition at line 244 of file MessageHandler.hpp.
References tdzdd::MessageHandler_< os >::end(), and tdzdd::to_string().
template<std::ostream & os> MessageHandler_& tdzdd::MessageHandler_< os >::setSteps (int steps) inline
Definition at line 156 of file MessageHandler.hpp.
Referenced by tdzdd::MessageHandler_< os >::begin(), tdzdd::DdStructure< ARITY >::construct_(), tdzdd::DdStructure< ARITY >::constructMP_(), tdzdd::PathCounter< S >::count(), tdzdd::PathCounter< S >::count64(), tdzdd::PathCounter< S >::countFast(), tdzdd::DdStructure< ARITY >::evaluate(), tdzdd::DdStructure< ARITY >::reduce(), tdzdd::DdStructure< ARITY >::zddSubset_(), and tdzdd::DdStructure< ARITY >::zddSubsetMP_().
template<std::ostream & os> static bool tdzdd::MessageHandler_< os >::showMessages (bool flag = true) inline static
Definition at line 136 of file MessageHandler.hpp.
References tdzdd::MessageHandler_< os >::enabled.
template<std::ostream & os> MessageHandler_& tdzdd::MessageHandler_< os >::step (char dot = '-') inline
Definition at line 166 of file MessageHandler.hpp.
References tdzdd::MessageHandler_< os >::dotCount, tdzdd::ResourceUsage::elapsedTime(), tdzdd::ResourceUsage::memory(), tdzdd::MessageHandler_< os >::prevUsage, tdzdd::MessageHandler_< os >::stepCount, and tdzdd::MessageHandler_< os >::totalSteps.
Referenced by tdzdd::DdStructure< ARITY >::construct_(), tdzdd::DdStructure< ARITY >::constructMP_(), tdzdd::PathCounter< S >::count(), tdzdd::PathCounter< S >::count64(), tdzdd::PathCounter< S >::countFast(), tdzdd::DdStructure< ARITY >::evaluate(), tdzdd::DdStructure< ARITY >::reduce(), tdzdd::DdStructure< ARITY >::zddSubset_(), and tdzdd::DdStructure< ARITY >::zddSubsetMP_().
Member Data Documentation
template<std::ostream & os> int tdzdd::MessageHandler_< os >::beginLine private
Definition at line 113 of file MessageHandler.hpp.
template<std::ostream & os> Buf tdzdd::MessageHandler_< os >::buf private
Definition at line 110 of file MessageHandler.hpp.
template<std::ostream & os> int tdzdd::MessageHandler_< os >::column = 0 static private
Definition at line 107 of file MessageHandler.hpp.
Referenced by tdzdd::MessageHandler_< os >::col(), and tdzdd::MessageHandler_< os >::Buf::overflow().
template<std::ostream & os> int tdzdd::MessageHandler_< os >::dotCount private
Definition at line 118 of file MessageHandler.hpp.
Referenced by tdzdd::MessageHandler_< os >::step().
template<std::ostream & os> time_t tdzdd::MessageHandler_< os >::dotTime private
Definition at line 119 of file MessageHandler.hpp.
template<std::ostream & os> bool tdzdd::MessageHandler_< os >::enabled = false static private
Definition at line 104 of file MessageHandler.hpp.
Referenced by tdzdd::MessageHandler_< os >::Buf::overflow(), and tdzdd::MessageHandler_< os >::showMessages().
template<std::ostream & os> int tdzdd::MessageHandler_< os >::indent private
Definition at line 112 of file MessageHandler.hpp.
Referenced by tdzdd::MessageHandler_< os >::Buf::overflow().
template<std::ostream & os> int const tdzdd::MessageHandler_< os >::INDENT_SIZE = 2 static private
Definition at line 103 of file MessageHandler.hpp.
Referenced by tdzdd::MessageHandler_< os >::begin(), and tdzdd::MessageHandler_< os >::end().
template<std::ostream & os> int tdzdd::MessageHandler_< os >::indentLevel = 0 static private
Definition at line 105 of file MessageHandler.hpp.
template<std::ostream & os> ResourceUsage tdzdd::MessageHandler_< os >::initialUsage private
Definition at line 114 of file MessageHandler.hpp.
Referenced by tdzdd::MessageHandler_< os >::begin(), and tdzdd::MessageHandler_< os >::end().
template<std::ostream & os> MessageHandler_< os >::Buf * tdzdd::MessageHandler_< os >::lastUser = 0 static private
Definition at line 108 of file MessageHandler.hpp.
Referenced by tdzdd::MessageHandler_< os >::Buf::overflow().
template<std::ostream & os> int tdzdd::MessageHandler_< os >::lineno = 1 static private
Definition at line 106 of file MessageHandler.hpp.
Referenced by tdzdd::MessageHandler_< os >::begin(), and tdzdd::MessageHandler_< os >::Buf::overflow().
template<std::ostream & os> std::string tdzdd::MessageHandler_< os >::name private
Definition at line 111 of file MessageHandler.hpp.
Referenced by tdzdd::MessageHandler_< os >::end().
template<std::ostream & os> ResourceUsage tdzdd::MessageHandler_< os >::prevUsage private
Definition at line 115 of file MessageHandler.hpp.
Referenced by tdzdd::MessageHandler_< os >::step().
template<std::ostream & os> int tdzdd::MessageHandler_< os >::stepCount private
Definition at line 117 of file MessageHandler.hpp.
Referenced by tdzdd::MessageHandler_< os >::step().
template<std::ostream & os> bool tdzdd::MessageHandler_< os >::stepping private
Definition at line 120 of file MessageHandler.hpp.
template<std::ostream & os> int tdzdd::MessageHandler_< os >::totalSteps private
Definition at line 116 of file MessageHandler.hpp.
Referenced by tdzdd::MessageHandler_< os >::step().
The documentation for this class was generated from the following file:
include/tdzdd/util/MessageHandler.hpp