TdZdd: tdzdd::Unreduction_< T, S, ZDD > Class Template Reference
tdzdd::Unreduction_< T, S, ZDD > Class Template Reference
#include <Unreduction.hpp>
Public Member Functions
Unreduction_ (S const &s, int numVars)
int getRoot (Word *p)
int getChild (Word *p, int i, int value)
void get_copy (void *to, void const *from)
void destruct (void *p)
void destructLevel (int level)
int merge_states (void *p1, void *p2)
size_t hash_code (void const *p, int i) const
bool equal_to (void const *p, void const *q, int i) const
void print_state (std::ostream &os, void const *p, int l) const
Public Member Functions inherited from tdzdd::PodArrayDdSpec< T, size_t, S::ARITY >
PodArrayDdSpec ()
int datasize () const
int get_root (void *p)
int get_child (void *p, int level, int value)
void get_copy (void *to, void const *from)
int mergeStates (size_t *a1, size_t *a2)
int merge_states (void *p1, void *p2)
void destruct (void *p)
void destructLevel (int level)
size_t hash_code (void const *p, int level) const
bool equal_to (void const *p, void const *q, int level) const
void printState (std::ostream &os, State const *a) const
void printStateAtLevel (std::ostream &os, State const *a, int level) const
void print_state (std::ostream &os, void const *p, int level) const
Public Member Functions inherited from tdzdd::DdSpecBase< T, AR >
T & entity ()
Tconst & entity () const
void printLevel (std::ostream &os, int level) const
std::vector< std::pair< int, int > > findOneInstance () const
Returns a random instance using simple depth-first search without caching.
void dumpDot (std::ostream &os=std::cout, std::string title=typenameof< T >()) const
Dumps the node table in Graphviz (dot) format.
Protected Types
typedef S Spec
typedef size_t Word
Protected Member Functions
int & level (void *p) const
int level (void const *p) const
void * state (void *p) const
void const * state (void const *p) const
Protected Member Functions inherited from tdzdd::PodArrayDdSpec< T, size_t, S::ARITY >
void setArraySize (int n)
int getArraySize () const
Static Protected Member Functions
static int wordSize (int size)
Static Protected Member Functions inherited from tdzdd::DdSpecBase< T, AR >
static size_t rawHashCode (T const &o)
static size_t rawEqualTo (T const &o1, T const &o2)
Protected Attributes
Spec spec
int const stateWords
int numVars
Static Protected Attributes
static size_t const levelWords
Additional Inherited Members
Public Types inherited from tdzdd::PodArrayDdSpec< T, size_t, S::ARITY >
typedef size_t State
Static Public Attributes inherited from tdzdd::DdSpecBase< T, AR >
static int const ARITY
Detailed Description
template<typename T, typename S, bool ZDD>
class tdzdd::Unreduction_< T, S, ZDD >
Definition at line 35 of file Unreduction.hpp.
Member Typedef Documentation
template<typename T, typename S, bool ZDD> typedef S tdzdd::Unreduction_< T, S, ZDD >::Spec protected
Definition at line 37 of file Unreduction.hpp.
template<typename T, typename S, bool ZDD> typedef size_t tdzdd::Unreduction_< T, S, ZDD >::Word protected
Definition at line 38 of file Unreduction.hpp.
Constructor & Destructor Documentation
template<typename T, typename S, bool ZDD> tdzdd::Unreduction_< T, S, ZDD >::Unreduction_ (S const & s, int numVars) inline
Definition at line 68 of file Unreduction.hpp.
Member Function Documentation
template<typename T, typename S, bool ZDD> void tdzdd::Unreduction_< T, S, ZDD >::destruct (void * p) inline
Definition at line 99 of file Unreduction.hpp.
template<typename T, typename S, bool ZDD> void tdzdd::Unreduction_< T, S, ZDD >::destructLevel (int level) inline
Definition at line 103 of file Unreduction.hpp.
template<typename T, typename S, bool ZDD> bool tdzdd::Unreduction_< T, S, ZDD >::equal_to (void const * p, void const * q, int i) const inline
Definition at line 117 of file Unreduction.hpp.
template<typename T, typename S, bool ZDD> void tdzdd::Unreduction_< T, S, ZDD >::get_copy (void * to, void const * from) inline
Definition at line 94 of file Unreduction.hpp.
template<typename T, typename S, bool ZDD> int tdzdd::Unreduction_< T, S, ZDD >::getChild (Word * p, int i, int value) inline
Definition at line 80 of file Unreduction.hpp.
template<typename T, typename S, bool ZDD> int tdzdd::Unreduction_< T, S, ZDD >::getRoot (Word * p) inline
Definition at line 73 of file Unreduction.hpp.
template<typename T, typename S, bool ZDD> size_t tdzdd::Unreduction_< T, S, ZDD >::hash_code (void const * p, int i) const inline
Definition at line 111 of file Unreduction.hpp.
template<typename T, typename S, bool ZDD> int& tdzdd::Unreduction_< T, S, ZDD >::level (void * p) const inline protected
Definition at line 51 of file Unreduction.hpp.
Referenced by tdzdd::Unreduction_< BddUnreduction< S >, S, false >::equal_to(), tdzdd::Unreduction_< BddUnreduction< S >, S, false >::get_copy(), tdzdd::Unreduction_< BddUnreduction< S >, S, false >::getChild(), tdzdd::Unreduction_< BddUnreduction< S >, S, false >::getRoot(), tdzdd::Unreduction_< BddUnreduction< S >, S, false >::hash_code(), and tdzdd::Unreduction_< BddUnreduction< S >, S, false >::print_state().
template<typename T, typename S, bool ZDD> int tdzdd::Unreduction_< T, S, ZDD >::level (void const * p) const inline protected
Definition at line 55 of file Unreduction.hpp.
template<typename T, typename S, bool ZDD> int tdzdd::Unreduction_< T, S, ZDD >::merge_states (void * p1, void * p2) inline
Definition at line 107 of file Unreduction.hpp.
template<typename T, typename S, bool ZDD> void tdzdd::Unreduction_< T, S, ZDD >::print_state (std::ostream & os, void const * p, int l) const inline
Definition at line 123 of file Unreduction.hpp.
template<typename T, typename S, bool ZDD> void* tdzdd::Unreduction_< T, S, ZDD >::state (void * p) const inline protected
Definition at line 59 of file Unreduction.hpp.
Referenced by tdzdd::Unreduction_< BddUnreduction< S >, S, false >::destruct(), tdzdd::Unreduction_< BddUnreduction< S >, S, false >::equal_to(), tdzdd::Unreduction_< BddUnreduction< S >, S, false >::get_copy(), tdzdd::Unreduction_< BddUnreduction< S >, S, false >::getChild(), tdzdd::Unreduction_< BddUnreduction< S >, S, false >::getRoot(), tdzdd::Unreduction_< BddUnreduction< S >, S, false >::hash_code(), tdzdd::Unreduction_< BddUnreduction< S >, S, false >::merge_states(), and tdzdd::Unreduction_< BddUnreduction< S >, S, false >::print_state().
template<typename T, typename S, bool ZDD> void const* tdzdd::Unreduction_< T, S, ZDD >::state (void const * p) const inline protected
Definition at line 63 of file Unreduction.hpp.
template<typename T, typename S, bool ZDD> static int tdzdd::Unreduction_< T, S, ZDD >::wordSize (int size) inline static protected
Definition at line 47 of file Unreduction.hpp.
Member Data Documentation
template<typename T, typename S, bool ZDD> size_t const tdzdd::Unreduction_< T, S, ZDD >::levelWords static protected
Initial value:
= (sizeof(int) + sizeof(Word) - 1)
            / sizeof(Word)
Definition at line 40 of file Unreduction.hpp.
template<typename T, typename S, bool ZDD> int tdzdd::Unreduction_< T, S, ZDD >::numVars protected
Definition at line 45 of file Unreduction.hpp.
template<typename T, typename S, bool ZDD> Spec tdzdd::Unreduction_< T, S, ZDD >::spec protected
Definition at line 43 of file Unreduction.hpp.
template<typename T, typename S, bool ZDD> int const tdzdd::Unreduction_< T, S, ZDD >::stateWords protected
Definition at line 44 of file Unreduction.hpp.
The documentation for this class was generated from the following file:
include/tdzdd/op/Unreduction.hpp