TdZdd: tdzdd::HybridDdSpec< S, TS, TA, AR > Class Template Reference
tdzdd::HybridDdSpec< S, TS, TA, AR > Class Template Reference
Abstract class of DD specifications using both scalar and POD array states.
#include <DdSpec.hpp>
Public Types
typedef TS S_State
typedef TA A_State
Public Member Functions
HybridDdSpec ()
int datasize () const
void construct (void *p)
int get_root (void *p)
int get_child (void *p, int level, int value)
void getCopy (void *p, S_State const &s)
void get_copy (void *to, void const *from)
int mergeStates (S_State &s1, A_State *a1, S_State &s2, A_State *a2)
int merge_states (void *p1, void *p2)
void destruct (void *p)
void destructLevel (int level)
size_t hashCode (S_State const &s) const
size_t hashCodeAtLevel (S_State const &s, int level) const
size_t hash_code (void const *p, int level) const
bool equalTo (S_State const &s1, S_State const &s2) const
bool equalToAtLevel (S_State const &s1, S_State const &s2, int level) const
bool equal_to (void const *p, void const *q, int level) const
void printState (std::ostream &os, S_State const &s, A_State const *a) const
void printStateAtLevel (std::ostream &os, S_State const &s, A_State const *a, int level) const
void print_state (std::ostream &os, void const *p, int level) const
Public Member Functions inherited from tdzdd::DdSpecBase< S, AR >
S & entity ()
S const & entity () const
void printLevel (std::ostream &os, int level) const
std::vector< std::pair< int,
int > > findOneInstance () const
Returns a random instance using simple depth-first search without caching.
void dumpDot (std::ostream &os=std::cout, std::string title=typenameof< S >()) const
Dumps the node table in Graphviz (dot) format.
Protected Member Functions
void setArraySize (int n)
int getArraySize () const
Additional Inherited Members
Static Public Attributes inherited from tdzdd::DdSpecBase< S, AR >
static int const ARITY = AR
Static Protected Member Functions inherited from tdzdd::DdSpecBase< S, AR >
template<typename T >
static size_t rawHashCode (T const &o)
template<typename T >
static size_t rawEqualTo (T const &o1, T const &o2)
Detailed Description
template<typename S, typename TS, typename TA, int AR>
class tdzdd::HybridDdSpec< S, TS, TA, AR >
Abstract class of DD specifications using both scalar and POD array states.
Every implementation must have the following functions:
int getRoot(TS& scalar, TA* array)
int getChild(TS& scalar, TA* array, int level, int value)
Optionally, the following functions can be overloaded:
void construct(void* p)
void getCopy(void* p, TS const& state)
void mergeStates(TS& s1, TA* a1, TS& s2, TA* a2)
size_t hashCode(TS const& state) const
bool equalTo(TS const& state1, TS const& state2) const
void printLevel(std::ostream& os, int level) const
void printState(std::ostream& os, TS const& s, TA const* a) const
Template Parameters
S the class implementing this class.
TS data type of scalar.
TA data type of array elements.
AR arity of the nodes.
Definition at line 497 of file DdSpec.hpp.
Member Typedef Documentation
template<typename S , typename TS , typename TA , int AR> typedef TA tdzdd::HybridDdSpec< S, TS, TA, AR >::A_State
Definition at line 500 of file DdSpec.hpp.
template<typename S , typename TS , typename TA , int AR> typedef TS tdzdd::HybridDdSpec< S, TS, TA, AR >::S_State
Definition at line 499 of file DdSpec.hpp.
Constructor & Destructor Documentation
template<typename S , typename TS , typename TA , int AR> tdzdd::HybridDdSpec< S, TS, TA, AR >::HybridDdSpec () inline
Definition at line 540 of file DdSpec.hpp.
Member Function Documentation
template<typename S , typename TS , typename TA , int AR> void tdzdd::HybridDdSpec< S, TS, TA, AR >::construct (void * p) inline
Definition at line 548 of file DdSpec.hpp.
template<typename S , typename TS , typename TA , int AR> int tdzdd::HybridDdSpec< S, TS, TA, AR >::datasize () const inline
Definition at line 544 of file DdSpec.hpp.
template<typename S , typename TS , typename TA , int AR> void tdzdd::HybridDdSpec< S, TS, TA, AR >::destruct (void * p) inline
Definition at line 587 of file DdSpec.hpp.
template<typename S , typename TS , typename TA , int AR> void tdzdd::HybridDdSpec< S, TS, TA, AR >::destructLevel (int level) inline
Definition at line 590 of file DdSpec.hpp.
template<typename S , typename TS , typename TA , int AR> bool tdzdd::HybridDdSpec< S, TS, TA, AR >::equal_to (void const * p, void const * q, int level) const inline
Definition at line 622 of file DdSpec.hpp.
References tdzdd::DdSpecBase< S, AR >::entity(), and tdzdd::HybridDdSpec< S, TS, TA, AR >::equalToAtLevel().
template<typename S , typename TS , typename TA , int AR> bool tdzdd::HybridDdSpec< S, TS, TA, AR >::equalTo (S_State const & s1, S_State const & s2) const inline
Definition at line 614 of file DdSpec.hpp.
References tdzdd::DdSpecBase< S, AR >::rawEqualTo().
template<typename S , typename TS , typename TA , int AR> bool tdzdd::HybridDdSpec< S, TS, TA, AR >::equalToAtLevel (S_State const & s1, S_State const & s2, int level) const inline
Definition at line 618 of file DdSpec.hpp.
References tdzdd::DdSpecBase< S, AR >::entity().
Referenced by tdzdd::HybridDdSpec< S, TS, TA, AR >::equal_to().
template<typename S , typename TS , typename TA , int AR> int tdzdd::HybridDdSpec< S, TS, TA, AR >::get_child (void * p, int level, int value) inline
Definition at line 557 of file DdSpec.hpp.
References tdzdd::DdSpecBase< S, AR >::entity().
template<typename S , typename TS , typename TA , int AR> void tdzdd::HybridDdSpec< S, TS, TA, AR >::get_copy (void * to, void const * from) inline
Definition at line 566 of file DdSpec.hpp.
References tdzdd::DdSpecBase< S, AR >::entity().
template<typename S , typename TS , typename TA , int AR> int tdzdd::HybridDdSpec< S, TS, TA, AR >::get_root (void * p) inline
Definition at line 552 of file DdSpec.hpp.
References tdzdd::DdSpecBase< S, AR >::entity().
template<typename S , typename TS , typename TA , int AR> int tdzdd::HybridDdSpec< S, TS, TA, AR >::getArraySize () const inline protected
Definition at line 535 of file DdSpec.hpp.
template<typename S , typename TS , typename TA , int AR> void tdzdd::HybridDdSpec< S, TS, TA, AR >::getCopy (void * p, S_State const & s) inline
Definition at line 562 of file DdSpec.hpp.
template<typename S , typename TS , typename TA , int AR> size_t tdzdd::HybridDdSpec< S, TS, TA, AR >::hash_code (void const * p, int level) const inline
Definition at line 601 of file DdSpec.hpp.
References tdzdd::DdSpecBase< S, AR >::entity().
template<typename S , typename TS , typename TA , int AR> size_t tdzdd::HybridDdSpec< S, TS, TA, AR >::hashCode (S_State const & s) const inline
Definition at line 593 of file DdSpec.hpp.
References tdzdd::DdSpecBase< S, AR >::rawHashCode().
template<typename S , typename TS , typename TA , int AR> size_t tdzdd::HybridDdSpec< S, TS, TA, AR >::hashCodeAtLevel (S_State const & s, int level) const inline
Definition at line 597 of file DdSpec.hpp.
References tdzdd::DdSpecBase< S, AR >::entity().
template<typename S , typename TS , typename TA , int AR> int tdzdd::HybridDdSpec< S, TS, TA, AR >::merge_states (void * p1, void * p2) inline
Definition at line 582 of file DdSpec.hpp.
References tdzdd::DdSpecBase< S, AR >::entity().
template<typename S , typename TS , typename TA , int AR> int tdzdd::HybridDdSpec< S, TS, TA, AR >::mergeStates (S_State & s1, A_State * a1, S_State & s2, A_State * a2) inline
Definition at line 578 of file DdSpec.hpp.
template<typename S , typename TS , typename TA , int AR> void tdzdd::HybridDdSpec< S, TS, TA, AR >::print_state (std::ostream & os, void const * p, int level) const inline
Definition at line 650 of file DdSpec.hpp.
References tdzdd::DdSpecBase< S, AR >::entity().
template<typename S , typename TS , typename TA , int AR> void tdzdd::HybridDdSpec< S, TS, TA, AR >::printState (std::ostream & os, S_State const & s, A_State const * a) const inline
Definition at line 636 of file DdSpec.hpp.
template<typename S , typename TS , typename TA , int AR> void tdzdd::HybridDdSpec< S, TS, TA, AR >::printStateAtLevel (std::ostream & os, S_State const & s, A_State const * a, int level) const inline
Definition at line 645 of file DdSpec.hpp.
References tdzdd::DdSpecBase< S, AR >::entity().
template<typename S , typename TS , typename TA , int AR> void tdzdd::HybridDdSpec< S, TS, TA, AR >::setArraySize (int n) inline protected
Definition at line 528 of file DdSpec.hpp.
The documentation for this class was generated from the following file:
include/tdzdd/DdSpec.hpp