TdZdd: tdzdd::DepthFirstSearcher< S > Class Template Reference
tdzdd::DepthFirstSearcher< S > Class Template Reference
#include <DepthFirstSearcher.hpp>
Public Member Functions
DepthFirstSearcher (Spec const &spec)
std::vector< std::pair< int, int > > findOneInstance ()
Returns a random instance using simple depth-first search.
Private Types
typedef S Spec
Private Member Functions
bool findOneInstanceStep (void *p, int i)
Private Attributes
Spec spec
int const datasize
MyList< char > statePool
std::vector< std::pair< int, int > > valueList
Static Private Attributes
static int const AR = Spec::ARITY
Detailed Description
template<typename S>
class tdzdd::DepthFirstSearcher< S >
Definition at line 36 of file DepthFirstSearcher.hpp.
Member Typedef Documentation
template<typename S > typedef S tdzdd::DepthFirstSearcher< S >::Spec private
Definition at line 37 of file DepthFirstSearcher.hpp.
Constructor & Destructor Documentation
template<typename S > tdzdd::DepthFirstSearcher< S >::DepthFirstSearcher (Spec const & spec) inline
Definition at line 47 of file DepthFirstSearcher.hpp.
Member Function Documentation
template<typename S > std::vector<std::pair<int,int> > tdzdd::DepthFirstSearcher< S >::findOneInstance () inline
Returns a random instance using simple depth-first search.
It does not guarantee that the selection is uniform. merge_states(void*, void*) is not supported.
Returns
a collection of (item, value) pairs.
Exceptions
std::runtime_error no instance exists.
Definition at line 58 of file DepthFirstSearcher.hpp.
References tdzdd::MyList< T, BLOCK_ELEMENTS >::alloc_front(), tdzdd::DepthFirstSearcher< S >::findOneInstanceStep(), tdzdd::MyList< T, BLOCK_ELEMENTS >::pop_front(), and tdzdd::DepthFirstSearcher< S >::valueList.
template<typename S > bool tdzdd::DepthFirstSearcher< S >::findOneInstanceStep (void * p, int i) inline private
Definition at line 84 of file DepthFirstSearcher.hpp.
References tdzdd::MyList< T, BLOCK_ELEMENTS >::alloc_front(), tdzdd::DepthFirstSearcher< S >::AR, and tdzdd::MyList< T, BLOCK_ELEMENTS >::pop_front().
Referenced by tdzdd::DepthFirstSearcher< S >::findOneInstance().
Member Data Documentation
template<typename S > int const tdzdd::DepthFirstSearcher< S >::AR = Spec::ARITY static private
Definition at line 38 of file DepthFirstSearcher.hpp.
Referenced by tdzdd::DepthFirstSearcher< S >::findOneInstanceStep().
template<typename S > int const tdzdd::DepthFirstSearcher< S >::datasize private
Definition at line 41 of file DepthFirstSearcher.hpp.
template<typename S > Spec tdzdd::DepthFirstSearcher< S >::spec private
Definition at line 40 of file DepthFirstSearcher.hpp.
template<typename S > MyList<char> tdzdd::DepthFirstSearcher< S >::statePool private
Definition at line 43 of file DepthFirstSearcher.hpp.
template<typename S > std::vector<std::pair<int,int> > tdzdd::DepthFirstSearcher< S >::valueList private
Definition at line 44 of file DepthFirstSearcher.hpp.
Referenced by tdzdd::DepthFirstSearcher< S >::findOneInstance().
The documentation for this class was generated from the following file:
include/tdzdd/dd/DepthFirstSearcher.hpp