TdZdd: tdzdd::MyVector< T, Size > Class Template Reference
tdzdd::MyVector< T, Size > Class Template Reference
#include <MyVector.hpp>
Classes
class reverse_iterator_
Public Types
typedef T * iterator
typedef T const * const_iterator
typedef reverse_iterator_< T > reverse_iterator
typedef reverse_iterator_< T const > const_reverse_iterator
Public Member Functions
MyVector ()
MyVector (Size n)
MyVector (Size n, T const &val)
MyVector (MyVector const &o)
MyVector & operator= (MyVector const &o)
template<typename U >
MyVector (std::vector< U > const &o)
template<typename U >
MyVector & operator= (std::vector< U > const &o)
void swap (MyVector &o)
~MyVector ()
Size capacity () const
Gets the current capacity of the storage.
Size size () const
Gets the number of elements.
bool empty () const
Checks emptiness.
void reserve (Size capacity)
Reserves the memory.
void init (Size n)
Initializes the array.
void resize (Size n)
Resizes the array.
T * erase (T *first, T *last)
Erases elements.
void clear ()
Initializes the array to be empty.
void push_back (T const &val)
Adds an element to the end of the array.
void pop_back ()
Removes the last element.
T & back ()
Accesses to the last element.
T const & back () const
Accesses to the last element.
T & operator[] (Size i)
Accesses to the i-th element.
T const & operator[] (Size i) const
Accesses to the i-th element.
T * data () const
Gets a pointer to the first element.
iterator begin ()
Gets a pointer to the first element.
const_iterator begin () const
Gets a pointer to the first element.
iterator end ()
Gets a pointer to the end of elements.
const_iterator end () const
Gets a pointer to the end of elements.
reverse_iterator rbegin ()
Returns a reverse iterator to the beginning.
const_reverse_iterator rbegin () const
Returns a reverse iterator to the beginning.
reverse_iterator rend ()
Returns a reverse iterator to the end.
const_reverse_iterator rend () const
Returns a reverse iterator to the end.
iterator erase (iterator pos)
Removes an element.
size_t hash () const
Gets the hash code of this object.
bool operator== (MyVector const &o) const
Checks equivalence between another object.
Private Member Functions
void ensureCapacity (Size capacity)
void moveElement (T &from, T &to)
template<>
void moveElement (MemoryPool &from, MemoryPool &to)
Static Private Member Functions
static T * allocate (Size n)
static void deallocate (T *p, Size n)
Private Attributes
Size capacity_
Size of the array.
Size size_
Current number of elements.
T * array_
Start address of the array.
Friends
std::ostream & operator<< (std::ostream &os, MyVector const &o)
Sends an object to an output stream.
Detailed Description
template<typename T, typename Size = size_t>
class tdzdd::MyVector< T, Size >
Definition at line 34 of file MyVector.hpp.
Member Typedef Documentation
template<typename T, typename Size = size_t> typedef T const* tdzdd::MyVector< T, Size >::const_iterator
Definition at line 381 of file MyVector.hpp.
template<typename T, typename Size = size_t> typedef reverse_iterator_<T const> tdzdd::MyVector< T, Size >::const_reverse_iterator
Definition at line 447 of file MyVector.hpp.
template<typename T, typename Size = size_t> typedef T* tdzdd::MyVector< T, Size >::iterator
Definition at line 380 of file MyVector.hpp.
template<typename T, typename Size = size_t> typedef reverse_iterator_<T> tdzdd::MyVector< T, Size >::reverse_iterator
Definition at line 446 of file MyVector.hpp.
Constructor & Destructor Documentation
template<typename T, typename Size = size_t> tdzdd::MyVector< T, Size >::MyVector () inline
Definition at line 61 of file MyVector.hpp.
template<typename T, typename Size = size_t> tdzdd::MyVector< T, Size >::MyVector (Size n) inline
Definition at line 65 of file MyVector.hpp.
template<typename T, typename Size = size_t> tdzdd::MyVector< T, Size >::MyVector (Size n, T const & val) inline
Definition at line 70 of file MyVector.hpp.
template<typename T, typename Size = size_t> tdzdd::MyVector< T, Size >::MyVector (MyVector< T, Size > const & o) inline
Definition at line 89 of file MyVector.hpp.
template<typename T, typename Size = size_t> template<typename U > tdzdd::MyVector< T, Size >::MyVector (std::vector< U > const & o) inline
Definition at line 108 of file MyVector.hpp.
template<typename T, typename Size = size_t> tdzdd::MyVector< T, Size >::~MyVector () inline
Definition at line 166 of file MyVector.hpp.
Member Function Documentation
template<typename T, typename Size = size_t> static T* tdzdd::MyVector< T, Size >::allocate (Size n) inline static private
Definition at line 39 of file MyVector.hpp.
Referenced by tdzdd::MyVector< tdzdd::DdDumper::Hasher< Spec > >::allocate(), tdzdd::MyVector< tdzdd::DdDumper::Hasher< Spec > >::reserve(), and tdzdd::MyVector< tdzdd::DdDumper::Hasher< Spec > >::resize().
template<typename T, typename Size = size_t> T& tdzdd::MyVector< T, Size >::back () inline
Accesses to the last element.
Returns
reference to the last element.
Definition at line 338 of file MyVector.hpp.
Referenced by tdzdd::DdBuilder< S >::construct(), tdzdd::PathCounter< S >::count(), tdzdd::PathCounter< S >::count64(), tdzdd::DdDumper< S >::dump(), and tdzdd::ZddSubsetter< S >::subset().
template<typename T, typename Size = size_t> T const& tdzdd::MyVector< T, Size >::back () const inline
Accesses to the last element.
Returns
reference to the last element.
Definition at line 347 of file MyVector.hpp.
template<typename T, typename Size = size_t> iterator tdzdd::MyVector< T, Size >::begin () inline
Gets a pointer to the first element.
Returns
pointer to the first element.
Definition at line 387 of file MyVector.hpp.
Referenced by tdzdd::DdReducer< ARITY, BDD, ZDD >::algorithmR(), tdzdd::DdStructure< ARITY >::dumpSapporo(), tdzdd::MyVector< tdzdd::DdDumper::Hasher< Spec > >::erase(), tdzdd::DdStructure< ARITY >::evaluate(), tdzdd::DdReducer< ARITY, BDD, ZDD >::garbageCollect(), tdzdd::DdReducer< ARITY, BDD, ZDD >::reduce_(), tdzdd::DdReducer< ARITY, BDD, ZDD >::reduceMP_(), and tdzdd::DdSweeper< AR >::update().
template<typename T, typename Size = size_t> const_iterator tdzdd::MyVector< T, Size >::begin () const inline
Gets a pointer to the first element.
Returns
pointer to the first element.
Definition at line 395 of file MyVector.hpp.
template<typename T, typename Size = size_t> Size tdzdd::MyVector< T, Size >::capacity () const inline
Gets the current capacity of the storage.
Returns
the storage capacity.
Definition at line 174 of file MyVector.hpp.
Referenced by tdzdd::MyVector< tdzdd::DdDumper::Hasher< Spec > >::reserve().
template<typename T, typename Size = size_t> void tdzdd::MyVector< T, Size >::clear () inline
Initializes the array to be empty.
The memory is deallocated.
Definition at line 290 of file MyVector.hpp.
Referenced by tdzdd::DdReducer< ARITY, BDD, ZDD >::algorithmR(), tdzdd::PathCounter< S >::count(), tdzdd::PathCounter< S >::count64(), tdzdd::PathCounter< S >::countFast(), tdzdd::NodeTableEntity< AR >::deleteIndex(), tdzdd::CardinalityBase< E, std::string, ARITY, BDD >::destructLevel(), tdzdd::DdDumper< S >::dump(), tdzdd::DdDumper< S >::dumpStep(), tdzdd::DataTable< tdzdd::MyListOnPool< SpecNode > >::init(), tdzdd::DdBuilder< S >::init(), tdzdd::DdBuilder< S >::initialize(), tdzdd::ZddSubsetter< S >::initialize(), tdzdd::DataTable< tdzdd::MyListOnPool< SpecNode > >::initRow(), tdzdd::NodeTableEntity< AR >::makeIndex(), tdzdd::DdReducer< ARITY, BDD, ZDD >::reduce_(), tdzdd::DdReducer< ARITY, BDD, ZDD >::reduceMP_(), tdzdd::MyVector< tdzdd::DdDumper::Hasher< Spec > >::resize(), tdzdd::ZddSubsetter< S >::subset(), tdzdd::ZddSubsetterMP< S >::subset(), tdzdd::DdBuilder< S >::~DdBuilder(), tdzdd::MyVector< tdzdd::DdDumper::Hasher< Spec > >::~MyVector(), and tdzdd::ZddSubsetter< S >::~ZddSubsetter().
template<typename T, typename Size = size_t> T* tdzdd::MyVector< T, Size >::data () const inline
Gets a pointer to the first element.
Returns
pointer to the first element.
Definition at line 376 of file MyVector.hpp.
Referenced by tdzdd::DdBuilderMP< S >::construct(), tdzdd::PathCounter< S >::count(), tdzdd::PathCounter< S >::count64(), tdzdd::PathCounter< S >::countFast(), tdzdd::DdDumper< S >::dumpStep(), tdzdd::DdBuilder< S >::initialize(), tdzdd::DdBuilderMP< S >::initialize(), tdzdd::ZddSubsetter< S >::initialize(), tdzdd::ZddSubsetterMP< S >::initialize(), tdzdd::ZddSubsetter< S >::subset(), and tdzdd::ZddSubsetterMP< S >::subset().
template<typename T, typename Size = size_t> static void tdzdd::MyVector< T, Size >::deallocate (T * p, Size n) inline static private
Definition at line 43 of file MyVector.hpp.
Referenced by tdzdd::MyVector< tdzdd::DdDumper::Hasher< Spec > >::clear(), tdzdd::MyVector< tdzdd::DdDumper::Hasher< Spec > >::deallocate(), tdzdd::MyVector< tdzdd::DdDumper::Hasher< Spec > >::reserve(), and tdzdd::MyVector< tdzdd::DdDumper::Hasher< Spec > >::resize().
template<typename T, typename Size = size_t> bool tdzdd::MyVector< T, Size >::empty () const inline
Checks emptiness.
Returns
true if empty.
Definition at line 190 of file MyVector.hpp.
Referenced by tdzdd::DdBuilder< S >::construct(), tdzdd::NodeTableEntity< AR >::higherLevels(), tdzdd::DdBuilder< S >::initialize(), tdzdd::ZddSubsetter< S >::initialize(), tdzdd::NodeTableEntity< AR >::lowerLevels(), tdzdd::ZddSubsetter< S >::subset(), tdzdd::DdBuilder< S >::~DdBuilder(), and tdzdd::ZddSubsetter< S >::~ZddSubsetter().
template<typename T, typename Size = size_t> iterator tdzdd::MyVector< T, Size >::end () inline
Gets a pointer to the end of elements.
Returns
pointer to the end of elements.
Definition at line 403 of file MyVector.hpp.
Referenced by tdzdd::DdReducer< ARITY, BDD, ZDD >::algorithmR(), tdzdd::DdStructure< ARITY >::dumpSapporo(), tdzdd::MyVector< tdzdd::DdDumper::Hasher< Spec > >::erase(), tdzdd::DdStructure< ARITY >::evaluate(), tdzdd::DdReducer< ARITY, BDD, ZDD >::garbageCollect(), tdzdd::DdReducer< ARITY, BDD, ZDD >::reduce_(), tdzdd::DdReducer< ARITY, BDD, ZDD >::reduceMP_(), and tdzdd::DdSweeper< AR >::update().
template<typename T, typename Size = size_t> const_iterator tdzdd::MyVector< T, Size >::end () const inline
Gets a pointer to the end of elements.
Returns
pointer to the end of elements.
Definition at line 411 of file MyVector.hpp.
template<typename T, typename Size = size_t> void tdzdd::MyVector< T, Size >::ensureCapacity (Size capacity) inline private
Definition at line 47 of file MyVector.hpp.
Referenced by tdzdd::MyVector< tdzdd::DdDumper::Hasher< Spec > >::push_back().
template<typename T, typename Size = size_t> T* tdzdd::MyVector< T, Size >::erase (T * first, T * last) inline
Erases elements.
Parameters
first pointer to the beginning.
last pointer to the end.
Returns
iterator following the last removed element.
Definition at line 271 of file MyVector.hpp.
template<typename T, typename Size = size_t> iterator tdzdd::MyVector< T, Size >::erase (iterator pos) inline
Removes an element.
Parameters
pos iterator to the element to remove.
Definition at line 485 of file MyVector.hpp.
template<typename T, typename Size = size_t> size_t tdzdd::MyVector< T, Size >::hash () const inline
Gets the hash code of this object.
Returns
the hash code.
Definition at line 495 of file MyVector.hpp.
template<typename T, typename Size = size_t> void tdzdd::MyVector< T, Size >::init (Size n) inline
Initializes the array.
Parameters
n new size.
Definition at line 218 of file MyVector.hpp.
Referenced by tdzdd::DdDumper< S >::dump().
template<typename T, typename Size = size_t> void tdzdd::MyVector< T, Size >::moveElement (T & from, T & to) inline private
Definition at line 54 of file MyVector.hpp.
Referenced by tdzdd::MyVector< tdzdd::DdDumper::Hasher< Spec > >::reserve(), and tdzdd::MyVector< tdzdd::DdDumper::Hasher< Spec > >::resize().
template<> void tdzdd::MyVector< MemoryPool >::moveElement (MemoryPool & from, MemoryPool & to) inline private
Definition at line 233 of file MemoryPool.hpp.
References tdzdd::MemoryPool::moveFrom().
template<typename T, typename Size = size_t> MyVector& tdzdd::MyVector< T, Size >::operator= (MyVector< T, Size > const & o) inline
Definition at line 97 of file MyVector.hpp.
template<typename T, typename Size = size_t> template<typename U > MyVector& tdzdd::MyVector< T, Size >::operator= (std::vector< U > const & o) inline
Definition at line 116 of file MyVector.hpp.
template<typename T, typename Size = size_t> bool tdzdd::MyVector< T, Size >::operator== (MyVector< T, Size > const & o) const inline
Checks equivalence between another object.
Parameters
o another object.
Returns
true if equivalent.
Definition at line 508 of file MyVector.hpp.
template<typename T, typename Size = size_t> T& tdzdd::MyVector< T, Size >::operator[] (Size i) inline
Accesses to the i-th element.
Parameters
i index of the element.
Returns
reference to the element.
Definition at line 357 of file MyVector.hpp.
template<typename T, typename Size = size_t> T const& tdzdd::MyVector< T, Size >::operator[] (Size i) const inline
Accesses to the i-th element.
Parameters
i index of the element.
Returns
reference to the element.
Definition at line 367 of file MyVector.hpp.
template<typename T, typename Size = size_t> void tdzdd::MyVector< T, Size >::pop_back () inline
Removes the last element.
Definition at line 317 of file MyVector.hpp.
Referenced by tdzdd::DdBuilder< S >::construct(), and tdzdd::ZddSubsetter< S >::subset().
template<typename T, typename Size = size_t> void tdzdd::MyVector< T, Size >::push_back (T const & val) inline
Adds an element to the end of the array.
The array is automatically extended, which may cause data move.
Parameters
val value of the new element.
Definition at line 308 of file MyVector.hpp.
Referenced by tdzdd::DataTable< tdzdd::MyListOnPool< SpecNode > >::addColumn(), tdzdd::DdBuilder< S >::construct(), tdzdd::PathCounter< S >::count(), tdzdd::PathCounter< S >::count64(), tdzdd::DdDumper< S >::dump(), tdzdd::DdReducer< ARITY, BDD, ZDD >::garbageCollect(), tdzdd::NodeTableEntity< AR >::makeIndex(), tdzdd::MyVector< tdzdd::DdDumper::Hasher< Spec > >::MyVector(), tdzdd::DdReducer< ARITY, BDD, ZDD >::setRoot(), and tdzdd::ZddSubsetter< S >::subset().
template<typename T, typename Size = size_t> reverse_iterator tdzdd::MyVector< T, Size >::rbegin () inline
Returns a reverse iterator to the beginning.
Returns
reverse iterator to the beginning.
Definition at line 453 of file MyVector.hpp.
template<typename T, typename Size = size_t> const_reverse_iterator tdzdd::MyVector< T, Size >::rbegin () const inline
Returns a reverse iterator to the beginning.
Returns
reverse iterator to the beginning.
Definition at line 461 of file MyVector.hpp.
template<typename T, typename Size = size_t> reverse_iterator tdzdd::MyVector< T, Size >::rend () inline
Returns a reverse iterator to the end.
Returns
reverse iterator to the end.
Definition at line 469 of file MyVector.hpp.
template<typename T, typename Size = size_t> const_reverse_iterator tdzdd::MyVector< T, Size >::rend () const inline
Returns a reverse iterator to the end.
Returns
reverse iterator to the end.
Definition at line 477 of file MyVector.hpp.
template<typename T, typename Size = size_t> void tdzdd::MyVector< T, Size >::reserve (Size capacity) inline
Reserves the memory.
Data is moved if the actual capacity is extended.
Parameters
capacity lower bound of the capacity.
Definition at line 199 of file MyVector.hpp.
Referenced by tdzdd::PathCounter< S >::count(), tdzdd::PathCounter< S >::count64(), tdzdd::DdDumper< S >::dump(), tdzdd::MyVector< tdzdd::DdDumper::Hasher< Spec > >::ensureCapacity(), tdzdd::DdReducer< ARITY, BDD, ZDD >::garbageCollect(), tdzdd::MyVector< tdzdd::DdDumper::Hasher< Spec > >::MyVector(), and tdzdd::MyVector< tdzdd::DdDumper::Hasher< Spec > >::operator=().
template<typename T, typename Size = size_t> void tdzdd::MyVector< T, Size >::resize (Size n) inline
Resizes the array.
Data may be moved unless new size is the same as capacity.
Parameters
n new size.
Definition at line 230 of file MyVector.hpp.
Referenced by tdzdd::DdReducer< ARITY, BDD, ZDD >::algorithmR(), tdzdd::DdReducer< ARITY, BDD, ZDD >::DdReducer(), tdzdd::DdReducer< ARITY, BDD, ZDD >::garbageCollect(), tdzdd::DataTable< tdzdd::MyListOnPool< SpecNode > >::init(), tdzdd::DdBuilder< S >::init(), tdzdd::MyVector< tdzdd::DdDumper::Hasher< Spec > >::init(), tdzdd::DdBuilderMP< S >::init(), tdzdd::CardinalityBase< E, std::string, ARITY, BDD >::initialize(), tdzdd::ZddSubsetter< S >::initialize(), tdzdd::ZddSubsetterMP< S >::initialize(), tdzdd::DataTable< tdzdd::MyListOnPool< SpecNode > >::initRow(), tdzdd::NodeTableEntity< AR >::initTerminals(), tdzdd::NodeTableEntity< AR >::makeIndex(), tdzdd::MyVector< tdzdd::DdDumper::Hasher< Spec > >::MyVector(), tdzdd::MyVector< tdzdd::DdDumper::Hasher< Spec > >::operator=(), tdzdd::DdReducer< ARITY, BDD, ZDD >::reduce_(), tdzdd::DdReducer< ARITY, BDD, ZDD >::reduceMP_(), tdzdd::DataTable< tdzdd::MyListOnPool< SpecNode > >::setNumRows(), tdzdd::ZddSubsetterMP< S >::subset(), and tdzdd::DdSweeper< AR >::update().
template<typename T, typename Size = size_t> Size tdzdd::MyVector< T, Size >::size () const inline
Gets the number of elements.
Returns
the number of elements.
Definition at line 182 of file MyVector.hpp.
Referenced by tdzdd::DataTable< tdzdd::MyListOnPool< SpecNode > >::addColumn(), tdzdd::DdReducer< ARITY, BDD, ZDD >::algorithmR(), tdzdd::DdBuilder< S >::construct(), tdzdd::DdBuilderMP< S >::construct(), tdzdd::DdDumper< S >::dumpStep(), tdzdd::CardinalityBase< E, std::string, ARITY, BDD >::evalNode(), tdzdd::DdStructure< ARITY >::evaluate(), tdzdd::DdReducer< ARITY, BDD, ZDD >::garbageCollect(), tdzdd::NodeTableEntity< AR >::makeIndex(), tdzdd::DataTable< tdzdd::MyListOnPool< SpecNode > >::numRows(), tdzdd::DdReducer< ARITY, BDD, ZDD >::reduce_(), tdzdd::DdReducer< ARITY, BDD, ZDD >::reduceMP_(), tdzdd::ZddSubsetter< S >::subset(), tdzdd::DataTable< tdzdd::MyListOnPool< SpecNode > >::totalSize(), and tdzdd::DdSweeper< AR >::update().
template<typename T, typename Size = size_t> void tdzdd::MyVector< T, Size >::swap (MyVector< T, Size > & o) inline
Definition at line 160 of file MyVector.hpp.
Friends And Related Function Documentation
template<typename T, typename Size = size_t> std::ostream& operator<< (std::ostream & os, MyVector< T, Size > const & o) friend
Sends an object to an output stream.
Parameters
os the output stream.
o the object.
Returns
os.
Definition at line 522 of file MyVector.hpp.
Member Data Documentation
template<typename T, typename Size = size_t> T* tdzdd::MyVector< T, Size >::array_ private
Start address of the array.
Definition at line 37 of file MyVector.hpp.
Referenced by tdzdd::MyVector< tdzdd::DdDumper::Hasher< Spec > >::begin(), tdzdd::MyVector< tdzdd::DdDumper::Hasher< Spec > >::data(), tdzdd::MyVector< tdzdd::DdDumper::Hasher< Spec > >::operator==(), and tdzdd::MyVector< tdzdd::DdDumper::Hasher< Spec > >::swap().
template<typename T, typename Size = size_t> Size tdzdd::MyVector< T, Size >::capacity_ private
Size of the array.
Definition at line 35 of file MyVector.hpp.
Referenced by tdzdd::MyVector< tdzdd::DdDumper::Hasher< Spec > >::capacity(), and tdzdd::MyVector< tdzdd::DdDumper::Hasher< Spec > >::swap().
template<typename T, typename Size = size_t> Size tdzdd::MyVector< T, Size >::size_ private
Current number of elements.
Definition at line 36 of file MyVector.hpp.
Referenced by tdzdd::MyVector< tdzdd::DdDumper::Hasher< Spec > >::clear(), tdzdd::MyVector< tdzdd::DdDumper::Hasher< Spec > >::end(), tdzdd::MyVector< tdzdd::DdDumper::Hasher< Spec > >::erase(), tdzdd::MyVector< tdzdd::DdDumper::Hasher< Spec > >::hash(), tdzdd::MyVector< tdzdd::DdDumper::Hasher< Spec > >::init(), tdzdd::MyVector< tdzdd::DdDumper::Hasher< Spec > >::MyVector(), tdzdd::MyVector< tdzdd::DdDumper::Hasher< Spec > >::operator=(), tdzdd::MyVector< tdzdd::DdDumper::Hasher< Spec > >::operator==(), tdzdd::MyVector< tdzdd::DdDumper::Hasher< Spec > >::pop_back(), tdzdd::MyVector< tdzdd::DdDumper::Hasher< Spec > >::push_back(), tdzdd::MyVector< tdzdd::DdDumper::Hasher< Spec > >::reserve(), tdzdd::MyVector< tdzdd::DdDumper::Hasher< Spec > >::resize(), tdzdd::MyVector< tdzdd::DdDumper::Hasher< Spec > >::size(), and tdzdd::MyVector< tdzdd::DdDumper::Hasher< Spec > >::swap().
The documentation for this class was generated from the following file:
include/tdzdd/util/MyVector.hpp