TdZdd: tdzdd::ElapsedTimeCounter Class Reference
tdzdd::ElapsedTimeCounter Class Reference
#include <ResourceUsage.hpp>
Public Member Functions
ElapsedTimeCounter ()
ElapsedTimeCounter & reset ()
ElapsedTimeCounter & start ()
ElapsedTimeCounter & stop ()
operator double () const
Private Attributes
double totalTime
double startTime
Friends
std::ostream & operator<< (std::ostream &os, ElapsedTimeCounter const &o)
Detailed Description
Definition at line 159 of file ResourceUsage.hpp.
Constructor & Destructor Documentation
tdzdd::ElapsedTimeCounter::ElapsedTimeCounter () inline
Definition at line 164 of file ResourceUsage.hpp.
Member Function Documentation
tdzdd::ElapsedTimeCounter::operator double () const inline
Definition at line 183 of file ResourceUsage.hpp.
ElapsedTimeCounter& tdzdd::ElapsedTimeCounter::reset () inline
Definition at line 168 of file ResourceUsage.hpp.
ElapsedTimeCounter& tdzdd::ElapsedTimeCounter::start () inline
Definition at line 173 of file ResourceUsage.hpp.
References tdzdd::getWallClockTime().
Referenced by tdzdd::DdBuilderMP< S >::construct(), tdzdd::DdReducer< ARITY, BDD, ZDD >::DdReducer(), and tdzdd::DdReducer< ARITY, BDD, ZDD >::reduceMP_().
ElapsedTimeCounter& tdzdd::ElapsedTimeCounter::stop () inline
Definition at line 178 of file ResourceUsage.hpp.
References tdzdd::getWallClockTime().
Referenced by tdzdd::DdBuilderMP< S >::construct(), tdzdd::DdReducer< ARITY, BDD, ZDD >::DdReducer(), and tdzdd::DdReducer< ARITY, BDD, ZDD >::reduceMP_().
Friends And Related Function Documentation
std::ostream& operator<< (std::ostream & os, ElapsedTimeCounter const & o) friend
Definition at line 187 of file ResourceUsage.hpp.
Member Data Documentation
double tdzdd::ElapsedTimeCounter::startTime private
Definition at line 161 of file ResourceUsage.hpp.
double tdzdd::ElapsedTimeCounter::totalTime private
Definition at line 160 of file ResourceUsage.hpp.
The documentation for this class was generated from the following file:
include/tdzdd/util/ResourceUsage.hpp