TdZdd: tdzdd::MyList< T, BLOCK_ELEMENTS > Class Template Reference
tdzdd::MyList< T, BLOCK_ELEMENTS > Class Template Reference
#include <MyList.hpp>
Classes
struct Cell
class const_iterator
class iterator
Public Member Functions
MyList ()
MyList (MyList const &o)
MyList & operator= (MyList const &o)
virtual ~MyList ()
size_t size () const
Returns the number of elements.
bool empty () const
Checks emptiness.
void clear ()
Initializes the array to be empty.
T * front ()
Accesses the first element.
T const * front () const
Accesses the first element.
T * alloc_front (size_t numElements=1)
Allocates a contiguous memory block for one or more new elements at the beginning.
void pop_front ()
Removes a memory block at the beginning.
iterator begin ()
Returns an iterator to the beginning.
const_iterator begin () const
Returns an iterator to the beginning.
iterator end ()
Returns an iterator to the end.
const_iterator end () const
Returns an iterator to the end.
Static Private Member Functions
static size_t numCells (size_t n)
static Cell * setFlag (Cell *p)
static Cell * clearFlag (Cell *p)
static bool flagged (Cell *p)
static Cell *& blockStart (Cell *p)
static T * dataStart (Cell *p)
Private Attributes
Cell * front_
size_t size_
Static Private Attributes
static int const headerCells = 1
Friends
std::ostream & operator<< (std::ostream &os, MyList const &o)
Get the hash code of this object.
Detailed Description
template<typename T, size_t BLOCK_ELEMENTS = 1000>
class tdzdd::MyList< T, BLOCK_ELEMENTS >
Definition at line 34 of file MyList.hpp.
Constructor & Destructor Documentation
template<typename T, size_t BLOCK_ELEMENTS = 1000> tdzdd::MyList< T, BLOCK_ELEMENTS >::MyList () inline
Definition at line 70 of file MyList.hpp.
template<typename T, size_t BLOCK_ELEMENTS = 1000> tdzdd::MyList< T, BLOCK_ELEMENTS >::MyList (MyList< T, BLOCK_ELEMENTS > const & o) inline
Definition at line 74 of file MyList.hpp.
template<typename T, size_t BLOCK_ELEMENTS = 1000> virtual tdzdd::MyList< T, BLOCK_ELEMENTS >::~MyList () inline virtual
Definition at line 97 of file MyList.hpp.
Member Function Documentation
template<typename T, size_t BLOCK_ELEMENTS = 1000> T* tdzdd::MyList< T, BLOCK_ELEMENTS >::alloc_front (size_t numElements = 1) inline
Allocates a contiguous memory block for one or more new elements at the beginning.
The memory block is not initialized.
Parameters
numElements the number of elements.
Returns
pointer to the memory block.
Definition at line 159 of file MyList.hpp.
Referenced by tdzdd::PathCounter< S >::count(), tdzdd::PathCounter< S >::count64(), tdzdd::PathCounter< S >::countFast(), tdzdd::DepthFirstSearcher< S >::findOneInstance(), and tdzdd::DepthFirstSearcher< S >::findOneInstanceStep().
template<typename T, size_t BLOCK_ELEMENTS = 1000> iterator tdzdd::MyList< T, BLOCK_ELEMENTS >::begin () inline
Returns an iterator to the beginning.
Returns
iterator to the beginning.
Definition at line 263 of file MyList.hpp.
Referenced by tdzdd::DdBuilder< S >::construct(), tdzdd::DdBuilderMP< S >::construct(), tdzdd::PathCounter< S >::countFast(), and tdzdd::DdReducer< ARITY, BDD, ZDD >::reduceMP_().
template<typename T, size_t BLOCK_ELEMENTS = 1000> const_iterator tdzdd::MyList< T, BLOCK_ELEMENTS >::begin () const inline
Returns an iterator to the beginning.
Returns
iterator to the beginning.
Definition at line 271 of file MyList.hpp.
template<typename T, size_t BLOCK_ELEMENTS = 1000> static Cell*& tdzdd::MyList< T, BLOCK_ELEMENTS >::blockStart (Cell * p) inline static private
Definition at line 61 of file MyList.hpp.
Referenced by tdzdd::MyList< char >::alloc_front(), tdzdd::MyList< char >::clear(), and tdzdd::MyList< char >::pop_front().
template<typename T, size_t BLOCK_ELEMENTS = 1000> void tdzdd::MyList< T, BLOCK_ELEMENTS >::clear () inline
Initializes the array to be empty.
The memory is deallocated.
Definition at line 122 of file MyList.hpp.
Referenced by tdzdd::MyList< char >::operator=(), tdzdd::MyList< char >::~MyList(), and tdzdd::MyListOnPool< T >::~MyListOnPool().
template<typename T, size_t BLOCK_ELEMENTS = 1000> static Cell* tdzdd::MyList< T, BLOCK_ELEMENTS >::clearFlag (Cell * p) inline static private
Definition at line 52 of file MyList.hpp.
Referenced by tdzdd::MyList< char >::clear(), tdzdd::MyList< T, BLOCK_ELEMENTS >::iterator::operator++(), tdzdd::MyList< T, BLOCK_ELEMENTS >::const_iterator::operator++(), and tdzdd::MyList< char >::pop_front().
template<typename T, size_t BLOCK_ELEMENTS = 1000> static T* tdzdd::MyList< T, BLOCK_ELEMENTS >::dataStart (Cell * p) inline static private
Definition at line 65 of file MyList.hpp.
Referenced by tdzdd::MyList< char >::alloc_front(), tdzdd::MyListOnPool< T >::alloc_front(), tdzdd::MyList< char >::front(), tdzdd::MyListOnPool< T >::front(), tdzdd::MyList< T, BLOCK_ELEMENTS >::iterator::operator*(), tdzdd::MyList< T, BLOCK_ELEMENTS >::const_iterator::operator*(), tdzdd::MyListOnPool< T >::iterator::operator*(), tdzdd::MyListOnPool< T >::const_iterator::operator*(), tdzdd::MyList< T, BLOCK_ELEMENTS >::iterator::operator->(), and tdzdd::MyList< T, BLOCK_ELEMENTS >::const_iterator::operator->().
template<typename T, size_t BLOCK_ELEMENTS = 1000> bool tdzdd::MyList< T, BLOCK_ELEMENTS >::empty () const inline
Checks emptiness.
Returns
true if empty.
Definition at line 113 of file MyList.hpp.
Referenced by tdzdd::DdBuilderMP< S >::construct(), tdzdd::PathCounter< S >::count(), tdzdd::PathCounter< S >::count64(), tdzdd::PathCounter< S >::countFast(), and tdzdd::DdDumper< S >::dumpStep().
template<typename T, size_t BLOCK_ELEMENTS = 1000> iterator tdzdd::MyList< T, BLOCK_ELEMENTS >::end () inline
Returns an iterator to the end.
Returns
iterator to the end.
Definition at line 279 of file MyList.hpp.
Referenced by tdzdd::DdBuilderMP< S >::construct(), tdzdd::PathCounter< S >::countFast(), and tdzdd::DdReducer< ARITY, BDD, ZDD >::reduceMP_().
template<typename T, size_t BLOCK_ELEMENTS = 1000> const_iterator tdzdd::MyList< T, BLOCK_ELEMENTS >::end () const inline
Returns an iterator to the end.
Returns
iterator to the end.
Definition at line 287 of file MyList.hpp.
template<typename T, size_t BLOCK_ELEMENTS = 1000> static bool tdzdd::MyList< T, BLOCK_ELEMENTS >::flagged (Cell * p) inline static private
Definition at line 57 of file MyList.hpp.
Referenced by tdzdd::MyList< char >::clear(), and tdzdd::MyList< char >::pop_front().
template<typename T, size_t BLOCK_ELEMENTS = 1000> T* tdzdd::MyList< T, BLOCK_ELEMENTS >::front () inline
Accesses the first element.
Returns
pointer to the first element.
Definition at line 140 of file MyList.hpp.
Referenced by tdzdd::DdBuilderMP< S >::construct(), tdzdd::PathCounter< S >::count(), tdzdd::PathCounter< S >::count64(), tdzdd::PathCounter< S >::countFast(), and tdzdd::DdDumper< S >::dumpStep().
template<typename T, size_t BLOCK_ELEMENTS = 1000> T const* tdzdd::MyList< T, BLOCK_ELEMENTS >::front () const inline
Accesses the first element.
Returns
pointer to the first element.
Definition at line 148 of file MyList.hpp.
template<typename T, size_t BLOCK_ELEMENTS = 1000> static size_t tdzdd::MyList< T, BLOCK_ELEMENTS >::numCells (size_t n) inline static private
Definition at line 44 of file MyList.hpp.
Referenced by tdzdd::MyList< char >::alloc_front().
template<typename T, size_t BLOCK_ELEMENTS = 1000> MyList& tdzdd::MyList< T, BLOCK_ELEMENTS >::operator= (MyList< T, BLOCK_ELEMENTS > const & o) inline
Definition at line 80 of file MyList.hpp.
template<typename T, size_t BLOCK_ELEMENTS = 1000> void tdzdd::MyList< T, BLOCK_ELEMENTS >::pop_front () inline
Removes a memory block at the beginning.
Definition at line 184 of file MyList.hpp.
Referenced by tdzdd::DdBuilderMP< S >::construct(), tdzdd::PathCounter< S >::count(), tdzdd::PathCounter< S >::count64(), tdzdd::PathCounter< S >::countFast(), tdzdd::DdDumper< S >::dumpStep(), tdzdd::DepthFirstSearcher< S >::findOneInstance(), and tdzdd::DepthFirstSearcher< S >::findOneInstanceStep().
template<typename T, size_t BLOCK_ELEMENTS = 1000> static Cell* tdzdd::MyList< T, BLOCK_ELEMENTS >::setFlag (Cell * p) inline static private
Definition at line 48 of file MyList.hpp.
Referenced by tdzdd::MyList< char >::alloc_front().
template<typename T, size_t BLOCK_ELEMENTS = 1000> size_t tdzdd::MyList< T, BLOCK_ELEMENTS >::size () const inline
Returns the number of elements.
Returns
the number of elements.
Definition at line 105 of file MyList.hpp.
Referenced by tdzdd::PathCounter< S >::count(), tdzdd::PathCounter< S >::count64(), tdzdd::PathCounter< S >::countFast(), and tdzdd::DdDumper< S >::dumpStep().
Friends And Related Function Documentation
template<typename T, size_t BLOCK_ELEMENTS = 1000> std::ostream& operator<< (std::ostream & os, MyList< T, BLOCK_ELEMENTS > const & o) friend
Get the hash code of this object.
Returns
the hash code. Check equivalence between another object.
Parameters
o another object.
Returns
true if equivalent. Sends an object to an output stream.
Parameters
os the output stream.
o the object.
Returns
os.
Definition at line 322 of file MyList.hpp.
Member Data Documentation
template<typename T, size_t BLOCK_ELEMENTS = 1000> Cell* tdzdd::MyList< T, BLOCK_ELEMENTS >::front_ private
Definition at line 41 of file MyList.hpp.
Referenced by tdzdd::MyList< char >::alloc_front(), tdzdd::MyListOnPool< T >::alloc_front(), and tdzdd::MyList< char >::clear().
template<typename T, size_t BLOCK_ELEMENTS = 1000> int const tdzdd::MyList< T, BLOCK_ELEMENTS >::headerCells = 1 static private
Definition at line 35 of file MyList.hpp.
template<typename T, size_t BLOCK_ELEMENTS = 1000> size_t tdzdd::MyList< T, BLOCK_ELEMENTS >::size_ private
Definition at line 42 of file MyList.hpp.
Referenced by tdzdd::MyList< char >::alloc_front(), tdzdd::MyListOnPool< T >::alloc_front(), tdzdd::MyList< char >::MyList(), tdzdd::MyList< char >::operator=(), tdzdd::MyList< char >::pop_front(), tdzdd::MyListOnPool< T >::pop_front(), tdzdd::MyList< char >::size(), and tdzdd::MyListOnPool< T >::size().
The documentation for this class was generated from the following file:
include/tdzdd/util/MyList.hpp