TdZdd: tdzdd::NodeId Class Reference
tdzdd::NodeId Class Reference
#include <Node.hpp>
Public Member Functions
NodeId ()
NodeId (uint64_t code)
NodeId (uint64_t row, uint64_t col)
NodeId (uint64_t row, uint64_t col, bool attr)
int row () const
size_t col () const
void setAttr (bool val)
bool getAttr () const
NodeId withoutAttr () const
bool hasEmpty () const
uint64_t code () const
size_t hash () const
bool operator== (NodeId const &o) const
bool operator!= (NodeId const &o) const
bool operator< (NodeId const &o) const
bool operator>= (NodeId const &o) const
bool operator> (NodeId const &o) const
bool operator<= (NodeId const &o) const
Private Attributes
uint64_t code_
Friends
std::ostream & operator<< (std::ostream &os, NodeId const &o)
Detailed Description
Definition at line 46 of file Node.hpp.
Constructor & Destructor Documentation
tdzdd::NodeId::NodeId () inline
Definition at line 50 of file Node.hpp.
tdzdd::NodeId::NodeId (uint64_t code) inline
Definition at line 53 of file Node.hpp.
tdzdd::NodeId::NodeId (uint64_t row, uint64_t col) inline
Definition at line 57 of file Node.hpp.
tdzdd::NodeId::NodeId (uint64_t row, uint64_t col, bool attr) inline
Definition at line 61 of file Node.hpp.
References setAttr().
Member Function Documentation
uint64_t tdzdd::NodeId::code () const inline
Definition at line 95 of file Node.hpp.
Referenced by tdzdd::DdDumper< S >::dump(), tdzdd::DdDumper< S >::dumpStep(), hash(), tdzdd::Node< ARITY >::hash(), operator<(), and operator==().
size_t tdzdd::NodeId::col () const inline
Definition at line 70 of file Node.hpp.
References tdzdd::NODE_COL_MAX.
Referenced by tdzdd::DdReducer< ARITY, BDD, ZDD >::algorithmR(), tdzdd::NodeTableEntity< AR >::child(), tdzdd::DdStructure< ARITY >::dumpSapporo(), tdzdd::DdStructure< ARITY >::evaluate(), tdzdd::DdStructure< ARITY >::getChild(), tdzdd::ZddSubsetter< S >::initialize(), tdzdd::ZddSubsetterMP< S >::initialize(), tdzdd::DdStructure< ARITY >::const_iterator::next(), tdzdd::NodeTableEntity< AR >::node(), tdzdd::DdStructure< ARITY >::operator==(), tdzdd::DdReducer< ARITY, BDD, ZDD >::reduce_(), tdzdd::DdReducer< ARITY, BDD, ZDD >::reduceMP_(), tdzdd::NodeTableEntity< AR >::stretchBottom(), tdzdd::ZddSubsetter< S >::subset(), tdzdd::ZddSubsetterMP< S >::subset(), and tdzdd::DdSweeper< AR >::update().
bool tdzdd::NodeId::getAttr () const inline
Definition at line 83 of file Node.hpp.
Referenced by tdzdd::NodeTableEntity< AR >::dumpDot(), tdzdd::DdReducer< ARITY, BDD, ZDD >::garbageCollect(), hasEmpty(), and tdzdd::DdReducer< ARITY, BDD, ZDD >::reduceMP_().
bool tdzdd::NodeId::hasEmpty () const inline
Definition at line 91 of file Node.hpp.
References getAttr().
Referenced by tdzdd::DdReducer< ARITY, BDD, ZDD >::algorithmR(), tdzdd::NodeTableEntity< AR >::getZeroDescendant(), and tdzdd::DdReducer< ARITY, BDD, ZDD >::reduce_().
size_t tdzdd::NodeId::hash () const inline
Definition at line 99 of file Node.hpp.
References code().
Referenced by tdzdd::DdStructure< ARITY >::hashCode().
bool tdzdd::NodeId::operator!= (NodeId const & o) const inline
Definition at line 107 of file Node.hpp.
bool tdzdd::NodeId::operator< (NodeId const & o) const inline
Definition at line 111 of file Node.hpp.
References code().
bool tdzdd::NodeId::operator<= (NodeId const & o) const inline
Definition at line 123 of file Node.hpp.
bool tdzdd::NodeId::operator== (NodeId const & o) const inline
Definition at line 103 of file Node.hpp.
References code().
Referenced by tdzdd::Node< ARITY >::operator!=().
bool tdzdd::NodeId::operator> (NodeId const & o) const inline
Definition at line 119 of file Node.hpp.
bool tdzdd::NodeId::operator>= (NodeId const & o) const inline
Definition at line 115 of file Node.hpp.
int tdzdd::NodeId::row () const inline
Definition at line 66 of file Node.hpp.
References tdzdd::NODE_ROW_OFFSET.
Referenced by tdzdd::DdReducer< ARITY, BDD, ZDD >::algorithmR(), tdzdd::NodeTableEntity< AR >::child(), tdzdd::ZddSubsetter< S >::downTable(), tdzdd::ZddSubsetterMP< S >::downTable(), tdzdd::DdStructure< ARITY >::dumpSapporo(), tdzdd::DdStructure< ARITY >::evaluate(), tdzdd::DdStructure< ARITY >::getChild(), tdzdd::DdStructure< ARITY >::getRoot(), tdzdd::NodeTableEntity< AR >::getZeroDescendant(), tdzdd::ZddSubsetter< S >::initialize(), tdzdd::ZddSubsetterMP< S >::initialize(), tdzdd::DdReducer< ARITY, BDD, ZDD >::makeReadyForSequentialReduction(), tdzdd::DdStructure< ARITY >::const_iterator::next(), tdzdd::NodeTableEntity< AR >::node(), tdzdd::DdStructure< ARITY >::operator==(), tdzdd::DdStructure< ARITY >::reduce(), tdzdd::DdReducer< ARITY, BDD, ZDD >::reduce_(), tdzdd::DdReducer< ARITY, BDD, ZDD >::reduceMP_(), tdzdd::DdReducer< ARITY, BDD, ZDD >::setRoot(), tdzdd::NodeTableEntity< AR >::stretchBottom(), tdzdd::ZddSubsetter< S >::subset(), tdzdd::ZddSubsetterMP< S >::subset(), tdzdd::DdStructure< ARITY >::topLevel(), and tdzdd::DdSweeper< AR >::update().
void tdzdd::NodeId::setAttr (bool val) inline
Definition at line 74 of file Node.hpp.
References tdzdd::NODE_ATTR_MASK.
Referenced by tdzdd::NodeTableEntity< AR >::dumpDot(), and NodeId().
NodeId tdzdd::NodeId::withoutAttr () const inline
Definition at line 87 of file Node.hpp.
Friends And Related Function Documentation
std::ostream& operator<< (std::ostream & os, NodeId const & o) friend
Definition at line 127 of file Node.hpp.
Member Data Documentation
uint64_t tdzdd::NodeId::code_ private
Definition at line 47 of file Node.hpp.
The documentation for this class was generated from the following file:
include/tdzdd/dd/Node.hpp