TdZdd: tdzdd::DdStructure< ARITY > Class Template Reference
tdzdd::DdStructure< ARITY > Class Template Reference
Ordered n-ary decision diagram structure.
#include <DdStructure.hpp>
Classes
class const_iterator
Iterator on a set of integer vectors represented by a DD.
Public Member Functions
DdStructure ()
Default constructor.
DdStructure (int n, bool useMP=false)
Universal ZDD constructor.
template<typename SPEC >
DdStructure (DdSpecBase< SPEC, ARITY > const &spec, bool useMP=false)
DD construction.
template<typename SPEC >
void zddSubset (DdSpecBase< SPEC, ARITY > const &spec)
ZDD subsetting.
bool useMultiProcessors (bool flag=true)
Enables or disables multiple processor algorithms.
NodeId & root ()
Gets the root node.
NodeId root () const
Gets the root node.
NodeId child (NodeId f, int b) const
Gets a child node.
NodeTableHandler< ARITY > & getDiagram ()
Gets the diagram.
NodeTableHandler< ARITY > const & getDiagram () const
Gets the diagram.
int topLevel () const
Gets the level of the root node.
size_t size () const
Gets the number of nonterminal nodes.
bool empty () const
Checks if DD is a 0-terminal only.
bool operator== (DdStructure const &o) const
Checks structural equivalence with another DD.
bool operator!= (DdStructure const &o) const
Checks structural inequivalence with another DD.
void qddReduce ()
QDD reduction.
void bddReduce ()
BDD reduction.
void zddReduce ()
ZDD reduction.
template<bool BDD, bool ZDD>
void reduce ()
BDD/ZDD reduction.
DdStructure bdd2zdd (int numVars) const
Transforms a BDD into a ZDD.
DdStructure zdd2bdd (int numVars) const
Transforms a ZDD into a BDD.
std::string bddCardinality (int numVars) const
Counts the number of minterms of the function represented by this BDD.
std::string zddCardinality () const
Counts the number of sets in the family of sets represented by this ZDD.
template<typename S , typename T , typename R >
R evaluate (DdEval< S, T, R > const &evaluator) const
Evaluates the DD from the bottom to the top.
const_iterator begin () const
Returns an iterator to the first instance, which is viewed as a collection of item numbers.
const_iterator end () const
Returns an iterator to the element following the last instance.
int getRoot (NodeId &f) const
Implements DdSpec.
int getChild (NodeId &f, int level, int value) const
Implements DdSpec.
size_t hashCode (NodeId const &f) const
Implements DdSpec.
void dumpSapporo (std::ostream &os) const
Dumps the node table in Sapporo ZDD format.
Public Member Functions inherited from tdzdd::DdSpec< DdStructure< ARITY >, NodeId, ARITY >
int datasize () const
void construct (void *p)
int get_root (void *p)
int get_child (void *p, int level, int value)
void getCopy (void *p, State const &s)
void get_copy (void *to, void const *from)
int mergeStates (State &s1, State &s2)
int merge_states (void *p1, void *p2)
void destruct (void *p)
void destructLevel (int level)
size_t hashCode (State const &s) const
size_t hashCodeAtLevel (State const &s, int level) const
size_t hash_code (void const *p, int level) const
bool equalTo (State const &s1, State const &s2) const
bool equalToAtLevel (State const &s1, State const &s2, int level) const
bool equal_to (void const *p, void const *q, int level) const
void printState (std::ostream &os, State const &s) const
void printStateAtLevel (std::ostream &os, State const &s, int level) const
void print_state (std::ostream &os, void const *p, int level) const
Public Member Functions inherited from tdzdd::DdSpecBase< DdStructure< ARITY >, AR >
DdStructure< ARITY > & entity ()
DdStructure< ARITY >const & entity () const
void printLevel (std::ostream &os, int level) const
std::vector< std::pair< int, int > > findOneInstance () const
Returns a random instance using simple depth-first search without caching.
void dumpDot (std::ostream &os=std::cout, std::string title=typenameof< DdStructure< ARITY > >()) const
Dumps the node table in Graphviz (dot) format.
Private Member Functions
template<typename SPEC >
void construct_ (SPEC const &spec)
template<typename SPEC >
void constructMP_ (SPEC const &spec)
template<typename SPEC >
void zddSubset_ (SPEC const &spec)
template<typename SPEC >
void zddSubsetMP_ (SPEC const &spec)
Private Attributes
NodeTableHandler< ARITY > diagram
The diagram structure.
NodeId root_
Root node ID.
bool useMP
Flag to use MP algorithms.
Additional Inherited Members
Public Types inherited from tdzdd::DdSpec< DdStructure< ARITY >, NodeId, ARITY >
typedef NodeId State
Static Public Attributes inherited from tdzdd::DdSpecBase< DdStructure< ARITY >, AR >
static int const ARITY
Static Protected Member Functions inherited from tdzdd::DdSpecBase< DdStructure< ARITY >, AR >
static size_t rawHashCode (T const &o)
static size_t rawEqualTo (T const &o1, T const &o2)
Detailed Description
template<int ARITY>
class tdzdd::DdStructure< ARITY >
Ordered n-ary decision diagram structure.
Template Parameters
ARITY arity of the nodes.
Definition at line 56 of file DdStructure.hpp.
Constructor & Destructor Documentation
template<int ARITY> tdzdd::DdStructure< ARITY >::DdStructure () inline
Default constructor.
Definition at line 65 of file DdStructure.hpp.
Referenced by tdzdd::DdStructure< ARITY >::bdd2zdd(), and tdzdd::DdStructure< ARITY >::zdd2bdd().
template<int ARITY> tdzdd::DdStructure< ARITY >::DdStructure (int n, bool useMP = false) inline
Universal ZDD constructor.
Parameters
n the number of variables.
useMP use algorithms for multiple processors.
Definition at line 82 of file DdStructure.hpp.
References tdzdd::DdSpecBase< DdStructure< ARITY >, AR >::ARITY, tdzdd::DataTable< Node< ARITY > >::initRow(), and tdzdd::NodeTableHandler< ARITY >::privateEntity().
template<int ARITY> template<typename SPEC > tdzdd::DdStructure< ARITY >::DdStructure (DdSpecBase< SPEC, ARITY > const & spec, bool useMP = false) inline
DD construction.
Parameters
spec DD spec.
useMP use algorithms for multiple processors.
Definition at line 105 of file DdStructure.hpp.
References tdzdd::DdStructure< ARITY >::construct_(), tdzdd::DdStructure< ARITY >::constructMP_(), and tdzdd::DdSpecBase< S, AR >::entity().
Member Function Documentation
template<int ARITY> DdStructure tdzdd::DdStructure< ARITY >::bdd2zdd (int numVars) const inline
Transforms a BDD into a ZDD.
Parameters
numVars the number of variables.
Definition at line 416 of file DdStructure.hpp.
References tdzdd::DdStructure< ARITY >::DdStructure().
template<int ARITY> std::string tdzdd::DdStructure< ARITY >::bddCardinality (int numVars) const inline
Counts the number of minterms of the function represented by this BDD.
Parameters
numVars the number of input variables of the function.
Returns
the number of itemsets.
Definition at line 437 of file DdStructure.hpp.
References tdzdd::DdStructure< ARITY >::evaluate().
template<int ARITY> void tdzdd::DdStructure< ARITY >::bddReduce () inline
BDD reduction.
The node of which two edges points to the identical node is deleted.
Definition at line 372 of file DdStructure.hpp.
template<int ARITY> const_iterator tdzdd::DdStructure< ARITY >::begin () const inline
Returns an iterator to the first instance, which is viewed as a collection of item numbers.
Supports binary ZDDs only.
Returns
iterator to the first instance.
Definition at line 659 of file DdStructure.hpp.
References tdzdd::DdStructure< ARITY >::const_iterator::const_iterator().
template<int ARITY> NodeId tdzdd::DdStructure< ARITY >::child (NodeId f, int b) const inline
Gets a child node.
Parameters
f parent node ID.
b branch number.
Returns
child node ID.
Definition at line 260 of file DdStructure.hpp.
Referenced by tdzdd::DdStructure< ARITY >::getChild().
template<int ARITY> template<typename SPEC > void tdzdd::DdStructure< ARITY >::construct_ (SPEC const & spec) inline private
Definition at line 116 of file DdStructure.hpp.
References tdzdd::MessageHandler_< os >::begin(), tdzdd::DdBuilder< S >::construct(), tdzdd::MessageHandler_< os >::end(), tdzdd::DdBuilder< S >::initialize(), tdzdd::MessageHandler_< os >::setSteps(), tdzdd::DdStructure< ARITY >::size(), tdzdd::MessageHandler_< os >::step(), and tdzdd::typenameof().
Referenced by tdzdd::DdStructure< ARITY >::DdStructure().
template<int ARITY> template<typename SPEC > void tdzdd::DdStructure< ARITY >::constructMP_ (SPEC const & spec) inline private
Definition at line 137 of file DdStructure.hpp.
References tdzdd::MessageHandler_< os >::begin(), tdzdd::DdBuilderMP< S >::construct(), tdzdd::MessageHandler_< os >::end(), tdzdd::DdBuilderMP< S >::initialize(), tdzdd::MessageHandler_< os >::setSteps(), tdzdd::DdStructure< ARITY >::size(), tdzdd::MessageHandler_< os >::step(), and tdzdd::typenameof().
Referenced by tdzdd::DdStructure< ARITY >::DdStructure().
template<int ARITY> void tdzdd::DdStructure< ARITY >::dumpSapporo (std::ostream & os) const inline
Dumps the node table in Sapporo ZDD format.
Works only for binary DDs.
Parameters
os the output stream.
Definition at line 702 of file DdStructure.hpp.
References tdzdd::MyVector< T, Size >::begin(), tdzdd::Node< ARITY >::branch, tdzdd::NodeId::col(), tdzdd::MyVector< T, Size >::end(), tdzdd::NodeId::row(), and tdzdd::DdStructure< ARITY >::size().
template<int ARITY> bool tdzdd::DdStructure< ARITY >::empty () const inline
Checks if DD is a 0-terminal only.
Returns
true if DD is a 0-terminal only.
Definition at line 300 of file DdStructure.hpp.
template<int ARITY> const_iterator tdzdd::DdStructure< ARITY >::end () const inline
Returns an iterator to the element following the last instance.
Supports binary ZDDs only.
Returns
iterator to the instance following the last instance.
Definition at line 668 of file DdStructure.hpp.
References tdzdd::DdStructure< ARITY >::const_iterator::const_iterator().
template<int ARITY> template<typename S , typename T , typename R > R tdzdd::DdStructure< ARITY >::evaluate (DdEval< S, T, R > const & evaluator) const inline
Evaluates the DD from the bottom to the top.
Parameters
evaluator the driver class that implements DdEval interface.
Returns
value at the root.
Definition at line 455 of file DdStructure.hpp.
References tdzdd::DdSpecBase< DdStructure< ARITY >, AR >::ARITY, tdzdd::MessageHandler_< os >::begin(), tdzdd::MyVector< T, Size >::begin(), tdzdd::NodeId::col(), tdzdd::MessageHandler_< os >::end(), tdzdd::MyVector< T, Size >::end(), tdzdd::DdEval< E, T, R >::entity(), tdzdd::NodeId::row(), tdzdd::DdValues< T, ARITY >::setLevel(), tdzdd::DdValues< T, ARITY >::setReference(), tdzdd::MessageHandler_< os >::setSteps(), tdzdd::MyVector< T, Size >::size(), tdzdd::MessageHandler_< os >::step(), and tdzdd::typenameof().
Referenced by tdzdd::DdStructure< ARITY >::bddCardinality(), and tdzdd::DdStructure< ARITY >::zddCardinality().
template<int ARITY> int tdzdd::DdStructure< ARITY >::getChild (NodeId & f, int level, int value) const inline
Implements DdSpec.
Definition at line 683 of file DdStructure.hpp.
References tdzdd::DdSpecBase< DdStructure< ARITY >, AR >::ARITY, tdzdd::DdStructure< ARITY >::child(), tdzdd::NodeId::col(), and tdzdd::NodeId::row().
template<int ARITY> NodeTableHandler<ARITY>& tdzdd::DdStructure< ARITY >::getDiagram () inline
Gets the diagram.
Returns
the node table handler.
Definition at line 268 of file DdStructure.hpp.
References tdzdd::DdStructure< ARITY >::diagram.
template<int ARITY> NodeTableHandler<ARITY> const& tdzdd::DdStructure< ARITY >::getDiagram () const inline
Gets the diagram.
Returns
the node table handler.
Definition at line 276 of file DdStructure.hpp.
References tdzdd::DdStructure< ARITY >::diagram.
template<int ARITY> int tdzdd::DdStructure< ARITY >::getRoot (NodeId & f) const inline
Implements DdSpec.
Definition at line 675 of file DdStructure.hpp.
References tdzdd::DdStructure< ARITY >::root_, and tdzdd::NodeId::row().
template<int ARITY> size_t tdzdd::DdStructure< ARITY >::hashCode (NodeId const & f) const inline
Implements DdSpec.
Definition at line 693 of file DdStructure.hpp.
References tdzdd::NodeId::hash().
template<int ARITY> bool tdzdd::DdStructure< ARITY >::operator!= (DdStructure< ARITY > const & o) const inline
Checks structural inequivalence with another DD.
Returns
true if they have the different structure.
Definition at line 356 of file DdStructure.hpp.
References tdzdd::DdStructure< ARITY >::operator==().
template<int ARITY> bool tdzdd::DdStructure< ARITY >::operator== (DdStructure< ARITY > const & o) const inline
Checks structural equivalence with another DD.
Returns
true if they have the same structure.
Definition at line 308 of file DdStructure.hpp.
References tdzdd::DdSpecBase< DdStructure< ARITY >, AR >::ARITY, tdzdd::Node< ARITY >::branch, tdzdd::NodeId::col(), tdzdd::DdStructure< ARITY >::diagram, tdzdd::MyHashMap< K, V, Hash, Equal >::getValue(), tdzdd::MyHashTable< MyHashMapEntry< K, V >, MyHashMapHashWrapper< K, V, Hash, Equal >, MyHashMapHashWrapper< K, V, Hash, Equal > >::initialize(), tdzdd::DdStructure< ARITY >::root_, tdzdd::NodeId::row(), and tdzdd::DdStructure< ARITY >::size().
Referenced by tdzdd::DdStructure< ARITY >::operator!=().
template<int ARITY> void tdzdd::DdStructure< ARITY >::qddReduce () inline
QDD reduction.
No node deletion rule is applied.
Definition at line 364 of file DdStructure.hpp.
template<int ARITY> template<bool BDD, bool ZDD> void tdzdd::DdStructure< ARITY >::reduce () inline
BDD/ZDD reduction.
Template Parameters
BDD enable BDD reduction.
ZDD enable ZDD reduction.
Definition at line 390 of file DdStructure.hpp.
References tdzdd::MessageHandler_< os >::begin(), tdzdd::MessageHandler_< os >::end(), tdzdd::DdReducer< ARITY, BDD, ZDD >::reduce(), tdzdd::NodeId::row(), tdzdd::DdReducer< ARITY, BDD, ZDD >::setRoot(), tdzdd::MessageHandler_< os >::setSteps(), tdzdd::DdStructure< ARITY >::size(), and tdzdd::MessageHandler_< os >::step().
template<int ARITY> NodeId& tdzdd::DdStructure< ARITY >::root () inline
Gets the root node.
Returns
root node ID.
Definition at line 242 of file DdStructure.hpp.
References tdzdd::DdStructure< ARITY >::root_.
template<int ARITY> NodeId tdzdd::DdStructure< ARITY >::root () const inline
Gets the root node.
Returns
root node ID.
Definition at line 250 of file DdStructure.hpp.
References tdzdd::DdStructure< ARITY >::root_.
template<int ARITY> size_t tdzdd::DdStructure< ARITY >::size () const inline
Gets the number of nonterminal nodes.
Returns
the number of nonterminal nodes.
Definition at line 292 of file DdStructure.hpp.
Referenced by tdzdd::DdStructure< ARITY >::construct_(), tdzdd::DdStructure< ARITY >::constructMP_(), tdzdd::DdStructure< ARITY >::dumpSapporo(), tdzdd::DdStructure< ARITY >::operator==(), tdzdd::DdStructure< ARITY >::reduce(), tdzdd::DdStructure< ARITY >::zddSubset_(), and tdzdd::DdStructure< ARITY >::zddSubsetMP_().
template<int ARITY> int tdzdd::DdStructure< ARITY >::topLevel () const inline
Gets the level of the root node.
Returns
the level of root ZDD variable.
Definition at line 284 of file DdStructure.hpp.
References tdzdd::NodeId::row().
template<int ARITY> bool tdzdd::DdStructure< ARITY >::useMultiProcessors (bool flag = true) inline
Enables or disables multiple processor algorithms.
Parameters
flag true for using multiple processor algorithms.
Returns
old value of the flag.
Definition at line 232 of file DdStructure.hpp.
References tdzdd::DdStructure< ARITY >::useMP.
template<int ARITY> DdStructure tdzdd::DdStructure< ARITY >::zdd2bdd (int numVars) const inline
Transforms a ZDD into a BDD.
Parameters
numVars the number of variables.
Definition at line 426 of file DdStructure.hpp.
References tdzdd::DdStructure< ARITY >::DdStructure().
template<int ARITY> std::string tdzdd::DdStructure< ARITY >::zddCardinality () const inline
Counts the number of sets in the family of sets represented by this ZDD.
Returns
the number of itemsets.
Definition at line 445 of file DdStructure.hpp.
References tdzdd::DdStructure< ARITY >::evaluate().
template<int ARITY> void tdzdd::DdStructure< ARITY >::zddReduce () inline
ZDD reduction.
The node of which 1-edge points to the 0-terminal is deleted.
Definition at line 380 of file DdStructure.hpp.
template<int ARITY> template<typename SPEC > void tdzdd::DdStructure< ARITY >::zddSubset (DdSpecBase< SPEC, ARITY > const & spec) inline
ZDD subsetting.
Parameters
spec ZDD spec.
Definition at line 166 of file DdStructure.hpp.
References tdzdd::DdSpecBase< S, AR >::entity(), tdzdd::DdStructure< ARITY >::zddSubset_(), and tdzdd::DdStructure< ARITY >::zddSubsetMP_().
template<int ARITY> template<typename SPEC > void tdzdd::DdStructure< ARITY >::zddSubset_ (SPEC const & spec) inline private
Definition at line 176 of file DdStructure.hpp.
References tdzdd::MessageHandler_< os >::begin(), tdzdd::NodeTableHandler< ARITY >::derefLevel(), tdzdd::MessageHandler_< os >::end(), tdzdd::ZddSubsetter< S >::initialize(), tdzdd::MessageHandler_< os >::setSteps(), tdzdd::DdStructure< ARITY >::size(), tdzdd::MessageHandler_< os >::step(), tdzdd::ZddSubsetter< S >::subset(), and tdzdd::typenameof().
Referenced by tdzdd::DdStructure< ARITY >::zddSubset().
template<int ARITY> template<typename SPEC > void tdzdd::DdStructure< ARITY >::zddSubsetMP_ (SPEC const & spec) inline private
Definition at line 200 of file DdStructure.hpp.
References tdzdd::MessageHandler_< os >::begin(), tdzdd::NodeTableHandler< ARITY >::derefLevel(), tdzdd::MessageHandler_< os >::end(), tdzdd::ZddSubsetterMP< S >::initialize(), tdzdd::MessageHandler_< os >::setSteps(), tdzdd::DdStructure< ARITY >::size(), tdzdd::MessageHandler_< os >::step(), tdzdd::ZddSubsetterMP< S >::subset(), and tdzdd::typenameof().
Referenced by tdzdd::DdStructure< ARITY >::zddSubset().
Member Data Documentation
template<int ARITY> NodeTableHandler<ARITY> tdzdd::DdStructure< ARITY >::diagram private
The diagram structure.
Definition at line 57 of file DdStructure.hpp.
Referenced by tdzdd::DdStructure< ARITY >::getDiagram(), tdzdd::DdStructure< ARITY >::const_iterator::next(), and tdzdd::DdStructure< ARITY >::operator==().
template<int ARITY> NodeId tdzdd::DdStructure< ARITY >::root_ private
Root node ID.
Definition at line 58 of file DdStructure.hpp.
Referenced by tdzdd::DdStructure< ARITY >::const_iterator::const_iterator(), tdzdd::DdStructure< ARITY >::getRoot(), tdzdd::DdStructure< ARITY >::operator==(), and tdzdd::DdStructure< ARITY >::root().
template<int ARITY> bool tdzdd::DdStructure< ARITY >::useMP private
Flag to use MP algorithms.
Definition at line 59 of file DdStructure.hpp.
Referenced by tdzdd::DdStructure< ARITY >::useMultiProcessors().
The documentation for this class was generated from the following file:
include/tdzdd/DdStructure.hpp