TdZdd: tdzdd::FrontierBasedSearch Class Reference
tdzdd::FrontierBasedSearch Class Reference
#include <FrontierBasedSearch.hpp>
Public Member Functions
FrontierBasedSearch (Graph const &graph, int numUEC=-1, bool noLoop=false, bool lookahead=true)
int getRoot (Count &count, Mate *mate) const
int getChild (Count &count, Mate *mate, int level, int take) const
size_t hashCode (Count const &count) const
Public Member Functions inherited from tdzdd::HybridDdSpec< FrontierBasedSearch, FrontierBasedSearchCount, FrontierBasedSearchMate, 2 >
HybridDdSpec ()
int datasize () const
void construct (void *p)
int get_root (void *p)
int get_child (void *p, int level, int value)
void getCopy (void *p, S_State const &s)
void get_copy (void *to, void const *from)
int mergeStates (S_State &s1, A_State *a1, S_State &s2, A_State *a2)
int merge_states (void *p1, void *p2)
void destruct (void *p)
void destructLevel (int level)
size_t hashCode (S_State const &s) const
size_t hashCodeAtLevel (S_State const &s, int level) const
size_t hash_code (void const *p, int level) const
bool equalTo (S_State const &s1, S_State const &s2) const
bool equalToAtLevel (S_State const &s1, S_State const &s2, int level) const
bool equal_to (void const *p, void const *q, int level) const
void printState (std::ostream &os, S_State const &s, A_State const *a) const
void printStateAtLevel (std::ostream &os, S_State const &s, A_State const *a, int level) const
void print_state (std::ostream &os, void const *p, int level) const
Public Member Functions inherited from tdzdd::DdSpecBase< FrontierBasedSearch, AR >
FrontierBasedSearch & entity ()
FrontierBasedSearchconst & entity () const
void printLevel (std::ostream &os, int level) const
std::vector< std::pair< int, int > > findOneInstance () const
Returns a random instance using simple depth-first search without caching.
void dumpDot (std::ostream &os=std::cout, std::string title=typenameof< FrontierBasedSearch >()) const
Dumps the node table in Graphviz (dot) format.
Private Types
typedef FrontierBasedSearchCount Count
typedef FrontierBasedSearchMate Mate
Private Member Functions
int takable (Count &c, Mate const *mate, Graph::EdgeInfo const &e) const
bool doTake (Count &count, Mate *mate, Graph::EdgeInfo const &e) const
bool doNotTake (Count &count, Mate *mate, Graph::EdgeInfo const &e) const
void update (Mate *mate, Graph::EdgeInfo const &e, Graph::EdgeInfo const &ee) const
Private Attributes
Graph const & graph
int const m
int const n
int const mateSize
std::vector< Mate > initialMate
int numUEC
bool const noLoop
bool const lookahead
Additional Inherited Members
Public Types inherited from tdzdd::HybridDdSpec< FrontierBasedSearch, FrontierBasedSearchCount, FrontierBasedSearchMate, 2 >
typedef FrontierBasedSearchCount S_State
typedef FrontierBasedSearchMate A_State
Static Public Attributes inherited from tdzdd::DdSpecBase< FrontierBasedSearch, AR >
static int const ARITY
Protected Member Functions inherited from tdzdd::HybridDdSpec< FrontierBasedSearch, FrontierBasedSearchCount, FrontierBasedSearchMate, 2 >
void setArraySize (int n)
int getArraySize () const
Static Protected Member Functions inherited from tdzdd::DdSpecBase< FrontierBasedSearch, AR >
static size_t rawHashCode (T const &o)
static size_t rawEqualTo (T const &o1, T const &o2)
Detailed Description
Definition at line 266 of file FrontierBasedSearch.hpp.
Member Typedef Documentation
typedef FrontierBasedSearchCount tdzdd::FrontierBasedSearch::Count private
Definition at line 268 of file FrontierBasedSearch.hpp.
typedef FrontierBasedSearchMate tdzdd::FrontierBasedSearch::Mate private
Definition at line 269 of file FrontierBasedSearch.hpp.
Constructor & Destructor Documentation
tdzdd::FrontierBasedSearch::FrontierBasedSearch (Graph const & graph, int numUEC = -1, bool noLoop = false, bool lookahead = true) inline
Definition at line 417 of file FrontierBasedSearch.hpp.
References tdzdd::Graph::colorNumber(), and tdzdd::Graph::numColor().
Member Function Documentation
bool tdzdd::FrontierBasedSearch::doNotTake (Count & count, Mate * mate, Graph::EdgeInfo const & e) const inline private
Definition at line 336 of file FrontierBasedSearch.hpp.
References tdzdd::Graph::EdgeInfo::finalEdge, tdzdd::FrontierBasedSearchMate::findColorPredecessor(), tdzdd::FrontierBasedSearchMate::isColored(), tdzdd::FrontierBasedSearchMate::isColoredTail(), tdzdd::FrontierBasedSearchMate::isHead(), tdzdd::FrontierBasedSearchMate::isIsolated(), tdzdd::FrontierBasedSearchMate::isTail(), tdzdd::FrontierBasedSearchMate::isUncoloredEdgeComponent(), tdzdd::FrontierBasedSearchMate::next(), tdzdd::FrontierBasedSearchCount::uec, tdzdd::Graph::EdgeInfo::v0, tdzdd::Graph::EdgeInfo::v1, tdzdd::Graph::EdgeInfo::v1final, tdzdd::Graph::EdgeInfo::v2, and tdzdd::Graph::EdgeInfo::v2final.
bool tdzdd::FrontierBasedSearch::doTake (Count & count, Mate * mate, Graph::EdgeInfo const & e) const inline private
Definition at line 326 of file FrontierBasedSearch.hpp.
References tdzdd::FrontierBasedSearchMate::mergeLists(), tdzdd::Graph::EdgeInfo::v0, tdzdd::Graph::EdgeInfo::v1, and tdzdd::Graph::EdgeInfo::v2.
int tdzdd::FrontierBasedSearch::getChild (Count & count, Mate * mate, int level, int take) const inline
Definition at line 447 of file FrontierBasedSearch.hpp.
References tdzdd::Graph::edgeInfo().
int tdzdd::FrontierBasedSearch::getRoot (Count & count, Mate * mate) const inline
Definition at line 435 of file FrontierBasedSearch.hpp.
References tdzdd::Graph::edgeInfo(), and tdzdd::Graph::EdgeInfo::v0.
size_t tdzdd::FrontierBasedSearch::hashCode (Count const & count) const inline
Definition at line 481 of file FrontierBasedSearch.hpp.
References tdzdd::FrontierBasedSearchCount::hash().
int tdzdd::FrontierBasedSearch::takable (Count & c, Mate const * mate, Graph::EdgeInfo const & e) const inline private
Definition at line 280 of file FrontierBasedSearch.hpp.
References tdzdd::Graph::EdgeInfo::finalEdge, tdzdd::FrontierBasedSearchMate::findColorPredecessor(), tdzdd::FrontierBasedSearchMate::hasSameColorAs(), tdzdd::FrontierBasedSearchMate::head(), tdzdd::FrontierBasedSearchMate::isColored(), tdzdd::FrontierBasedSearchMate::isColoredTail(), tdzdd::FrontierBasedSearchMate::isHead(), tdzdd::FrontierBasedSearchMate::isIsolated(), tdzdd::FrontierBasedSearchMate::isTail(), tdzdd::FrontierBasedSearchMate::isUncoloredEdgeComponent(), tdzdd::FrontierBasedSearchMate::next(), tdzdd::FrontierBasedSearchCount::uec, tdzdd::Graph::EdgeInfo::v0, tdzdd::Graph::EdgeInfo::v1, tdzdd::Graph::EdgeInfo::v1final, tdzdd::Graph::EdgeInfo::v2, and tdzdd::Graph::EdgeInfo::v2final.
void tdzdd::FrontierBasedSearch::update (Mate * mate, Graph::EdgeInfo const & e, Graph::EdgeInfo const & ee) const inline private
Definition at line 383 of file FrontierBasedSearch.hpp.
References tdzdd::FrontierBasedSearchMate::clear(), tdzdd::FrontierBasedSearchMate::next(), tdzdd::FrontierBasedSearchMate::removeFromList(), tdzdd::FrontierBasedSearchMate::replaceHeadWith(), tdzdd::Graph::EdgeInfo::v0, tdzdd::Graph::EdgeInfo::v1, tdzdd::Graph::EdgeInfo::v1final, tdzdd::Graph::EdgeInfo::v2, and tdzdd::Graph::EdgeInfo::v2final.
Member Data Documentation
Graph const& tdzdd::FrontierBasedSearch::graph private
Definition at line 271 of file FrontierBasedSearch.hpp.
std::vector<Mate> tdzdd::FrontierBasedSearch::initialMate private
Definition at line 275 of file FrontierBasedSearch.hpp.
bool const tdzdd::FrontierBasedSearch::lookahead private
Definition at line 278 of file FrontierBasedSearch.hpp.
int const tdzdd::FrontierBasedSearch::m private
Definition at line 272 of file FrontierBasedSearch.hpp.
int const tdzdd::FrontierBasedSearch::mateSize private
Definition at line 274 of file FrontierBasedSearch.hpp.
int const tdzdd::FrontierBasedSearch::n private
Definition at line 273 of file FrontierBasedSearch.hpp.
bool const tdzdd::FrontierBasedSearch::noLoop private
Definition at line 277 of file FrontierBasedSearch.hpp.
int tdzdd::FrontierBasedSearch::numUEC private
Definition at line 276 of file FrontierBasedSearch.hpp.
The documentation for this class was generated from the following file:
include/tdzdd/spec/FrontierBasedSearch.hpp