TdZdd: tdzdd::ZddSubsetter< S > Class Template Reference
tdzdd::ZddSubsetter< S > Class Template Reference
Breadth-first ZDD subset builder.
#include <DdBuilder.hpp>
Public Member Functions
ZddSubsetter (NodeTableHandler< AR > const &input, Spec const &s, NodeTableHandler< AR > &output)
~ZddSubsetter ()
int initialize (NodeId &root)
Initializes the builder.
void subset (int i)
Builds one level.
Private Types
typedef S Spec
typedef MyHashTable< SpecNode *, Hasher< Spec >, Hasher< Spec > > UniqTable
Private Member Functions
int downTable (NodeId &f, int b, int zerosupLevel) const
int downSpec (void *p, int level, int b, int zerosupLevel)
Private Attributes
Spec spec
int const specNodeSize
NodeTableEntity< AR > const & input
NodeTableEntity< AR > & output
DataTable< MyListOnPool< SpecNode > > work
DdSweeper< AR > sweeper
MyVector< char > oneStorage
void *const one
MyVector< NodeBranchId > oneSrcPtr
MemoryPools pools
Static Private Attributes
static int const AR = Spec::ARITY
Static Private Attributes inherited from tdzdd::DdBuilderBase
static int const headerSize = 1
Additional Inherited Members
Static Private Member Functions inherited from tdzdd::DdBuilderBase
static NodeId *& srcPtr (SpecNode *p)
static int64_t & code (SpecNode *p)
static NodeId & nodeId (SpecNode *p)
static void * state (SpecNode *p)
static void const * state (SpecNode const *p)
static int getSpecNodeSize (int n)
Detailed Description
template<typename S>
class tdzdd::ZddSubsetter< S >
Breadth-first ZDD subset builder.
Definition at line 678 of file DdBuilder.hpp.
Member Typedef Documentation
template<typename S> typedef S tdzdd::ZddSubsetter< S >::Spec private
Definition at line 680 of file DdBuilder.hpp.
template<typename S> typedef MyHashTable<SpecNode*,Hasher<Spec>,Hasher<Spec> > tdzdd::ZddSubsetter< S >::UniqTable private
Definition at line 681 of file DdBuilder.hpp.
Constructor & Destructor Documentation
template<typename S> tdzdd::ZddSubsetter< S >::ZddSubsetter (NodeTableHandler< AR > const & input, Spec const & s, NodeTableHandler< AR > & output) inline
Definition at line 698 of file DdBuilder.hpp.
template<typename S> tdzdd::ZddSubsetter< S >::~ZddSubsetter () inline
Definition at line 710 of file DdBuilder.hpp.
References tdzdd::MyVector< T, Size >::clear(), and tdzdd::MyVector< T, Size >::empty().
Member Function Documentation
template<typename S> int tdzdd::ZddSubsetter< S >::downSpec (void * p, int level, int b, int zerosupLevel) inline private
Definition at line 942 of file DdBuilder.hpp.
template<typename S> int tdzdd::ZddSubsetter< S >::downTable (NodeId & f, int b, int zerosupLevel) const inline private
Definition at line 932 of file DdBuilder.hpp.
References tdzdd::NodeTableEntity< ARITY >::child(), and tdzdd::NodeId::row().
template<typename S> int tdzdd::ZddSubsetter< S >::initialize (NodeId & root) inline
Initializes the builder.
Parameters
root the root node.
Definition at line 721 of file DdBuilder.hpp.
References tdzdd::MyVector< T, Size >::clear(), tdzdd::NodeId::col(), tdzdd::MyVector< T, Size >::data(), tdzdd::MyVector< T, Size >::empty(), tdzdd::NodeTableEntity< ARITY >::init(), tdzdd::MyVector< T, Size >::resize(), tdzdd::NodeId::row(), tdzdd::DdSweeper< ARITY >::setRoot(), tdzdd::DdBuilderBase::SpecNode::srcPtr, and tdzdd::DdBuilderBase::state().
Referenced by tdzdd::DdStructure< ARITY >::zddSubset_().
template<typename S> void tdzdd::ZddSubsetter< S >::subset (int i) inline
Builds one level.
Parameters
i level.
Definition at line 771 of file DdBuilder.hpp.
References tdzdd::MyHashTable< T, Hash, Equal >::add(), tdzdd::MyVector< T, Size >::back(), tdzdd::MyListOnPool< T >::begin(), tdzdd::Node< ARITY >::branch, tdzdd::MyVector< T, Size >::clear(), tdzdd::NodeId::col(), tdzdd::NodeBranchId::col, tdzdd::MyVector< T, Size >::data(), tdzdd::MyVector< T, Size >::empty(), tdzdd::MyListOnPool< T >::end(), tdzdd::MyListOnPool< T >::front(), tdzdd::DataTable< T >::initRow(), tdzdd::DdBuilderBase::nodeId(), tdzdd::DataTable< T >::numRows(), tdzdd::MyVector< T, Size >::pop_back(), tdzdd::MyVector< T, Size >::push_back(), tdzdd::NodeId::row(), tdzdd::NodeBranchId::row, tdzdd::NodeTableEntity< ARITY >::size(), tdzdd::MyVector< T, Size >::size(), tdzdd::MyListOnPool< T >::size(), tdzdd::DdBuilderBase::SpecNode::srcPtr, tdzdd::DdBuilderBase::state(), tdzdd::DdSweeper< ARITY >::update(), and tdzdd::NodeBranchId::val.
Referenced by tdzdd::DdStructure< ARITY >::zddSubset_().
Member Data Documentation
template<typename S> int const tdzdd::ZddSubsetter< S >::AR = Spec::ARITY static private
Definition at line 682 of file DdBuilder.hpp.
template<typename S> NodeTableEntity<AR> const& tdzdd::ZddSubsetter< S >::input private
Definition at line 686 of file DdBuilder.hpp.
template<typename S> void* const tdzdd::ZddSubsetter< S >::one private
Definition at line 692 of file DdBuilder.hpp.
template<typename S> MyVector<NodeBranchId> tdzdd::ZddSubsetter< S >::oneSrcPtr private
Definition at line 693 of file DdBuilder.hpp.
template<typename S> MyVector<char> tdzdd::ZddSubsetter< S >::oneStorage private
Definition at line 691 of file DdBuilder.hpp.
template<typename S> NodeTableEntity<AR>& tdzdd::ZddSubsetter< S >::output private
Definition at line 687 of file DdBuilder.hpp.
template<typename S> MemoryPools tdzdd::ZddSubsetter< S >::pools private
Definition at line 695 of file DdBuilder.hpp.
template<typename S> Spec tdzdd::ZddSubsetter< S >::spec private
Definition at line 684 of file DdBuilder.hpp.
template<typename S> int const tdzdd::ZddSubsetter< S >::specNodeSize private
Definition at line 685 of file DdBuilder.hpp.
template<typename S> DdSweeper<AR> tdzdd::ZddSubsetter< S >::sweeper private
Definition at line 689 of file DdBuilder.hpp.
template<typename S> DataTable<MyListOnPool<SpecNode> > tdzdd::ZddSubsetter< S >::work private
Definition at line 688 of file DdBuilder.hpp.
The documentation for this class was generated from the following file:
include/tdzdd/dd/DdBuilder.hpp