TdZdd: tdzdd::MyList< T, BLOCK_ELEMENTS >::const_iterator Class Reference
tdzdd::MyList< T, BLOCK_ELEMENTS >::const_iterator Class Reference
#include <MyList.hpp>
Public Member Functions
const_iterator (Cell const *front)
T const * operator* () const
T const * operator-> () const
const_iterator & operator++ ()
bool operator== (iterator const &o) const
bool operator!= (iterator const &o) const
Private Attributes
Cell const * front
Detailed Description
template<typename T, size_t BLOCK_ELEMENTS = 1000>
class tdzdd::MyList< T, BLOCK_ELEMENTS >::const_iterator
Definition at line 229 of file MyList.hpp.
Constructor & Destructor Documentation
template<typename T, size_t BLOCK_ELEMENTS = 1000> tdzdd::MyList< T, BLOCK_ELEMENTS >::const_iterator::const_iterator (Cell const * front) inline
Definition at line 233 of file MyList.hpp.
Member Function Documentation
template<typename T, size_t BLOCK_ELEMENTS = 1000> bool tdzdd::MyList< T, BLOCK_ELEMENTS >::const_iterator::operator!= (iterator const & o) const inline
Definition at line 254 of file MyList.hpp.
References tdzdd::MyList< T, BLOCK_ELEMENTS >::iterator::front.
template<typename T, size_t BLOCK_ELEMENTS = 1000> T const* tdzdd::MyList< T, BLOCK_ELEMENTS >::const_iterator::operator* () const inline
Definition at line 237 of file MyList.hpp.
References tdzdd::MyList< T, BLOCK_ELEMENTS >::dataStart().
template<typename T, size_t BLOCK_ELEMENTS = 1000> const_iterator& tdzdd::MyList< T, BLOCK_ELEMENTS >::const_iterator::operator++ () inline
Definition at line 245 of file MyList.hpp.
References tdzdd::MyList< T, BLOCK_ELEMENTS >::clearFlag(), and tdzdd::MyList< T, BLOCK_ELEMENTS >::Cell::next.
template<typename T, size_t BLOCK_ELEMENTS = 1000> T const* tdzdd::MyList< T, BLOCK_ELEMENTS >::const_iterator::operator-> () const inline
Definition at line 241 of file MyList.hpp.
References tdzdd::MyList< T, BLOCK_ELEMENTS >::dataStart().
template<typename T, size_t BLOCK_ELEMENTS = 1000> bool tdzdd::MyList< T, BLOCK_ELEMENTS >::const_iterator::operator== (iterator const & o) const inline
Definition at line 250 of file MyList.hpp.
References tdzdd::MyList< T, BLOCK_ELEMENTS >::iterator::front.
Member Data Documentation
template<typename T, size_t BLOCK_ELEMENTS = 1000> Cell const* tdzdd::MyList< T, BLOCK_ELEMENTS >::const_iterator::front private
Definition at line 230 of file MyList.hpp.
The documentation for this class was generated from the following file:
include/tdzdd/util/MyList.hpp