TdZdd: tdzdd::FrontierBasedSearchMate Class Reference
tdzdd::FrontierBasedSearchMate Class Reference
#include <FrontierBasedSearch.hpp>
Public Types
typedef int16_t Offset
Public Member Functions
FrontierBasedSearchMate (Offset hoc=0)
bool operator== (FrontierBasedSearchMate const &o) const
bool operator!= (FrontierBasedSearchMate const &o) const
void clear ()
bool isHead () const
bool isTail () const
bool isIsolated () const
FrontierBasedSearchMate & head ()
FrontierBasedSearchMate const & head () const
FrontierBasedSearchMate & next ()
FrontierBasedSearchMate const & next () const
bool isColored () const
bool isUncoloredEdgeComponent () const
bool isColoredTail () const
bool hasSameColorAs (FrontierBasedSearchMate const &o) const
FrontierBasedSearchMate const * findColorPredecessor (FrontierBasedSearchMate const &o) const
void mergeLists (FrontierBasedSearchMate &o1, FrontierBasedSearchMate &o2)
void replaceHeadWith (FrontierBasedSearchMate &newHead) const
void removeFromList (FrontierBasedSearchMate const &o)
Static Public Attributes
static Offset const UNCOLORED = 32766
static Offset const UNCOLORED_EDGE_COMPONENT = 32767
Private Attributes
Offset hoc
offset to head or color.
Offset nxt
offset to next connected vertex.
Friends
std::ostream & operator<< (std::ostream &os, FrontierBasedSearchMate const &o)
Detailed Description
Definition at line 64 of file FrontierBasedSearch.hpp.
Member Typedef Documentation
typedef int16_t tdzdd::FrontierBasedSearchMate::Offset
Definition at line 66 of file FrontierBasedSearch.hpp.
Constructor & Destructor Documentation
tdzdd::FrontierBasedSearchMate::FrontierBasedSearchMate (Offset hoc = 0) inline
Definition at line 86 of file FrontierBasedSearch.hpp.
Member Function Documentation
void tdzdd::FrontierBasedSearchMate::clear () inline
Definition at line 98 of file FrontierBasedSearch.hpp.
Referenced by tdzdd::FrontierBasedSearch::update().
FrontierBasedSearchMate const* tdzdd::FrontierBasedSearchMate::findColorPredecessor (FrontierBasedSearchMate const & o) const inline
Definition at line 149 of file FrontierBasedSearch.hpp.
References head(), hoc, and isColoredTail().
Referenced by tdzdd::FrontierBasedSearch::doNotTake(), and tdzdd::FrontierBasedSearch::takable().
bool tdzdd::FrontierBasedSearchMate::hasSameColorAs (FrontierBasedSearchMate const & o) const inline
Definition at line 143 of file FrontierBasedSearch.hpp.
References head(), and hoc.
Referenced by tdzdd::FrontierBasedSearch::takable().
FrontierBasedSearchMate& tdzdd::FrontierBasedSearchMate::head () inline
Definition at line 115 of file FrontierBasedSearch.hpp.
Referenced by findColorPredecessor(), hasSameColorAs(), mergeLists(), and tdzdd::FrontierBasedSearch::takable().
FrontierBasedSearchMate const& tdzdd::FrontierBasedSearchMate::head () const inline
Definition at line 119 of file FrontierBasedSearch.hpp.
bool tdzdd::FrontierBasedSearchMate::isColored () const inline
Definition at line 131 of file FrontierBasedSearch.hpp.
Referenced by tdzdd::FrontierBasedSearch::doNotTake(), and tdzdd::FrontierBasedSearch::takable().
bool tdzdd::FrontierBasedSearchMate::isColoredTail () const inline
Definition at line 139 of file FrontierBasedSearch.hpp.
Referenced by tdzdd::FrontierBasedSearch::doNotTake(), findColorPredecessor(), removeFromList(), and tdzdd::FrontierBasedSearch::takable().
bool tdzdd::FrontierBasedSearchMate::isHead () const inline
Definition at line 103 of file FrontierBasedSearch.hpp.
Referenced by tdzdd::FrontierBasedSearch::doNotTake(), and tdzdd::FrontierBasedSearch::takable().
bool tdzdd::FrontierBasedSearchMate::isIsolated () const inline
Definition at line 111 of file FrontierBasedSearch.hpp.
Referenced by tdzdd::FrontierBasedSearch::doNotTake(), and tdzdd::FrontierBasedSearch::takable().
bool tdzdd::FrontierBasedSearchMate::isTail () const inline
Definition at line 107 of file FrontierBasedSearch.hpp.
Referenced by tdzdd::FrontierBasedSearch::doNotTake(), and tdzdd::FrontierBasedSearch::takable().
bool tdzdd::FrontierBasedSearchMate::isUncoloredEdgeComponent () const inline
Definition at line 135 of file FrontierBasedSearch.hpp.
Referenced by tdzdd::FrontierBasedSearch::doNotTake(), and tdzdd::FrontierBasedSearch::takable().
void tdzdd::FrontierBasedSearchMate::mergeLists (FrontierBasedSearchMate & o1, FrontierBasedSearchMate & o2) inline
Definition at line 162 of file FrontierBasedSearch.hpp.
References head(), hoc, and nxt.
Referenced by tdzdd::FrontierBasedSearch::doTake().
FrontierBasedSearchMate& tdzdd::FrontierBasedSearchMate::next () inline
Definition at line 123 of file FrontierBasedSearch.hpp.
Referenced by tdzdd::FrontierBasedSearch::doNotTake(), tdzdd::FrontierBasedSearch::takable(), and tdzdd::FrontierBasedSearch::update().
FrontierBasedSearchMate const& tdzdd::FrontierBasedSearchMate::next () const inline
Definition at line 127 of file FrontierBasedSearch.hpp.
bool tdzdd::FrontierBasedSearchMate::operator!= (FrontierBasedSearchMate const & o) const inline
Definition at line 94 of file FrontierBasedSearch.hpp.
bool tdzdd::FrontierBasedSearchMate::operator== (FrontierBasedSearchMate const & o) const inline
Definition at line 90 of file FrontierBasedSearch.hpp.
void tdzdd::FrontierBasedSearchMate::removeFromList (FrontierBasedSearchMate const & o) inline
Definition at line 237 of file FrontierBasedSearch.hpp.
References isColoredTail(), and nxt.
Referenced by tdzdd::FrontierBasedSearch::update().
void tdzdd::FrontierBasedSearchMate::replaceHeadWith (FrontierBasedSearchMate & newHead) const inline
Definition at line 225 of file FrontierBasedSearch.hpp.
References hoc, and nxt.
Referenced by tdzdd::FrontierBasedSearch::update().
Friends And Related Function Documentation
std::ostream& operator<< (std::ostream & os, FrontierBasedSearchMate const & o) friend
Definition at line 260 of file FrontierBasedSearch.hpp.
Member Data Documentation
Offset tdzdd::FrontierBasedSearchMate::hoc private
offset to head or color.
Definition at line 71 of file FrontierBasedSearch.hpp.
Referenced by findColorPredecessor(), hasSameColorAs(), mergeLists(), and replaceHeadWith().
Offset tdzdd::FrontierBasedSearchMate::nxt private
offset to next connected vertex.
Definition at line 72 of file FrontierBasedSearch.hpp.
Referenced by mergeLists(), removeFromList(), and replaceHeadWith().
Offset const tdzdd::FrontierBasedSearchMate::UNCOLORED = 32766 static
Definition at line 67 of file FrontierBasedSearch.hpp.
Offset const tdzdd::FrontierBasedSearchMate::UNCOLORED_EDGE_COMPONENT = 32767 static
Definition at line 68 of file FrontierBasedSearch.hpp.
The documentation for this class was generated from the following file:
include/tdzdd/spec/FrontierBasedSearch.hpp