TdZdd: tdzdd::DdDumper< S > Class Template Reference
tdzdd::DdDumper< S > Class Template Reference
DD dumper.
#include <DdBuilder.hpp>
Classes
struct Hasher
struct SpecNode
Public Member Functions
DdDumper (Spec const &s)
~DdDumper ()
void dump (std::ostream &os, std::string title)
Dumps the node table in Graphviz (dot) format.
Private Types
typedef S Spec
typedef MyHashTable< SpecNode *, Hasher< Spec >, Hasher< Spec > > UniqTable
Private Member Functions
void dumpStep (std::ostream &os, int i)
Static Private Member Functions
static NodeId & nodeId (SpecNode *p)
static NodeId nodeId (SpecNode const *p)
static void * state (SpecNode *p)
static void const * state (SpecNode const *p)
static int getSpecNodeSize (int n)
Private Attributes
Spec spec
int const specNodeSize
char * oneState
NodeId oneId
MyVector< MyList< SpecNode > > snodeTable
MyVector< UniqTable > uniqTable
MyVector< Hasher< Spec > > hasher
Static Private Attributes
static int const AR = Spec::ARITY
static int const headerSize = 1
Detailed Description
template<typename S>
class tdzdd::DdDumper< S >
DD dumper.
A node table is printed in Graphviz (dot) format.
Definition at line 1248 of file DdBuilder.hpp.
Member Typedef Documentation
template<typename S> typedef S tdzdd::DdDumper< S >::Spec private
Definition at line 1249 of file DdBuilder.hpp.
template<typename S> typedef MyHashTable<SpecNode*,Hasher<Spec>,Hasher<Spec> > tdzdd::DdDumper< S >::UniqTable private
Definition at line 1296 of file DdBuilder.hpp.
Constructor & Destructor Documentation
template<typename S> tdzdd::DdDumper< S >::DdDumper (Spec const & s) inline
Definition at line 1314 of file DdBuilder.hpp.
template<typename S> tdzdd::DdDumper< S >::~DdDumper () inline
Definition at line 1321 of file DdBuilder.hpp.
Member Function Documentation
template<typename S> void tdzdd::DdDumper< S >::dump (std::ostream & os, std::string title) inline
Dumps the node table in Graphviz (dot) format.
Parameters
os the output stream.
title title label.
Definition at line 1333 of file DdBuilder.hpp.
References tdzdd::MyVector< T, Size >::back(), tdzdd::MyVector< T, Size >::clear(), tdzdd::NodeId::code(), tdzdd::MyVector< T, Size >::init(), tdzdd::DdBuilderBase::nodeId(), tdzdd::MyVector< T, Size >::push_back(), tdzdd::MyVector< T, Size >::reserve(), and tdzdd::DdBuilderBase::state().
Referenced by tdzdd::DdSpecBase< HamiltonCycleZdd, AR >::dumpDot().
template<typename S> void tdzdd::DdDumper< S >::dumpStep (std::ostream & os, int i) inline private
Definition at line 1403 of file DdBuilder.hpp.
References tdzdd::MyVector< T, Size >::clear(), tdzdd::NodeId::code(), tdzdd::MyVector< T, Size >::data(), tdzdd::MyList< T, BLOCK_ELEMENTS >::empty(), tdzdd::MyList< T, BLOCK_ELEMENTS >::front(), tdzdd::DdBuilderBase::nodeId(), tdzdd::MyList< T, BLOCK_ELEMENTS >::pop_front(), tdzdd::MyList< T, BLOCK_ELEMENTS >::size(), tdzdd::MyVector< T, Size >::size(), and tdzdd::DdBuilderBase::state().
template<typename S> static int tdzdd::DdDumper< S >::getSpecNodeSize (int n) inline static private
Definition at line 1298 of file DdBuilder.hpp.
template<typename S> static NodeId& tdzdd::DdDumper< S >::nodeId (SpecNode * p) inline static private
Definition at line 1262 of file DdBuilder.hpp.
References tdzdd::DdDumper< S >::SpecNode::nodeId.
template<typename S> static NodeId tdzdd::DdDumper< S >::nodeId (SpecNode const * p) inline static private
Definition at line 1266 of file DdBuilder.hpp.
References tdzdd::DdDumper< S >::SpecNode::nodeId.
template<typename S> static void* tdzdd::DdDumper< S >::state (SpecNode * p) inline static private
Definition at line 1270 of file DdBuilder.hpp.
References tdzdd::DdBuilderBase::headerSize.
template<typename S> static void const* tdzdd::DdDumper< S >::state (SpecNode const * p) inline static private
Definition at line 1274 of file DdBuilder.hpp.
References tdzdd::DdBuilderBase::headerSize.
Member Data Documentation
template<typename S> int const tdzdd::DdDumper< S >::AR = Spec::ARITY static private
Definition at line 1250 of file DdBuilder.hpp.
template<typename S> MyVector<Hasher<Spec> > tdzdd::DdDumper< S >::hasher private
Definition at line 1311 of file DdBuilder.hpp.
template<typename S> int const tdzdd::DdDumper< S >::headerSize = 1 static private
Definition at line 1251 of file DdBuilder.hpp.
template<typename S> NodeId tdzdd::DdDumper< S >::oneId private
Definition at line 1307 of file DdBuilder.hpp.
template<typename S> char* tdzdd::DdDumper< S >::oneState private
Definition at line 1306 of file DdBuilder.hpp.
template<typename S> MyVector<MyList<SpecNode> > tdzdd::DdDumper< S >::snodeTable private
Definition at line 1309 of file DdBuilder.hpp.
template<typename S> Spec tdzdd::DdDumper< S >::spec private
Definition at line 1304 of file DdBuilder.hpp.
template<typename S> int const tdzdd::DdDumper< S >::specNodeSize private
Definition at line 1305 of file DdBuilder.hpp.
template<typename S> MyVector<UniqTable> tdzdd::DdDumper< S >::uniqTable private
Definition at line 1310 of file DdBuilder.hpp.
The documentation for this class was generated from the following file:
include/tdzdd/dd/DdBuilder.hpp