TdZdd: tdzdd::CardinalityBase< E, std::string, ARITY, BDD > Class Template Reference
tdzdd::CardinalityBase< E, std::string, ARITY, BDD > Class Template Reference
#include <Cardinality.hpp>
Public Member Functions
CardinalityBase (int numVars=0)
void initialize (int level)
void evalTerminal (BigNumber &n, int value)
void evalNode (BigNumber &n, int i, DdValues< BigNumber, ARITY > const &values)
std::string getValue (BigNumber const &n)
void destructLevel (int i)
Public Member Functions inherited from tdzdd::DdEval< E, BigNumber, std::string >
E & entity ()
E const & entity () const
bool isThreadSafe () const
Declares thread-safety.
bool showMessages () const
Declares preference to show messages.
void initialize (int level)
Initialization.
std::string getValue (BigNumberconst &v)
Makes a result value.
void destructLevel (int i)
Destructs i-th level of data storage.
Private Attributes
int numVars
int topLevel
MemoryPools pools
BigNumber tmp1
BigNumber tmp2
BigNumber tmp3
Detailed Description
template<typename E, int ARITY, bool BDD>
class tdzdd::CardinalityBase< E, std::string, ARITY, BDD >
Definition at line 91 of file Cardinality.hpp.
Constructor & Destructor Documentation
template<typename E , int ARITY, bool BDD> tdzdd::CardinalityBase< E, std::string, ARITY, BDD >::CardinalityBase (int numVars = 0) inline
Definition at line 101 of file Cardinality.hpp.
Member Function Documentation
template<typename E , int ARITY, bool BDD> void tdzdd::CardinalityBase< E, std::string, ARITY, BDD >::destructLevel (int i) inline
Definition at line 184 of file Cardinality.hpp.
References tdzdd::MyVector< T, Size >::clear().
template<typename E , int ARITY, bool BDD> void tdzdd::CardinalityBase< E, std::string, ARITY, BDD >::evalNode (BigNumber & n, int i, DdValues< BigNumber, ARITY > const & values) inline
Definition at line 121 of file Cardinality.hpp.
References tdzdd::BigNumber::add(), tdzdd::DdValues< T, ARITY >::get(), tdzdd::DdValues< T, ARITY >::getLevel(), tdzdd::BigNumber::setArray(), tdzdd::BigNumber::shiftLeft(), tdzdd::MyVector< T, Size >::size(), and tdzdd::BigNumber::store().
template<typename E , int ARITY, bool BDD> void tdzdd::CardinalityBase< E, std::string, ARITY, BDD >::evalTerminal (BigNumber & n, int value) inline
Definition at line 116 of file Cardinality.hpp.
References tdzdd::BigNumber::setArray(), and tdzdd::BigNumber::store().
template<typename E , int ARITY, bool BDD> std::string tdzdd::CardinalityBase< E, std::string, ARITY, BDD >::getValue (BigNumber const & n) inline
Definition at line 162 of file Cardinality.hpp.
References tdzdd::BigNumber::add(), tdzdd::BigNumber::shiftLeft(), tdzdd::BigNumber::store(), and tdzdd::CardinalityBase< E, T, ARITY, BDD >::topLevel.
template<typename E , int ARITY, bool BDD> void tdzdd::CardinalityBase< E, std::string, ARITY, BDD >::initialize (int level) inline
Definition at line 106 of file Cardinality.hpp.
References tdzdd::MyVector< T, Size >::resize(), and tdzdd::BigNumber::setArray().
Member Data Documentation
template<typename E , int ARITY, bool BDD> int tdzdd::CardinalityBase< E, std::string, ARITY, BDD >::numVars private
Definition at line 93 of file Cardinality.hpp.
template<typename E , int ARITY, bool BDD> MemoryPools tdzdd::CardinalityBase< E, std::string, ARITY, BDD >::pools private
Definition at line 95 of file Cardinality.hpp.
template<typename E , int ARITY, bool BDD> BigNumber tdzdd::CardinalityBase< E, std::string, ARITY, BDD >::tmp1 private
Definition at line 96 of file Cardinality.hpp.
template<typename E , int ARITY, bool BDD> BigNumber tdzdd::CardinalityBase< E, std::string, ARITY, BDD >::tmp2 private
Definition at line 97 of file Cardinality.hpp.
template<typename E , int ARITY, bool BDD> BigNumber tdzdd::CardinalityBase< E, std::string, ARITY, BDD >::tmp3 private
Definition at line 98 of file Cardinality.hpp.
template<typename E , int ARITY, bool BDD> int tdzdd::CardinalityBase< E, std::string, ARITY, BDD >::topLevel private
Definition at line 94 of file Cardinality.hpp.
The documentation for this class was generated from the following file:
include/tdzdd/eval/Cardinality.hpp