TdZdd: tdzdd::PathCounter< S > Class Template Reference
tdzdd::PathCounter< S > Class Template Reference
#include <PathCounter.hpp>
Classes
struct Hasher
Public Member Functions
PathCounter (S &s)
std::string count ()
std::string countFast ()
uint64_t count64 ()
Private Types
typedef S Spec
typedef uint64_t Word
typedef MyHashTable< Word *, Hasher, Hasher > UniqTable
Private Member Functions
BigNumber number (Word *p) const
uint64_t & number64 (Word *p) const
Static Private Member Functions
static int numWords (int n)
static void * state (Word *p)
static void const * state (Word const *p)
Private Attributes
Spec & spec
int const stateWords
Detailed Description
template<typename S>
class tdzdd::PathCounter< S >
Definition at line 46 of file PathCounter.hpp.
Member Typedef Documentation
template<typename S> typedef S tdzdd::PathCounter< S >::Spec private
Definition at line 48 of file PathCounter.hpp.
template<typename S> typedef MyHashTable<Word*,Hasher,Hasher> tdzdd::PathCounter< S >::UniqTable private
Definition at line 68 of file PathCounter.hpp.
template<typename S> typedef uint64_t tdzdd::PathCounter< S >::Word private
Definition at line 49 of file PathCounter.hpp.
Constructor & Destructor Documentation
template<typename S> tdzdd::PathCounter< S >::PathCounter (S & s) inline
Definition at line 98 of file PathCounter.hpp.
Member Function Documentation
template<typename S> std::string tdzdd::PathCounter< S >::count () inline
Definition at line 102 of file PathCounter.hpp.
References tdzdd::BigNumber::add(), tdzdd::MyHashTable< T, Hash, Equal >::add(), tdzdd::MyList< T, BLOCK_ELEMENTS >::alloc_front(), tdzdd::MyVector< T, Size >::back(), tdzdd::MessageHandler_< os >::begin(), tdzdd::MyHashTable< T, Hash, Equal >::clear(), tdzdd::MyVector< T, Size >::clear(), tdzdd::MyVector< T, Size >::data(), tdzdd::MyList< T, BLOCK_ELEMENTS >::empty(), tdzdd::MessageHandler_< os >::end(), tdzdd::MyList< T, BLOCK_ELEMENTS >::front(), tdzdd::PathCounter< S >::Hasher::Hasher(), tdzdd::PathCounter< S >::number(), tdzdd::MyList< T, BLOCK_ELEMENTS >::pop_front(), tdzdd::MyVector< T, Size >::push_back(), tdzdd::MyVector< T, Size >::reserve(), tdzdd::MessageHandler_< os >::setSteps(), tdzdd::MyList< T, BLOCK_ELEMENTS >::size(), tdzdd::PathCounter< S >::state(), tdzdd::MessageHandler_< os >::step(), tdzdd::BigNumber::store(), and tdzdd::typenameof().
Referenced by tdzdd::countPaths().
template<typename S> uint64_t tdzdd::PathCounter< S >::count64 () inline
Definition at line 326 of file PathCounter.hpp.
References tdzdd::MyHashTable< T, Hash, Equal >::add(), tdzdd::MyList< T, BLOCK_ELEMENTS >::alloc_front(), tdzdd::MyVector< T, Size >::back(), tdzdd::MessageHandler_< os >::begin(), tdzdd::MyHashTable< T, Hash, Equal >::clear(), tdzdd::MyVector< T, Size >::clear(), tdzdd::MyVector< T, Size >::data(), tdzdd::MyList< T, BLOCK_ELEMENTS >::empty(), tdzdd::MessageHandler_< os >::end(), tdzdd::MyList< T, BLOCK_ELEMENTS >::front(), tdzdd::PathCounter< S >::Hasher::Hasher(), tdzdd::PathCounter< S >::number64(), tdzdd::MyList< T, BLOCK_ELEMENTS >::pop_front(), tdzdd::MyVector< T, Size >::push_back(), tdzdd::MyVector< T, Size >::reserve(), tdzdd::MessageHandler_< os >::setSteps(), tdzdd::MyList< T, BLOCK_ELEMENTS >::size(), tdzdd::PathCounter< S >::state(), tdzdd::MessageHandler_< os >::step(), and tdzdd::typenameof().
Referenced by tdzdd::countPaths64().
template<typename S> std::string tdzdd::PathCounter< S >::countFast () inline
Definition at line 221 of file PathCounter.hpp.
References tdzdd::BigNumber::add(), tdzdd::MyList< T, BLOCK_ELEMENTS >::alloc_front(), tdzdd::MessageHandler_< os >::begin(), tdzdd::MyList< T, BLOCK_ELEMENTS >::begin(), tdzdd::MyVector< T, Size >::clear(), tdzdd::MyVector< T, Size >::data(), tdzdd::MyList< T, BLOCK_ELEMENTS >::empty(), tdzdd::MessageHandler_< os >::end(), tdzdd::MyList< T, BLOCK_ELEMENTS >::end(), tdzdd::MyList< T, BLOCK_ELEMENTS >::front(), tdzdd::PathCounter< S >::number(), tdzdd::MyList< T, BLOCK_ELEMENTS >::pop_front(), tdzdd::MessageHandler_< os >::setSteps(), tdzdd::MyList< T, BLOCK_ELEMENTS >::size(), tdzdd::PathCounter< S >::state(), tdzdd::MessageHandler_< os >::step(), tdzdd::BigNumber::store(), and tdzdd::typenameof().
Referenced by tdzdd::countPaths().
template<typename S> BigNumber tdzdd::PathCounter< S >::number (Word * p) const inline private
Definition at line 87 of file PathCounter.hpp.
Referenced by tdzdd::PathCounter< S >::count(), and tdzdd::PathCounter< S >::countFast().
template<typename S> uint64_t& tdzdd::PathCounter< S >::number64 (Word * p) const inline private
Definition at line 91 of file PathCounter.hpp.
References tdzdd::PathCounter< S >::stateWords.
Referenced by tdzdd::PathCounter< S >::count64().
template<typename S> static int tdzdd::PathCounter< S >::numWords (int n) inline static private
Definition at line 73 of file PathCounter.hpp.
template<typename S> static void* tdzdd::PathCounter< S >::state (Word * p) inline static private
Definition at line 79 of file PathCounter.hpp.
Referenced by tdzdd::PathCounter< S >::count(), tdzdd::PathCounter< S >::count64(), tdzdd::PathCounter< S >::countFast(), and tdzdd::PathCounter< S >::Hasher::operator()().
template<typename S> static void const* tdzdd::PathCounter< S >::state (Word const * p) inline static private
Definition at line 83 of file PathCounter.hpp.
Member Data Documentation
template<typename S> Spec& tdzdd::PathCounter< S >::spec private
Definition at line 70 of file PathCounter.hpp.
template<typename S> int const tdzdd::PathCounter< S >::stateWords private
Definition at line 71 of file PathCounter.hpp.
Referenced by tdzdd::PathCounter< S >::number64().
The documentation for this class was generated from the following file:
include/tdzdd/dd/PathCounter.hpp