TdZdd: tdzdd::MyBitSet< N >::const_iterator Class Reference
tdzdd::MyBitSet< N >::const_iterator Class Reference
#include <MySet.hpp>
Public Member Functions
const_iterator (MyBitSet const &bitSet)
const_iterator (MyBitSet const &bitSet, size_t i)
size_t operator* () const
const_iterator & operator++ ()
bool operator== (const_iterator const &o) const
bool operator!= (const_iterator const &o) const
Private Attributes
MyBitSet const & bitSet
size_t wordPos
int bitPos
uint64_t word
Detailed Description
template<size_t N>
class tdzdd::MyBitSet< N >::const_iterator
Definition at line 155 of file MySet.hpp.
Constructor & Destructor Documentation
template<size_t N> tdzdd::MyBitSet< N >::const_iterator::const_iterator (MyBitSet const & bitSet) inline
Definition at line 162 of file MySet.hpp.
Referenced by tdzdd::MyBitSet< 0 >::begin(), and tdzdd::MyBitSet< 0 >::end().
template<size_t N> tdzdd::MyBitSet< N >::const_iterator::const_iterator (MyBitSet const & bitSet, size_t i) inline
Definition at line 166 of file MySet.hpp.
Member Function Documentation
template<size_t N> bool tdzdd::MyBitSet< N >::const_iterator::operator!= (const_iterator const & o) const inline
Definition at line 213 of file MySet.hpp.
template<size_t N> size_t tdzdd::MyBitSet< N >::const_iterator::operator* () const inline
Definition at line 171 of file MySet.hpp.
References tdzdd::MyBitSet< N >::const_iterator::bitPos.
template<size_t N> const_iterator& tdzdd::MyBitSet< N >::const_iterator::operator++ () inline
Definition at line 175 of file MySet.hpp.
References tdzdd::MyBitSet< N >::numWords(), and tdzdd::MyBitSet< N >::word().
template<size_t N> bool tdzdd::MyBitSet< N >::const_iterator::operator== (const_iterator const & o) const inline
Definition at line 209 of file MySet.hpp.
References tdzdd::MyBitSet< N >::const_iterator::bitPos, and tdzdd::MyBitSet< N >::const_iterator::wordPos.
Member Data Documentation
template<size_t N> int tdzdd::MyBitSet< N >::const_iterator::bitPos private
Definition at line 158 of file MySet.hpp.
Referenced by tdzdd::MyBitSet< N >::const_iterator::operator*(), and tdzdd::MyBitSet< N >::const_iterator::operator==().
template<size_t N> MyBitSet const& tdzdd::MyBitSet< N >::const_iterator::bitSet private
Definition at line 156 of file MySet.hpp.
template<size_t N> uint64_t tdzdd::MyBitSet< N >::const_iterator::word private
Definition at line 159 of file MySet.hpp.
Referenced by tdzdd::MyBitSet< 0 >::hash(), and tdzdd::MyBitSet< 0 >::operator==().
template<size_t N> size_t tdzdd::MyBitSet< N >::const_iterator::wordPos private
Definition at line 157 of file MySet.hpp.
Referenced by tdzdd::MyBitSet< N >::const_iterator::operator==().
The documentation for this class was generated from the following file:
include/tdzdd/util/MySet.hpp