TdZdd: tdzdd::DdSweeper< ARITY > Class Template Reference
tdzdd::DdSweeper< ARITY > Class Template Reference
On-the-fly DD cleaner.
#include <DdSweeper.hpp>
Public Member Functions
DdSweeper (NodeTableEntity< ARITY > &diagram)
Constructor.
DdSweeper (NodeTableEntity< ARITY > &diagram, MyVector< NodeBranchId > &oneSrcPtr)
Constructor.
void setRoot (NodeId &root)
Set the root pointer.
void update (int current, int child, size_t count)
Updates status and sweeps the DD if necessary.
Private Attributes
NodeTableEntity< ARITY > & diagram
MyVector< NodeBranchId > * oneSrcPtr
MyVector< int > sweepLevel
MyVector< size_t > deadCount
size_t allCount
size_t maxCount
NodeId * rootPtr
Static Private Attributes
static size_t const SWEEP_RATIO = 20
Detailed Description
template<int ARITY>
class tdzdd::DdSweeper< ARITY >
On-the-fly DD cleaner.
Removes the nodes that are identified as equivalent to the 0-terminal while top-down DD construction.
Definition at line 43 of file DdSweeper.hpp.
Constructor & Destructor Documentation
template<int ARITY> tdzdd::DdSweeper< ARITY >::DdSweeper (NodeTableEntity< ARITY > & diagram) inline
Constructor.
Parameters
diagram the diagram to sweep.
Definition at line 60 of file DdSweeper.hpp.
template<int ARITY> tdzdd::DdSweeper< ARITY >::DdSweeper (NodeTableEntity< ARITY > & diagram, MyVector< NodeBranchId > & oneSrcPtr) inline
Constructor.
Parameters
diagram the diagram to sweep.
oneSrcPtr collection of node branch IDs.
Definition at line 69 of file DdSweeper.hpp.
Member Function Documentation
template<int ARITY> void tdzdd::DdSweeper< ARITY >::setRoot (NodeId & root) inline
Set the root pointer.
Parameters
root reference to the root ID storage.
Definition at line 82 of file DdSweeper.hpp.
Referenced by tdzdd::DdBuilder< S >::initialize(), tdzdd::DdBuilderMP< S >::initialize(), tdzdd::ZddSubsetter< S >::initialize(), and tdzdd::ZddSubsetterMP< S >::initialize().
template<int ARITY> void tdzdd::DdSweeper< ARITY >::update (int current, int child, size_t count) inline
Updates status and sweeps the DD if necessary.
Parameters
current current level.
child the level at which edges from this level are completed.
count the number of dead nodes at this level.
Definition at line 92 of file DdSweeper.hpp.
Referenced by tdzdd::DdBuilder< S >::construct(), tdzdd::DdBuilderMP< S >::construct(), tdzdd::ZddSubsetter< S >::subset(), and tdzdd::ZddSubsetterMP< S >::subset().
Member Data Documentation
template<int ARITY> size_t tdzdd::DdSweeper< ARITY >::allCount private
Definition at line 51 of file DdSweeper.hpp.
Referenced by tdzdd::DdSweeper< AR >::update().
template<int ARITY> MyVector<size_t> tdzdd::DdSweeper< ARITY >::deadCount private
Definition at line 50 of file DdSweeper.hpp.
template<int ARITY> NodeTableEntity<ARITY>& tdzdd::DdSweeper< ARITY >::diagram private
Definition at line 46 of file DdSweeper.hpp.
template<int ARITY> size_t tdzdd::DdSweeper< ARITY >::maxCount private
Definition at line 52 of file DdSweeper.hpp.
template<int ARITY> MyVector<NodeBranchId>* tdzdd::DdSweeper< ARITY >::oneSrcPtr private
Definition at line 47 of file DdSweeper.hpp.
template<int ARITY> NodeId* tdzdd::DdSweeper< ARITY >::rootPtr private
Definition at line 53 of file DdSweeper.hpp.
template<int ARITY> size_t const tdzdd::DdSweeper< ARITY >::SWEEP_RATIO = 20 static private
Definition at line 44 of file DdSweeper.hpp.
template<int ARITY> MyVector<int> tdzdd::DdSweeper< ARITY >::sweepLevel private
Definition at line 49 of file DdSweeper.hpp.
The documentation for this class was generated from the following file:
include/tdzdd/dd/DdSweeper.hpp