TdZdd: tdzdd::DdBuilderMP< S > Class Template Reference
tdzdd::DdBuilderMP< S > Class Template Reference
Multi-threaded breadth-first DD builder.
#include <DdBuilder.hpp>
Public Member Functions
DdBuilderMP (Spec const &s, NodeTableHandler< AR > &output, int n=0)
void schedule (NodeId *fp, int level, void *s)
Schedules a top-down event.
int initialize (NodeId &root)
Initializes the builder.
void construct (int i)
Builds one level.
Private Types
typedef S Spec
typedef MyHashTable< SpecNode *, Hasher< Spec >, Hasher< Spec > > UniqTable
Private Member Functions
void init (int n)
Private Attributes
int const threads
int const tasks
MyVector< Spec > specs
int const specNodeSize
NodeTableEntity< AR > & output
DdSweeper< AR > sweeper
MyVector< MyVector< MyVector< MyList< SpecNode > > > > snodeTables
Static Private Attributes
static int const AR = Spec::ARITY
static int const TASKS_PER_THREAD = 10
Static Private Attributes inherited from tdzdd::DdBuilderMPBase
static int const headerSize = 2
Additional Inherited Members
Static Private Member Functions inherited from tdzdd::DdBuilderMPBase
static NodeId *& srcPtr (SpecNode *p)
static int64_t & code (SpecNode *p)
static NodeId & nodeId (SpecNode *p)
static NodeId nodeId (SpecNode const *p)
static void * state (SpecNode *p)
static void const * state (SpecNode const *p)
static int getSpecNodeSize (int n)
Detailed Description
template<typename S>
class tdzdd::DdBuilderMP< S >
Multi-threaded breadth-first DD builder.
Definition at line 395 of file DdBuilder.hpp.
Member Typedef Documentation
template<typename S> typedef S tdzdd::DdBuilderMP< S >::Spec private
Definition at line 396 of file DdBuilder.hpp.
template<typename S> typedef MyHashTable<SpecNode*,Hasher<Spec>,Hasher<Spec> > tdzdd::DdBuilderMP< S >::UniqTable private
Definition at line 397 of file DdBuilder.hpp.
Constructor & Destructor Documentation
template<typename S> tdzdd::DdBuilderMP< S >::DdBuilderMP (Spec const & s, NodeTableHandler< AR > & output, int n = 0) inline
Definition at line 426 of file DdBuilder.hpp.
Member Function Documentation
template<typename S> void tdzdd::DdBuilderMP< S >::construct (int i) inline
Builds one level.
Parameters
i level.
Definition at line 494 of file DdBuilder.hpp.
References tdzdd::MyHashTable< T, Hash, Equal >::add(), tdzdd::MyList< T, BLOCK_ELEMENTS >::begin(), tdzdd::Node< ARITY >::branch, tdzdd::DdBuilderBase::SpecNode::code, tdzdd::MyVector< T, Size >::data(), tdzdd::MyList< T, BLOCK_ELEMENTS >::empty(), tdzdd::MyList< T, BLOCK_ELEMENTS >::end(), tdzdd::MyList< T, BLOCK_ELEMENTS >::front(), tdzdd::MyHashTable< T, Hash, Equal >::initialize(), tdzdd::DataTable< T >::initRow(), tdzdd::DataTable< T >::numRows(), tdzdd::MyList< T, BLOCK_ELEMENTS >::pop_front(), tdzdd::NodeTableEntity< ARITY >::size(), tdzdd::MyVector< T, Size >::size(), tdzdd::DdBuilderBase::SpecNode::srcPtr, tdzdd::ElapsedTimeCounter::start(), tdzdd::DdBuilderBase::state(), tdzdd::ElapsedTimeCounter::stop(), and tdzdd::DdSweeper< ARITY >::update().
Referenced by tdzdd::DdStructure< ARITY >::constructMP_().
template<typename S> void tdzdd::DdBuilderMP< S >::init (int n) inline private
Definition at line 415 of file DdBuilder.hpp.
References tdzdd::DataTable< T >::numRows(), tdzdd::MyVector< T, Size >::resize(), and tdzdd::DataTable< T >::setNumRows().
template<typename S> int tdzdd::DdBuilderMP< S >::initialize (NodeId & root) inline
Initializes the builder.
Parameters
root result storage.
Definition at line 471 of file DdBuilder.hpp.
References tdzdd::MyVector< T, Size >::data(), and tdzdd::DdSweeper< ARITY >::setRoot().
Referenced by tdzdd::DdStructure< ARITY >::constructMP_().
template<typename S> void tdzdd::DdBuilderMP< S >::schedule (NodeId * fp, int level, void * s) inline
Schedules a top-down event.
Parameters
fp result storage.
level node level of the event.
s node state of the event.
Definition at line 461 of file DdBuilder.hpp.
References tdzdd::DdBuilderBase::SpecNode::srcPtr, and tdzdd::DdBuilderBase::state().
Member Data Documentation
template<typename S> int const tdzdd::DdBuilderMP< S >::AR = Spec::ARITY static private
Definition at line 398 of file DdBuilder.hpp.
template<typename S> NodeTableEntity<AR>& tdzdd::DdBuilderMP< S >::output private
Definition at line 406 of file DdBuilder.hpp.
template<typename S> MyVector<MyVector<MyVector<MyList<SpecNode> > > > tdzdd::DdBuilderMP< S >::snodeTables private
Definition at line 409 of file DdBuilder.hpp.
template<typename S> int const tdzdd::DdBuilderMP< S >::specNodeSize private
Definition at line 405 of file DdBuilder.hpp.
template<typename S> MyVector<Spec> tdzdd::DdBuilderMP< S >::specs private
Definition at line 404 of file DdBuilder.hpp.
template<typename S> DdSweeper<AR> tdzdd::DdBuilderMP< S >::sweeper private
Definition at line 407 of file DdBuilder.hpp.
template<typename S> int const tdzdd::DdBuilderMP< S >::tasks private
Definition at line 402 of file DdBuilder.hpp.
template<typename S> int const tdzdd::DdBuilderMP< S >::TASKS_PER_THREAD = 10 static private
Definition at line 399 of file DdBuilder.hpp.
template<typename S> int const tdzdd::DdBuilderMP< S >::threads private
Definition at line 401 of file DdBuilder.hpp.
The documentation for this class was generated from the following file:
include/tdzdd/dd/DdBuilder.hpp