TdZdd: tdzdd::ZddSubsetterMP< S > Class Template Reference
tdzdd::ZddSubsetterMP< S > Class Template Reference
Multi-threaded breadth-first ZDD subset builder.
#include <DdBuilder.hpp>
Public Member Functions
ZddSubsetterMP (NodeTableHandler< AR > const &input, Spec const &s, NodeTableHandler< AR > &output)
int initialize (NodeId &root)
Initializes the builder.
void subset (int i)
Builds one level.
Private Types
typedef S Spec
typedef MyHashTable< SpecNode *, Hasher< Spec >, Hasher< Spec > > UniqTable
Private Member Functions
int downTable (NodeId &f, int b, int zerosupLevel) const
int downSpec (Spec &spec, void *p, int level, int b, int zerosupLevel)
Private Attributes
int const threads
MyVector< Spec > specs
int const specNodeSize
NodeTableEntity< AR > const & input
NodeTableEntity< AR > & output
DdSweeper< AR > sweeper
MyVector< MyVector< MyVector< MyListOnPool< SpecNode > > > > snodeTables
MyVector< MemoryPools > pools
Static Private Attributes
static int const AR = Spec::ARITY
Static Private Attributes inherited from tdzdd::DdBuilderMPBase
static int const headerSize = 2
Additional Inherited Members
Static Private Member Functions inherited from tdzdd::DdBuilderMPBase
static NodeId *& srcPtr (SpecNode *p)
static int64_t & code (SpecNode *p)
static NodeId & nodeId (SpecNode *p)
static NodeId nodeId (SpecNode const *p)
static void * state (SpecNode *p)
static void const * state (SpecNode const *p)
static int getSpecNodeSize (int n)
Detailed Description
template<typename S>
class tdzdd::ZddSubsetterMP< S >
Multi-threaded breadth-first ZDD subset builder.
Definition at line 958 of file DdBuilder.hpp.
Member Typedef Documentation
template<typename S> typedef S tdzdd::ZddSubsetterMP< S >::Spec private
Definition at line 960 of file DdBuilder.hpp.
template<typename S> typedef MyHashTable<SpecNode*,Hasher<Spec>,Hasher<Spec> > tdzdd::ZddSubsetterMP< S >::UniqTable private
Definition at line 961 of file DdBuilder.hpp.
Constructor & Destructor Documentation
template<typename S> tdzdd::ZddSubsetterMP< S >::ZddSubsetterMP (NodeTableHandler< AR > const & input, Spec const & s, NodeTableHandler< AR > & output) inline
Definition at line 976 of file DdBuilder.hpp.
Member Function Documentation
template<typename S> int tdzdd::ZddSubsetterMP< S >::downSpec (Spec & spec, void * p, int level, int b, int zerosupLevel) inline private
Definition at line 1231 of file DdBuilder.hpp.
template<typename S> int tdzdd::ZddSubsetterMP< S >::downTable (NodeId & f, int b, int zerosupLevel) const inline private
Definition at line 1221 of file DdBuilder.hpp.
References tdzdd::NodeTableEntity< ARITY >::child(), and tdzdd::NodeId::row().
template<typename S> int tdzdd::ZddSubsetterMP< S >::initialize (NodeId & root) inline
Initializes the builder.
Parameters
root the root node.
Definition at line 998 of file DdBuilder.hpp.
References tdzdd::NodeId::col(), tdzdd::MyVector< T, Size >::data(), tdzdd::NodeTableEntity< ARITY >::init(), tdzdd::MyVector< T, Size >::resize(), tdzdd::NodeId::row(), tdzdd::DdSweeper< ARITY >::setRoot(), tdzdd::DdBuilderBase::SpecNode::srcPtr, and tdzdd::DdBuilderBase::state().
Referenced by tdzdd::DdStructure< ARITY >::zddSubsetMP_().
template<typename S> void tdzdd::ZddSubsetterMP< S >::subset (int i) inline
Builds one level.
Parameters
i level.
Definition at line 1048 of file DdBuilder.hpp.
References tdzdd::MyHashTable< T, Hash, Equal >::add(), tdzdd::MyListOnPool< T >::begin(), tdzdd::Node< ARITY >::branch, tdzdd::MyVector< T, Size >::clear(), tdzdd::DdBuilderBase::SpecNode::code, tdzdd::NodeId::col(), tdzdd::MyVector< T, Size >::data(), tdzdd::MyListOnPool< T >::end(), tdzdd::MyHashTable< T, Hash, Equal >::initialize(), tdzdd::DataTable< T >::initRow(), tdzdd::DataTable< T >::numRows(), tdzdd::MyVector< T, Size >::resize(), tdzdd::NodeId::row(), tdzdd::NodeTableEntity< ARITY >::size(), tdzdd::MyListOnPool< T >::size(), tdzdd::DdBuilderBase::SpecNode::srcPtr, tdzdd::DdBuilderBase::state(), and tdzdd::DdSweeper< ARITY >::update().
Referenced by tdzdd::DdStructure< ARITY >::zddSubsetMP_().
Member Data Documentation
template<typename S> int const tdzdd::ZddSubsetterMP< S >::AR = Spec::ARITY static private
Definition at line 962 of file DdBuilder.hpp.
template<typename S> NodeTableEntity<AR> const& tdzdd::ZddSubsetterMP< S >::input private
Definition at line 968 of file DdBuilder.hpp.
template<typename S> NodeTableEntity<AR>& tdzdd::ZddSubsetterMP< S >::output private
Definition at line 969 of file DdBuilder.hpp.
template<typename S> MyVector<MemoryPools> tdzdd::ZddSubsetterMP< S >::pools private
Definition at line 973 of file DdBuilder.hpp.
template<typename S> MyVector<MyVector<MyVector<MyListOnPool<SpecNode> > > > tdzdd::ZddSubsetterMP< S >::snodeTables private
Definition at line 972 of file DdBuilder.hpp.
template<typename S> int const tdzdd::ZddSubsetterMP< S >::specNodeSize private
Definition at line 967 of file DdBuilder.hpp.
template<typename S> MyVector<Spec> tdzdd::ZddSubsetterMP< S >::specs private
Definition at line 966 of file DdBuilder.hpp.
template<typename S> DdSweeper<AR> tdzdd::ZddSubsetterMP< S >::sweeper private
Definition at line 970 of file DdBuilder.hpp.
template<typename S> int const tdzdd::ZddSubsetterMP< S >::threads private
Definition at line 964 of file DdBuilder.hpp.
The documentation for this class was generated from the following file:
include/tdzdd/dd/DdBuilder.hpp