TdZdd: tdzdd::MyBitSet< N > Class Template Reference
tdzdd::MyBitSet< N > Class Template Reference
#include <MySet.hpp>
Classes
class const_iterator
Public Member Functions
MyBitSet (uint64_t n=0)
size_t numWords () const
Gets the number of words for a bit vector.
void clear ()
Initializes the set to be empty.
bool empty () const
Checks if the set is empty.
void add (size_t i)
Adds the i-th element.
void remove (size_t i)
Removes the i-th element.
void pullout (size_t i)
Removes the i-th entry and shifts all behind it front by one.
bool includes (size_t i) const
Checks if the i-th element is included.
bool intersects (MyBitSet const &o) const
Checks non-emptiness of the intersection of two bit-vectors.
const_iterator begin () const
Returns an iterator to the beginning.
const_iterator end () const
Returns an iterator to the end.
size_t hash () const
Gets the hash code of this object.
bool operator== (MyBitSet const &o) const
Checks equivalence between another object.
Private Member Functions
uint64_t & word (size_t i)
uint64_t word (size_t i) const
uint64_t mask (size_t i) const
Private Attributes
uint64_t array_ [(N==0)?1:N]
Static Private Attributes
static size_t const offset = (N == 0) ? 1 : 0
Friends
std::ostream & operator<< (std::ostream &os, MyBitSet const &o)
Sends an object to an output stream.
Detailed Description
template<size_t N>
class tdzdd::MyBitSet< N >
Definition at line 38 of file MySet.hpp.
Constructor & Destructor Documentation
template<size_t N> tdzdd::MyBitSet< N >::MyBitSet (uint64_t n = 0) inline
Definition at line 58 of file MySet.hpp.
Member Function Documentation
template<size_t N> void tdzdd::MyBitSet< N >::add (size_t i) inline
Adds the i-th element.
Parameters
i element number.
Definition at line 98 of file MySet.hpp.
template<size_t N> const_iterator tdzdd::MyBitSet< N >::begin () const inline
Returns an iterator to the beginning.
Returns
iterator to the beginning.
Definition at line 222 of file MySet.hpp.
Referenced by tdzdd::MySmallSet< T, 0 >::containsAll(), tdzdd::MySmallSet< T, 0 >::equals(), and tdzdd::MySmallSet< T, 0 >::intersects().
template<size_t N> void tdzdd::MyBitSet< N >::clear () inline
Initializes the set to be empty.
The memory is deallocated.
Definition at line 77 of file MySet.hpp.
template<size_t N> bool tdzdd::MyBitSet< N >::empty () const inline
Checks if the set is empty.
Returns
true if empty.
Definition at line 87 of file MySet.hpp.
template<size_t N> const_iterator tdzdd::MyBitSet< N >::end () const inline
Returns an iterator to the end.
Returns
iterator to the end.
Definition at line 230 of file MySet.hpp.
Referenced by tdzdd::MyBitSet< 0 >::begin(), tdzdd::MySmallSet< T, 0 >::containsAll(), tdzdd::MySmallSet< T, 0 >::equals(), and tdzdd::MySmallSet< T, 0 >::intersects().
template<size_t N> size_t tdzdd::MyBitSet< N >::hash () const inline
Gets the hash code of this object.
Returns
the hash code.
Definition at line 238 of file MySet.hpp.
template<size_t N> bool tdzdd::MyBitSet< N >::includes (size_t i) const inline
Checks if the i-th element is included.
Parameters
i element number.
Returns
true if the i-th element is included.
Definition at line 136 of file MySet.hpp.
template<size_t N> bool tdzdd::MyBitSet< N >::intersects (MyBitSet< N > const & o) const inline
Checks non-emptiness of the intersection of two bit-vectors.
Parameters
o the other bit-vector.
Returns
true if the intersection is not empty.
Definition at line 147 of file MySet.hpp.
template<size_t N> uint64_t tdzdd::MyBitSet< N >::mask (size_t i) const inline private
Definition at line 53 of file MySet.hpp.
Referenced by tdzdd::MyBitSet< 0 >::add(), tdzdd::MyBitSet< 0 >::includes(), tdzdd::MyBitSet< 0 >::pullout(), and tdzdd::MyBitSet< 0 >::remove().
template<size_t N> size_t tdzdd::MyBitSet< N >::numWords () const inline
Gets the number of words for a bit vector.
Returns
the number of words.
Definition at line 69 of file MySet.hpp.
Referenced by tdzdd::MyBitSet< 0 >::begin(), tdzdd::MyBitSet< 0 >::clear(), tdzdd::MyBitSet< 0 >::empty(), tdzdd::MyBitSet< 0 >::hash(), tdzdd::MyBitSet< 0 >::intersects(), tdzdd::MyBitSet< 0 >::MyBitSet(), tdzdd::MyBitSet< N >::const_iterator::operator++(), tdzdd::MyBitSet< 0 >::operator==(), tdzdd::MyBitSet< 0 >::pullout(), and tdzdd::MyBitSet< 0 >::word().
template<size_t N> bool tdzdd::MyBitSet< N >::operator== (MyBitSet< N > const & o) const inline
Checks equivalence between another object.
Parameters
o another object.
Returns
true if equivalent.
Definition at line 252 of file MySet.hpp.
template<size_t N> void tdzdd::MyBitSet< N >::pullout (size_t i) inline
Removes the i-th entry and shifts all behind it front by one.
Parameters
i element number.
Definition at line 119 of file MySet.hpp.
template<size_t N> void tdzdd::MyBitSet< N >::remove (size_t i) inline
Removes the i-th element.
Parameters
i element number.
Definition at line 108 of file MySet.hpp.
template<size_t N> uint64_t& tdzdd::MyBitSet< N >::word (size_t i) inline private
Definition at line 43 of file MySet.hpp.
Referenced by tdzdd::MyBitSet< 0 >::add(), tdzdd::MyBitSet< 0 >::clear(), tdzdd::MyBitSet< 0 >::empty(), tdzdd::MyBitSet< 0 >::includes(), tdzdd::MyBitSet< 0 >::intersects(), tdzdd::MyBitSet< 0 >::MyBitSet(), tdzdd::MyBitSet< N >::const_iterator::operator++(), tdzdd::MyBitSet< 0 >::operator==(), tdzdd::MyBitSet< 0 >::pullout(), and tdzdd::MyBitSet< 0 >::remove().
template<size_t N> uint64_t tdzdd::MyBitSet< N >::word (size_t i) const inline private
Definition at line 48 of file MySet.hpp.
Friends And Related Function Documentation
template<size_t N> std::ostream& operator<< (std::ostream & os, MyBitSet< N > const & o) friend
Sends an object to an output stream.
Parameters
os the output stream.
o the object.
Returns
os.
Definition at line 267 of file MySet.hpp.
Member Data Documentation
template<size_t N> uint64_t tdzdd::MyBitSet< N >::array_[(N==0)?1:N] private
Definition at line 41 of file MySet.hpp.
Referenced by tdzdd::MySmallSet< T, 0 >::add(), tdzdd::MySmallSet< T, 0 >::begin(), tdzdd::MySmallSet< T, 0 >::end(), tdzdd::MySmallSet< T, 0 >::get(), tdzdd::MySmallSet< T, 0 >::hash(), tdzdd::MySmallSet< T, 0 >::includes(), tdzdd::MyBitSet< 0 >::MyBitSet(), tdzdd::MyBitSet< 0 >::numWords(), tdzdd::MySmallSet< T, 0 >::operator==(), tdzdd::MySmallSet< T, 0 >::rbegin(), tdzdd::MySmallSet< T, 0 >::remove(), tdzdd::MySmallSet< T, 0 >::rend(), and tdzdd::MyBitSet< 0 >::word().
template<size_t N> size_t const tdzdd::MyBitSet< N >::offset = (N == 0) ? 1 : 0 static private
Definition at line 39 of file MySet.hpp.
Referenced by tdzdd::MyBitSet< 0 >::word().
The documentation for this class was generated from the following file:
include/tdzdd/util/MySet.hpp