TdZdd: tdzdd::DdBuilderBase Class Reference
tdzdd::DdBuilderBase Class Reference
#include <DdBuilder.hpp>
Classes
struct Hasher
union SpecNode
Static Protected Member Functions
static NodeId *& srcPtr (SpecNode *p)
static int64_t & code (SpecNode *p)
static NodeId & nodeId (SpecNode *p)
static void * state (SpecNode *p)
static void const * state (SpecNode const *p)
static int getSpecNodeSize (int n)
Static Protected Attributes
static int const headerSize = 1
Detailed Description
Definition at line 48 of file DdBuilder.hpp.
Member Function Documentation
static int64_t& tdzdd::DdBuilderBase::code (SpecNode * p) inline static protected
Definition at line 67 of file DdBuilder.hpp.
References tdzdd::DdBuilderBase::SpecNode::code.
static int tdzdd::DdBuilderBase::getSpecNodeSize (int n) inline static protected
Definition at line 83 of file DdBuilder.hpp.
static NodeId& tdzdd::DdBuilderBase::nodeId (SpecNode * p) inline static protected
Definition at line 71 of file DdBuilder.hpp.
References tdzdd::DdBuilderBase::SpecNode::code.
Referenced by tdzdd::DdBuilder< S >::construct(), tdzdd::DdDumper< S >::dump(), tdzdd::DdDumper< S >::dumpStep(), and tdzdd::ZddSubsetter< S >::subset().
static NodeId*& tdzdd::DdBuilderBase::srcPtr (SpecNode * p) inline static protected
Definition at line 63 of file DdBuilder.hpp.
References tdzdd::DdBuilderBase::SpecNode::srcPtr.
static void* tdzdd::DdBuilderBase::state (SpecNode * p) inline static protected
Definition at line 75 of file DdBuilder.hpp.
References headerSize.
Referenced by tdzdd::DdBuilder< S >::construct(), tdzdd::DdBuilderMP< S >::construct(), tdzdd::DdDumper< S >::dump(), tdzdd::DdDumper< S >::dumpStep(), tdzdd::ZddSubsetter< S >::initialize(), tdzdd::ZddSubsetterMP< S >::initialize(), tdzdd::DdBuilderBase::Hasher< SPEC >::operator()(), tdzdd::DdBuilderMPBase::Hasher< SPEC >::operator()(), tdzdd::DdDumper< S >::Hasher< Spec >::operator()(), tdzdd::DdBuilder< S >::schedule(), tdzdd::DdBuilderMP< S >::schedule(), tdzdd::ZddSubsetter< S >::subset(), and tdzdd::ZddSubsetterMP< S >::subset().
static void const* tdzdd::DdBuilderBase::state (SpecNode const * p) inline static protected
Definition at line 79 of file DdBuilder.hpp.
References headerSize.
Member Data Documentation
int const tdzdd::DdBuilderBase::headerSize = 1 static protected
Definition at line 50 of file DdBuilder.hpp.
Referenced by state(), tdzdd::DdBuilderMPBase::state(), and tdzdd::DdDumper< S >::state().
The documentation for this class was generated from the following file:
include/tdzdd/dd/DdBuilder.hpp