TdZdd: tdzdd Namespace Reference
tdzdd Namespace Reference
Classes
struct BddAnd
struct BddAnd_
struct BddAnd_< S, S1, S2 >
struct BddCardinality
BDD evaluator that counts the number of elements.
class BddLookahead
struct BddOr
struct BddOr_
struct BddOr_< S, S1, S2 >
struct BddUnreduction
class BigNumber
class BinaryOperation
class CardinalityBase
class CardinalityBase< E, std::string, ARITY, BDD >
struct CycleZdd
class DataTable
class DdBuilder
Basic breadth-first DD builder.
class DdBuilderBase
class DdBuilderMP
Multi-threaded breadth-first DD builder.
class DdBuilderMPBase
class DdDumper
DD dumper.
class DdEval
Base class of DD evaluators.
class DdReducer
class DdSpec
Abstract class of DD specifications using scalar states.
class DdSpecBase
Base class of DD specs.
class DdStructure
Ordered n-ary decision diagram structure.
class DdSweeper
On-the-fly DD cleaner.
class DdValues
Collection of child node values/levels for DdEval::evalNode function interface.
class DegreeConstraint
class DepthFirstSearcher
class ElapsedTimeCounter
class FixedBigNumber
class FrontierBasedSearch
struct FrontierBasedSearchCount
class FrontierBasedSearchMate
class Graph
class GraphillionZdd
struct HamiltonCycleZdd
struct HamiltonPathZdd
class HybridDdSpec
Abstract class of DD specifications using both scalar and POD array states.
struct InitializedNode
class IntRange
struct IntSubset
class LinearConstraints
class MemoryPool
Memory pool.
class MessageHandler_
class MyBitSet
class MyBitSetOnPool
class MyHashConstant
struct MyHashDefault
struct MyHashDefault< int16_t >
struct MyHashDefault< int32_t >
struct MyHashDefault< int64_t >
struct MyHashDefault< int8_t >
struct MyHashDefault< T * >
struct MyHashDefault< uint16_t >
struct MyHashDefault< uint32_t >
struct MyHashDefault< uint64_t >
struct MyHashDefault< uint8_t >
struct MyHashDefaultForInt
struct MyHashMap
Closed hash map implementation.
struct MyHashMapEntry
Entry for a hash map.
class MyHashMapHashWrapper
class MyHashTable
Closed hash table implementation.
class MyList
class MyListOnPool
class MySmallSet
class MySmallSetOnPool
class MyVector
struct Node
struct NodeBranchId
class NodeId
class NodeTableEntity
class NodeTableHandler
class PathCounter
struct PathZdd
struct PathZddByStdMap
class PodArrayDdSpec
Abstract class of DD specifications using POD array states.
class PodHybridDdSpec
struct ResourceUsage
class SapporoZdd
ZBDD wrapper.
class SimpathBasedImpl
class SizeConstraint
class StatelessDdSpec
Abstract class of DD specifications without states.
struct ToZBDD
Exporter to ZBDD.
class Unreduction_
struct ZddCardinality
ZDD evaluator that counts the number of elements.
struct ZddIntersection
struct ZddIntersection_
struct ZddIntersection_< S, S1, S2 >
class ZddLookahead
class ZddSubsetter
Breadth-first ZDD subset builder.
class ZddSubsetterMP
Multi-threaded breadth-first ZDD subset builder.
struct ZddUnion
struct ZddUnion_
struct ZddUnion_< S, S1, S2 >
struct ZddUnreduction
Typedefs
typedef MyVector< MemoryPool > MemoryPools
Collection of memory pools.
typedef MessageHandler_< std::cerr > MessageHandler
Enumerations
enum SimpathBasedImplType { Path, Cycle }
Functions
template<typename S >
std::string countPaths (S &spec, bool fast=false)
Counts the number of paths from the root to the 1-terminal without building entire DD structure.
template<typename S >
uint64_t countPaths64 (S &spec)
Counts the number of paths from the root to the 1-terminal without building entire DD structure.
template<typename S1 , typename S2 >
BddAnd< S1, S2 > bddAnd (S1 const &spec1, S2 const &spec2)
Returns a BDD specification for logical AND of two BDD specifications.
template<typename... SS>
BddAnd< SS... > bddAnd (SS const &...specs)
Returns a BDD specification for logical AND of two or more BDD specifications.
template<typename S1 , typename S2 >
BddOr< S1, S2 > bddOr (S1 const &spec1, S2 const &spec2)
Returns a BDD specification for logical OR of two BDD specifications.
template<typename... SS>
BddOr< SS... > bddOr (SS const &...specs)
Returns a BDD specification for logical OR of two or more BDD specifications.
template<typename S1 , typename S2 >
ZddIntersection< S1, S2 > zddIntersection (S1 const &spec1, S2 const &spec2)
Returns a ZDD specification for set intersection of two ZDD specifications.
template<typename... SS>
ZddIntersection< SS... > zddIntersection (SS const &...specs)
Returns a ZDD specification for set intersection of two or more ZDD specifications.
template<typename S1 , typename S2 >
ZddUnion< S1, S2 > zddUnion (S1 const &spec1, S2 const &spec2)
Returns a ZDD specification for set union of two ZDD specifications.
template<typename... SS>
ZddUnion< SS... > zddUnion (SS const &...specs)
Returns a ZDD specification for set union of two or more ZDD specifications.
template<typename S >
BddLookahead< S > bddLookahead (S const &spec)
Optimizes a BDD specification in terms of the BDD node deletion rule.
template<typename S >
ZddLookahead< S > zddLookahead (S const &spec)
Optimizes a ZDD specification in terms of the ZDD node deletion rule.
template<typename S >
BddUnreduction< S > bddUnreduction (S const &spec, int numVars)
Creates a QDD specification from a BDD specification by complementing skipped nodes in terms of the BDD node deletion rule.
template<typename S >
ZddUnreduction< S > zddUnreduction (S const &spec, int numVars)
Creates a QDD specification from a ZDD specification by complementing skipped nodes in terms of the ZDD node deletion rule.
std::string demangle (char const *name)
std::string demangleTypename (char const *name)
template<typename T >
std::string typenameof ()
template<typename T >
std::string typenameof (T const &obj)
std::string capitalize (std::string const &s)
template<typename T >
std::string to_string (T const &o)
double getWallClockTime ()
Variables
int const NODE_ROW_BITS = 20
int const NODE_ATTR_BITS = 1
int const NODE_COL_BITS = 64 - NODE_ROW_BITS - NODE_ATTR_BITS
int const NODE_ROW_OFFSET = NODE_COL_BITS + NODE_ATTR_BITS
int const NODE_ATTR_OFFSET = NODE_COL_BITS
uint64_t const NODE_ROW_MAX = (uint64_t(1) << NODE_ROW_BITS) - 1
uint64_t const NODE_COL_MAX = (uint64_t(1) << NODE_COL_BITS) - 1
uint64_t const NODE_ROW_MASK = NODE_ROW_MAX << NODE_ROW_OFFSET
uint64_t const NODE_ATTR_MASK = uint64_t(1) << NODE_ATTR_OFFSET
Typedef Documentation
typedef MyVector<MemoryPool> tdzdd::MemoryPools
Collection of memory pools.
Definition at line 230 of file MemoryPool.hpp.
typedef MessageHandler_<std::cerr> tdzdd::MessageHandler
Definition at line 269 of file MessageHandler.hpp.
Enumeration Type Documentation
enum tdzdd::SimpathBasedImplType
Enumerator
Path
Cycle
Definition at line 34 of file PathZdd.hpp.
Function Documentation
template<typename S1 , typename S2 > BddAnd<S1,S2> tdzdd::bddAnd (S1 const & spec1, S2 const & spec2)
Returns a BDD specification for logical AND of two BDD specifications.
Parameters
spec1 the first BDD specification.
spec2 the second BDD specification.
Returns
BDD specification for logical AND of spec1 and spec2.
Definition at line 40 of file DdSpecOp.hpp.
template<typename... SS> BddAnd<SS...> tdzdd::bddAnd (SS const &... specs)
Returns a BDD specification for logical AND of two or more BDD specifications.
(since C++11)
Parameters
specs BDD specifications.
Returns
BDD specification for logical AND of specs.
Definition at line 52 of file DdSpecOp.hpp.
template<typename S > BddLookahead<S> tdzdd::bddLookahead (S const & spec)
Optimizes a BDD specification in terms of the BDD node deletion rule.
Parameters
spec original BDD specification.
Returns
optimized BDD specification.
Definition at line 135 of file DdSpecOp.hpp.
template<typename S1 , typename S2 > BddOr<S1,S2> tdzdd::bddOr (S1 const & spec1, S2 const & spec2)
Returns a BDD specification for logical OR of two BDD specifications.
Parameters
spec1 the first BDD specification.
spec2 the second BDD specification.
Returns
BDD specification for logical OR of spec1 and spec2.
Definition at line 64 of file DdSpecOp.hpp.
template<typename... SS> BddOr<SS...> tdzdd::bddOr (SS const &... specs)
Returns a BDD specification for logical OR of two or more BDD specifications.
(since C++11)
Parameters
specs BDD specifications.
Returns
BDD specification for logical OR of specs.
Definition at line 76 of file DdSpecOp.hpp.
template<typename S > BddUnreduction<S> tdzdd::bddUnreduction (S const & spec, int numVars)
Creates a QDD specification from a BDD specification by complementing skipped nodes in terms of the BDD node deletion rule.
Parameters
spec BDD specification.
Returns
QDD specification.
Definition at line 156 of file DdSpecOp.hpp.
std::string tdzdd::capitalize (std::string const & s) inline
Definition at line 37 of file MessageHandler.hpp.
Referenced by tdzdd::MessageHandler_< os >::begin(), and tdzdd::MessageHandler_< os >::end().
template<typename S > std::string tdzdd::countPaths (S & spec, bool fast = false)
Counts the number of paths from the root to the 1-terminal without building entire DD structure.
This function uses arbitrary-precision integer for counting.
Parameters
spec DD specification.
fast true to select a faster algorithm instead of a memory-efficient one.
Definition at line 443 of file PathCounter.hpp.
References tdzdd::PathCounter< S >::count(), and tdzdd::PathCounter< S >::countFast().
template<typename S > uint64_t tdzdd::countPaths64 (S & spec)
Counts the number of paths from the root to the 1-terminal without building entire DD structure.
This function uses unsigned 64-bit integer for counting.
Parameters
spec DD specification.
Definition at line 455 of file PathCounter.hpp.
References tdzdd::PathCounter< S >::count64(), and tdzdd::PathCounter< S >::Hasher::spec.
std::string tdzdd::demangle (char const * name) inline
Definition at line 37 of file demangle.hpp.
Referenced by demangleTypename().
std::string tdzdd::demangleTypename (char const * name) inline
Definition at line 63 of file demangle.hpp.
References demangle().
Referenced by typenameof().
double tdzdd::getWallClockTime () inline
Definition at line 45 of file ResourceUsage.hpp.
Referenced by tdzdd::ElapsedTimeCounter::start(), tdzdd::ElapsedTimeCounter::stop(), and tdzdd::ResourceUsage::update().
template<typename T > std::string tdzdd::to_string (T const & o) inline
Definition at line 46 of file MessageHandler.hpp.
Referenced by tdzdd::MessageHandler_< os >::end().
template<typename T > std::string tdzdd::typenameof ()
Definition at line 90 of file demangle.hpp.
References demangleTypename().
Referenced by tdzdd::DdStructure< ARITY >::construct_(), tdzdd::DdStructure< ARITY >::constructMP_(), tdzdd::PathCounter< S >::count(), tdzdd::PathCounter< S >::count64(), tdzdd::PathCounter< S >::countFast(), tdzdd::DdStructure< ARITY >::evaluate(), tdzdd::DdStructure< ARITY >::zddSubset_(), and tdzdd::DdStructure< ARITY >::zddSubsetMP_().
template<typename T > std::string tdzdd::typenameof (T const & obj)
Definition at line 95 of file demangle.hpp.
References demangleTypename().
template<typename S1 , typename S2 > ZddIntersection<S1,S2> tdzdd::zddIntersection (S1 const & spec1, S2 const & spec2)
Returns a ZDD specification for set intersection of two ZDD specifications.
Parameters
spec1 the first ZDD specification.
spec2 the second ZDD specification.
Returns
ZDD specification for set intersection of spec1 and spec2.
Definition at line 88 of file DdSpecOp.hpp.
template<typename... SS> ZddIntersection<SS...> tdzdd::zddIntersection (SS const &... specs)
Returns a ZDD specification for set intersection of two or more ZDD specifications.
(since C++11)
Parameters
specs ZDD specifications.
Returns
ZDD specification for set intersection of specs.
Definition at line 100 of file DdSpecOp.hpp.
template<typename S > ZddLookahead<S> tdzdd::zddLookahead (S const & spec)
Optimizes a ZDD specification in terms of the ZDD node deletion rule.
Parameters
spec original ZDD specification.
Returns
optimized ZDD specification.
Definition at line 145 of file DdSpecOp.hpp.
template<typename S1 , typename S2 > ZddUnion<S1,S2> tdzdd::zddUnion (S1 const & spec1, S2 const & spec2)
Returns a ZDD specification for set union of two ZDD specifications.
Parameters
spec1 the first ZDD specification.
spec2 the second ZDD specification.
Returns
ZDD specification for set union of spec1 and spec2.
Definition at line 112 of file DdSpecOp.hpp.
template<typename... SS> ZddUnion<SS...> tdzdd::zddUnion (SS const &... specs)
Returns a ZDD specification for set union of two or more ZDD specifications.
(since C++11)
Parameters
specs specifications.
Returns
ZDD specification for set union of specs.
Definition at line 124 of file DdSpecOp.hpp.
template<typename S > ZddUnreduction<S> tdzdd::zddUnreduction (S const & spec, int numVars)
Creates a QDD specification from a ZDD specification by complementing skipped nodes in terms of the ZDD node deletion rule.
Parameters
spec ZDD specification.
Returns
QDD specification.
Definition at line 167 of file DdSpecOp.hpp.
Variable Documentation
int const tdzdd::NODE_ATTR_BITS = 1
Definition at line 34 of file Node.hpp.
uint64_t const tdzdd::NODE_ATTR_MASK = uint64_t(1) << NODE_ATTR_OFFSET
Definition at line 44 of file Node.hpp.
Referenced by tdzdd::NodeId::setAttr().
int const tdzdd::NODE_ATTR_OFFSET = NODE_COL_BITS
Definition at line 38 of file Node.hpp.
int const tdzdd::NODE_COL_BITS = 64 - NODE_ROW_BITS - NODE_ATTR_BITS
Definition at line 35 of file Node.hpp.
uint64_t const tdzdd::NODE_COL_MAX = (uint64_t(1) << NODE_COL_BITS) - 1
Definition at line 41 of file Node.hpp.
Referenced by tdzdd::NodeId::col().
int const tdzdd::NODE_ROW_BITS = 20
Definition at line 33 of file Node.hpp.
uint64_t const tdzdd::NODE_ROW_MASK = NODE_ROW_MAX << NODE_ROW_OFFSET
Definition at line 43 of file Node.hpp.
uint64_t const tdzdd::NODE_ROW_MAX = (uint64_t(1) << NODE_ROW_BITS) - 1
Definition at line 40 of file Node.hpp.
int const tdzdd::NODE_ROW_OFFSET = NODE_COL_BITS + NODE_ATTR_BITS
Definition at line 37 of file Node.hpp.
Referenced by tdzdd::NodeId::row().