TdZdd: tdzdd::PathCounter< S >::Hasher Struct Reference
tdzdd::PathCounter< S >::Hasher Struct Reference
Public Member Functions
Hasher (Spec const &spec, int level)
size_t operator() (Word const *p) const
size_t operator() (Word const *p, Word const *q) const
Public Attributes
Spec const & spec
int const level
Detailed Description
template<typename S>
struct tdzdd::PathCounter< S >::Hasher
Definition at line 51 of file PathCounter.hpp.
Constructor & Destructor Documentation
template<typename S> tdzdd::PathCounter< S >::Hasher::Hasher (Spec const & spec, int level) inline
Definition at line 55 of file PathCounter.hpp.
Referenced by tdzdd::PathCounter< S >::count(), and tdzdd::PathCounter< S >::count64().
Member Function Documentation
template<typename S> size_t tdzdd::PathCounter< S >::Hasher::operator() (Word const * p) const inline
Definition at line 59 of file PathCounter.hpp.
References tdzdd::PathCounter< S >::state().
template<typename S> size_t tdzdd::PathCounter< S >::Hasher::operator() (Word const * p, Word const * q) const inline
Definition at line 63 of file PathCounter.hpp.
References tdzdd::PathCounter< S >::state().
Member Data Documentation
template<typename S> int const tdzdd::PathCounter< S >::Hasher::level
Definition at line 53 of file PathCounter.hpp.
template<typename S> Spec const& tdzdd::PathCounter< S >::Hasher::spec
Definition at line 52 of file PathCounter.hpp.
Referenced by tdzdd::countPaths64().
The documentation for this struct was generated from the following file:
include/tdzdd/dd/PathCounter.hpp