TdZdd: tdzdd::IntSubset Struct Reference
tdzdd::IntSubset Struct Reference abstract
#include <IntSubset.hpp>
Public Member Functions
virtual ~IntSubset ()
virtual bool contains (int x) const =0
virtual int lowerBound () const
virtual int upperBound () const
Detailed Description
Definition at line 31 of file IntSubset.hpp.
Constructor & Destructor Documentation
virtual tdzdd::IntSubset::~IntSubset () inline virtual
Definition at line 32 of file IntSubset.hpp.
References contains().
Member Function Documentation
virtual bool tdzdd::IntSubset::contains (int x) const pure virtual
Implemented in tdzdd::IntRange.
Referenced by tdzdd::SizeConstraint::getChild(), tdzdd::DegreeConstraint::leavable(), tdzdd::DegreeConstraint::takable(), and ~IntSubset().
virtual int tdzdd::IntSubset::lowerBound () const inline virtual
Reimplemented in tdzdd::IntRange.
Definition at line 37 of file IntSubset.hpp.
virtual int tdzdd::IntSubset::upperBound () const inline virtual
Reimplemented in tdzdd::IntRange.
Definition at line 41 of file IntSubset.hpp.
Referenced by tdzdd::SizeConstraint::getChild(), and tdzdd::DegreeConstraint::takable().
The documentation for this struct was generated from the following file:
include/tdzdd/util/IntSubset.hpp