TdZdd: tdzdd::ZddIntersection_< S, S1, S2 > Struct Template Reference
tdzdd::ZddIntersection_< S, S1, S2 > Struct Template Reference
#include <BinaryOperation.hpp>
Public Types
typedef S1 Spec1
typedef S2 Spec2
typedef size_t Word
Public Types inherited from tdzdd::PodArrayDdSpec< S, size_t, 2 >
typedef size_t State
Public Member Functions
void * state1 (void *p) const
void const * state1 (void const *p) const
void * state2 (void *p) const
void const * state2 (void const *p) const
ZddIntersection_ (S1 const &s1, S2 const &s2)
int getRoot (Word *p)
int getChild (Word *p, int level, int take)
void get_copy (void *to, void const *from)
int merge_states (void *p1, void *p2)
void destruct (void *p)
void destructLevel (int level)
size_t hash_code (void const *p, int level) const
bool equal_to (void const *p, void const *q, int level) const
void print_state (std::ostream &os, void const *p, int level) const
Public Member Functions inherited from tdzdd::PodArrayDdSpec< S, size_t, 2 >
PodArrayDdSpec ()
int datasize () const
int get_root (void *p)
int get_child (void *p, int level, int value)
void get_copy (void *to, void const *from)
int mergeStates (size_t *a1, size_t *a2)
int merge_states (void *p1, void *p2)
void destruct (void *p)
void destructLevel (int level)
size_t hash_code (void const *p, int level) const
bool equal_to (void const *p, void const *q, int level) const
void printState (std::ostream &os, State const *a) const
void printStateAtLevel (std::ostream &os, State const *a, int level) const
void print_state (std::ostream &os, void const *p, int level) const
Public Member Functions inherited from tdzdd::DdSpecBase< S, AR >
S & entity ()
S const & entity () const
void printLevel (std::ostream &os, int level) const
std::vector< std::pair< int, int > > findOneInstance () const
Returns a random instance using simple depth-first search without caching.
void dumpDot (std::ostream &os=std::cout, std::string title=typenameof< S >()) const
Dumps the node table in Graphviz (dot) format.
Static Public Member Functions
static int wordSize (int size)
Public Attributes
Spec1 spec1
Spec2 spec2
int const stateWords1
int const stateWords2
Additional Inherited Members
Static Public Attributes inherited from tdzdd::DdSpecBase< S, AR >
static int const ARITY = AR
Protected Member Functions inherited from tdzdd::PodArrayDdSpec< S, size_t, 2 >
void setArraySize (int n)
int getArraySize () const
Static Protected Member Functions inherited from tdzdd::DdSpecBase< S, AR >
template<typename T >
static size_t rawHashCode (T const &o)
template<typename T >
static size_t rawEqualTo (T const &o1, T const &o2)
Detailed Description
template<typename S, typename S1, typename S2>
struct tdzdd::ZddIntersection_< S, S1, S2 >
Definition at line 303 of file BinaryOperation.hpp.
Member Typedef Documentation
template<typename S , typename S1 , typename S2 > typedef S1 tdzdd::ZddIntersection_< S, S1, S2 >::Spec1
Definition at line 308 of file BinaryOperation.hpp.
template<typename S , typename S1 , typename S2 > typedef S2 tdzdd::ZddIntersection_< S, S1, S2 >::Spec2
Definition at line 309 of file BinaryOperation.hpp.
template<typename S , typename S1 , typename S2 > typedef size_t tdzdd::ZddIntersection_< S, S1, S2 >::Word
Definition at line 310 of file BinaryOperation.hpp.
Constructor & Destructor Documentation
template<typename S , typename S1 , typename S2 > tdzdd::ZddIntersection_< S, S1, S2 >::ZddIntersection_ (S1 const & s1, S2 const & s2) inline
Definition at line 338 of file BinaryOperation.hpp.
Member Function Documentation
template<typename S , typename S1 , typename S2 > void tdzdd::ZddIntersection_< S, S1, S2 >::destruct (void * p) inline
Definition at line 396 of file BinaryOperation.hpp.
References tdzdd::BinaryOperation< S, S1, S2 >::state1(), and tdzdd::BinaryOperation< S, S1, S2 >::state2().
template<typename S , typename S1 , typename S2 > void tdzdd::ZddIntersection_< S, S1, S2 >::destructLevel (int level) inline
Definition at line 401 of file BinaryOperation.hpp.
template<typename S , typename S1 , typename S2 > bool tdzdd::ZddIntersection_< S, S1, S2 >::equal_to (void const * p, void const * q, int level) const inline
Definition at line 411 of file BinaryOperation.hpp.
References tdzdd::BinaryOperation< S, S1, S2 >::state1(), and tdzdd::BinaryOperation< S, S1, S2 >::state2().
template<typename S , typename S1 , typename S2 > void tdzdd::ZddIntersection_< S, S1, S2 >::get_copy (void * to, void const * from) inline
Definition at line 386 of file BinaryOperation.hpp.
References tdzdd::BinaryOperation< S, S1, S2 >::state1(), and tdzdd::BinaryOperation< S, S1, S2 >::state2().
template<typename S , typename S1 , typename S2 > int tdzdd::ZddIntersection_< S, S1, S2 >::getChild (Word * p, int level, int take) inline
Definition at line 366 of file BinaryOperation.hpp.
References tdzdd::BinaryOperation< S, S1, S2 >::state1(), and tdzdd::BinaryOperation< S, S1, S2 >::state2().
template<typename S , typename S1 , typename S2 > int tdzdd::ZddIntersection_< S, S1, S2 >::getRoot (Word * p) inline
Definition at line 346 of file BinaryOperation.hpp.
References tdzdd::BinaryOperation< S, S1, S2 >::state1(), and tdzdd::BinaryOperation< S, S1, S2 >::state2().
template<typename S , typename S1 , typename S2 > size_t tdzdd::ZddIntersection_< S, S1, S2 >::hash_code (void const * p, int level) const inline
Definition at line 406 of file BinaryOperation.hpp.
References tdzdd::BinaryOperation< S, S1, S2 >::state1(), and tdzdd::BinaryOperation< S, S1, S2 >::state2().
template<typename S , typename S1 , typename S2 > int tdzdd::ZddIntersection_< S, S1, S2 >::merge_states (void * p1, void * p2) inline
Definition at line 391 of file BinaryOperation.hpp.
References tdzdd::BinaryOperation< S, S1, S2 >::state1(), and tdzdd::BinaryOperation< S, S1, S2 >::state2().
template<typename S , typename S1 , typename S2 > void tdzdd::ZddIntersection_< S, S1, S2 >::print_state (std::ostream & os, void const * p, int level) const inline
Definition at line 416 of file BinaryOperation.hpp.
References tdzdd::BinaryOperation< S, S1, S2 >::state1(), and tdzdd::BinaryOperation< S, S1, S2 >::state2().
template<typename S , typename S1 , typename S2 > void* tdzdd::ZddIntersection_< S, S1, S2 >::state1 (void * p) const inline
Definition at line 321 of file BinaryOperation.hpp.
template<typename S , typename S1 , typename S2 > void const* tdzdd::ZddIntersection_< S, S1, S2 >::state1 (void const * p) const inline
Definition at line 325 of file BinaryOperation.hpp.
template<typename S , typename S1 , typename S2 > void* tdzdd::ZddIntersection_< S, S1, S2 >::state2 (void * p) const inline
Definition at line 329 of file BinaryOperation.hpp.
template<typename S , typename S1 , typename S2 > void const* tdzdd::ZddIntersection_< S, S1, S2 >::state2 (void const * p) const inline
Definition at line 333 of file BinaryOperation.hpp.
template<typename S , typename S1 , typename S2 > static int tdzdd::ZddIntersection_< S, S1, S2 >::wordSize (int size) inline static
Definition at line 317 of file BinaryOperation.hpp.
Member Data Documentation
template<typename S , typename S1 , typename S2 > Spec1 tdzdd::ZddIntersection_< S, S1, S2 >::spec1
Definition at line 312 of file BinaryOperation.hpp.
template<typename S , typename S1 , typename S2 > Spec2 tdzdd::ZddIntersection_< S, S1, S2 >::spec2
Definition at line 313 of file BinaryOperation.hpp.
template<typename S , typename S1 , typename S2 > int const tdzdd::ZddIntersection_< S, S1, S2 >::stateWords1
Definition at line 314 of file BinaryOperation.hpp.
template<typename S , typename S1 , typename S2 > int const tdzdd::ZddIntersection_< S, S1, S2 >::stateWords2
Definition at line 315 of file BinaryOperation.hpp.
The documentation for this struct was generated from the following file:
include/tdzdd/op/BinaryOperation.hpp