TdZdd: tdzdd::NodeTableHandler< ARITY >::Object Struct Reference
tdzdd::NodeTableHandler< ARITY >::Object Struct Reference
Public Member Functions
Object (int n)
Object (NodeTableEntity< ARITY > const &entity)
void ref ()
void deref ()
Public Attributes
unsigned refCount
NodeTableEntity< ARITY > entity
Detailed Description
template<int ARITY>
struct tdzdd::NodeTableHandler< ARITY >::Object
Definition at line 403 of file NodeTable.hpp.
Constructor & Destructor Documentation
template<int ARITY> tdzdd::NodeTableHandler< ARITY >::Object::Object (int n) inline
Definition at line 407 of file NodeTable.hpp.
template<int ARITY> tdzdd::NodeTableHandler< ARITY >::Object::Object (NodeTableEntity< ARITY > const & entity) inline
Definition at line 411 of file NodeTable.hpp.
Member Function Documentation
template<int ARITY> void tdzdd::NodeTableHandler< ARITY >::Object::deref () inline
Definition at line 420 of file NodeTable.hpp.
Referenced by tdzdd::NodeTableHandler< ARITY >::init(), tdzdd::NodeTableHandler< ARITY >::operator=(), tdzdd::NodeTableHandler< ARITY >::privateEntity(), and tdzdd::NodeTableHandler< ARITY >::~NodeTableHandler().
template<int ARITY> void tdzdd::NodeTableHandler< ARITY >::Object::ref () inline
Definition at line 415 of file NodeTable.hpp.
Referenced by tdzdd::NodeTableHandler< ARITY >::NodeTableHandler(), and tdzdd::NodeTableHandler< ARITY >::operator=().
Member Data Documentation
template<int ARITY> NodeTableEntity<ARITY> tdzdd::NodeTableHandler< ARITY >::Object::entity
Definition at line 405 of file NodeTable.hpp.
Referenced by tdzdd::NodeTableHandler< ARITY >::derefLevel(), tdzdd::NodeTableHandler< ARITY >::init(), tdzdd::NodeTableHandler< ARITY >::operator*(), tdzdd::NodeTableHandler< ARITY >::operator->(), and tdzdd::NodeTableHandler< ARITY >::privateEntity().
template<int ARITY> unsigned tdzdd::NodeTableHandler< ARITY >::Object::refCount
Definition at line 404 of file NodeTable.hpp.
Referenced by tdzdd::NodeTableHandler< ARITY >::derefLevel(), tdzdd::NodeTableHandler< ARITY >::init(), and tdzdd::NodeTableHandler< ARITY >::privateEntity().
The documentation for this struct was generated from the following file:
include/tdzdd/dd/NodeTable.hpp