TdZdd: tdzdd::PathZddByStdMap Struct Reference
tdzdd::PathZddByStdMap Struct Reference
#include <PathZddByStdMap.hpp>
Public Member Functions
PathZddByStdMap (Graph const &graph)
int getRoot (State &mate) const
int getChild (State &mate, int level, int take) const
size_t hashCode (State const &mate) const
Public Member Functions inherited from tdzdd::DdSpec< PathZddByStdMap, std::map< int16_t, int16_t >, 2 >
int datasize () const
void construct (void *p)
int get_root (void *p)
int get_child (void *p, int level, int value)
void getCopy (void *p, State const &s)
void get_copy (void *to, void const *from)
int mergeStates (State &s1, State &s2)
int merge_states (void *p1, void *p2)
void destruct (void *p)
void destructLevel (int level)
size_t hashCode (State const &s) const
size_t hashCodeAtLevel (State const &s, int level) const
size_t hash_code (void const *p, int level) const
bool equalTo (State const &s1, State const &s2) const
bool equalToAtLevel (State const &s1, State const &s2, int level) const
bool equal_to (void const *p, void const *q, int level) const
void printState (std::ostream &os, State const &s) const
void printStateAtLevel (std::ostream &os, State const &s, int level) const
void print_state (std::ostream &os, void const *p, int level) const
Public Member Functions inherited from tdzdd::DdSpecBase< PathZddByStdMap, AR >
PathZddByStdMap & entity ()
PathZddByStdMapconst & entity () const
void printLevel (std::ostream &os, int level) const
std::vector< std::pair< int, int > > findOneInstance () const
Returns a random instance using simple depth-first search without caching.
void dumpDot (std::ostream &os=std::cout, std::string title=typenameof< PathZddByStdMap >()) const
Dumps the node table in Graphviz (dot) format.
Public Attributes
Graph const & graph
int const n
Additional Inherited Members
Public Types inherited from tdzdd::DdSpec< PathZddByStdMap, std::map< int16_t, int16_t >, 2 >
typedef std::map< int16_t, int16_t > State
Static Public Attributes inherited from tdzdd::DdSpecBase< PathZddByStdMap, AR >
static int const ARITY
Static Protected Member Functions inherited from tdzdd::DdSpecBase< PathZddByStdMap, AR >
static size_t rawHashCode (T const &o)
static size_t rawEqualTo (T const &o1, T const &o2)
Detailed Description
Definition at line 35 of file PathZddByStdMap.hpp.
Constructor & Destructor Documentation
tdzdd::PathZddByStdMap::PathZddByStdMap (Graph const & graph) inline
Definition at line 42 of file PathZddByStdMap.hpp.
Member Function Documentation
int tdzdd::PathZddByStdMap::getChild (State & mate, int level, int take) const inline
Definition at line 54 of file PathZddByStdMap.hpp.
References tdzdd::Graph::edgeInfo(), tdzdd::Graph::EdgeInfo::v1, tdzdd::Graph::EdgeInfo::v1final, tdzdd::Graph::EdgeInfo::v2, and tdzdd::Graph::EdgeInfo::v2final.
int tdzdd::PathZddByStdMap::getRoot (State & mate) const inline
Definition at line 46 of file PathZddByStdMap.hpp.
References n, tdzdd::Graph::vertexSize(), and tdzdd::Graph::virtualMate().
size_t tdzdd::PathZddByStdMap::hashCode (State const & mate) const inline
Definition at line 96 of file PathZddByStdMap.hpp.
Member Data Documentation
Graph const& tdzdd::PathZddByStdMap::graph
Definition at line 38 of file PathZddByStdMap.hpp.
int const tdzdd::PathZddByStdMap::n
Definition at line 39 of file PathZddByStdMap.hpp.
Referenced by getRoot().
The documentation for this struct was generated from the following file:
include/tdzdd/spec/PathZddByStdMap.hpp