TdZdd: tdzdd::ResourceUsage Struct Reference
tdzdd::ResourceUsage Struct Reference
#include <ResourceUsage.hpp>
Public Member Functions
ResourceUsage ()
ResourceUsage (double etime, double utime, double stime, long maxrss)
ResourceUsage & update ()
ResourceUsage operator+ (ResourceUsage const &u) const
ResourceUsage & operator+= (ResourceUsage const &u)
ResourceUsage operator- (ResourceUsage const &u) const
ResourceUsage & operator-= (ResourceUsage const &u)
std::string elapsedTime () const
std::string userTime () const
std::string memory () const
Public Attributes
double etime
double utime
double stime
long maxrss
Friends
std::ostream & operator<< (std::ostream &os, ResourceUsage const &u)
Detailed Description
Definition at line 58 of file ResourceUsage.hpp.
Constructor & Destructor Documentation
tdzdd::ResourceUsage::ResourceUsage () inline
Definition at line 64 of file ResourceUsage.hpp.
References update().
Referenced by operator+(), and operator-().
tdzdd::ResourceUsage::ResourceUsage (double etime, double utime, double stime, long maxrss) inline
Definition at line 68 of file ResourceUsage.hpp.
Member Function Documentation
std::string tdzdd::ResourceUsage::elapsedTime () const inline
Definition at line 128 of file ResourceUsage.hpp.
Referenced by tdzdd::MessageHandler_< os >::step().
std::string tdzdd::ResourceUsage::memory () const inline
Definition at line 140 of file ResourceUsage.hpp.
Referenced by tdzdd::MessageHandler_< os >::step().
ResourceUsage tdzdd::ResourceUsage::operator+ (ResourceUsage const & u) const inline
Definition at line 102 of file ResourceUsage.hpp.
References etime, maxrss, ResourceUsage(), stime, and utime.
ResourceUsage& tdzdd::ResourceUsage::operator+= (ResourceUsage const & u) inline
Definition at line 107 of file ResourceUsage.hpp.
References etime, maxrss, stime, and utime.
ResourceUsage tdzdd::ResourceUsage::operator- (ResourceUsage const & u) const inline
Definition at line 115 of file ResourceUsage.hpp.
References etime, maxrss, ResourceUsage(), stime, and utime.
ResourceUsage& tdzdd::ResourceUsage::operator-= (ResourceUsage const & u) inline
Definition at line 120 of file ResourceUsage.hpp.
References etime, maxrss, stime, and utime.
ResourceUsage& tdzdd::ResourceUsage::update () inline
Definition at line 72 of file ResourceUsage.hpp.
References tdzdd::getWallClockTime().
Referenced by tdzdd::MessageHandler_< os >::begin(), and ResourceUsage().
std::string tdzdd::ResourceUsage::userTime () const inline
Definition at line 134 of file ResourceUsage.hpp.
Friends And Related Function Documentation
std::ostream& operator<< (std::ostream & os, ResourceUsage const & u) friend
Definition at line 146 of file ResourceUsage.hpp.
Member Data Documentation
double tdzdd::ResourceUsage::etime
Definition at line 59 of file ResourceUsage.hpp.
Referenced by operator+(), operator+=(), operator-(), and operator-=().
long tdzdd::ResourceUsage::maxrss
Definition at line 62 of file ResourceUsage.hpp.
Referenced by operator+(), operator+=(), operator-(), and operator-=().
double tdzdd::ResourceUsage::stime
Definition at line 61 of file ResourceUsage.hpp.
Referenced by operator+(), operator+=(), operator-(), and operator-=().
double tdzdd::ResourceUsage::utime
Definition at line 60 of file ResourceUsage.hpp.
Referenced by operator+(), operator+=(), operator-(), and operator-=().
The documentation for this struct was generated from the following file:
include/tdzdd/util/ResourceUsage.hpp